### ISSUE TITLE
Crashed - dump file

### ISSUE THREAD

**Issue by netzgestaltung** [quodlibet/quodlibet#1581]
the crash handler of quodlibet encouraged me to post a dump file here - so i do ;-)

what happened: i switched thrue various views while playing a song - and a big musik folder is added to the library - the detection was still running.

so this might be not a big problem...
DE is gnome 3.14

dump:   

```
=== SYSTEM INFORMATION:
Quod Libet 3.4.-1
Mutagen 1.23
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] linux2
Platform Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.10-utopic

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/quodlibetwindow.py", line 982, in __song_ended
    if song and active_filter and not active_filter(song):

  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/media.py", line 333, in active_filter
    device = model[iter][0]

  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 801, in __getitem__
    aiter = self._getiter(key)

  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 789, in _getiter
    aiter = self.get_iter(key)

  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 823, in get_iter
    path = self._coerce_path(path)

  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 798, in _coerce_path
    return TreePath(path)

  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1146, in __new__
    path = ":".join(str(val) for val in path)

TypeError: 'NoneType' object is not iterable


=== LOG:
D: 741.52: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 741.52: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 742.44: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 742.51: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 742.53: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 742.57: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 742.79: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 742.84: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 742.94: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 742.99: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.01: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.06: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.14: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.17: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.19: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.25: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.30: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.35: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.47: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.52: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 743.66: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 791.49: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 791.56: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 791.60: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 791.64: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 791.69: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 791.76: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 791.81: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 791.86: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 792.31: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 792.34: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 792.48: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 792.52: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 792.58: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 792.71: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 792.77: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 792.98: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.09: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.18: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.23: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.49: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.67: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.71: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.74: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.76: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.81: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.84: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 793.88: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.02: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.29: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.32: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.36: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.38: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.44: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.52: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.57: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.75: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.81: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.81: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.86: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.88: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 794.94: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 795.27: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 795.33: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 795.36: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 795.42: CoPool.add: Added copool function <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>> with id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 795.85: CoPool.remove: Removed copool function id <bound method AlbumList.__scan_paths of <AlbumList object at 0x7f2bc80254b0 (quodlibet+browsers+albums+main+AlbumList at 0x2d4d7b0)>>
D: 813.27: player.gstbe.player.__about_to_finish: About to finish (async)
D: 813.27: player.gstbe.player.__about_to_finish_sync: About to finish (sync)
D: 813.27: player.gstbe.player.__about_to_finish_sync: Select next song in mainloop..
D: 813.27: player.gstbe.player.__about_to_finish_sync: ..done.
D: 813.27: player.gstbe.player.__about_to_finish: About to finish (async): setting uri
D: 813.27: player.gstbe.player.__about_to_finish: About to finish (async): done
D: 814.50: player.gstbe.player.__message: Stream EOS
D: 814.50: GStreamerPlayer._end: End song
```

**Comment by CreamyCookie** [comment]
Closing this one as the media browser was removed (and this is pretty old).
