### ISSUE TITLE
Search crash

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#1608]
via Yatagar...?gmail.com at https://code.google.com/p/quodlibet/issues/detail?id=1560&colspec=Stars%20ID%20Type%20Component%20Milestone%20Summary

> For every character i typed into the searchbox, a crash happened.
> Quodlibet ver 3.0.2
> Ubuntu 14.04 LTS 64bit

Dump_20150409_072730.txt
```plain
=== SYSTEM INFORMATION:
Quod Libet 3.0.2
Mutagen 1.22
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] linux2
Platform Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/search.py", line 184, in __text_parse
    self.activate()

  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/paned.py", line 770, in activate
    songs = filter(self._filter, self._library)

  File "/usr/lib/python2.7/dist-packages/quodlibet/parse/_match.py", line 189, in search
    if self.res.search(data(name)):

TypeError: expected string or buffer



=== LOG: 'Debug'
D: 698.09: PlaylistModel.go_to: Told to go to '/media/eoxuszx/Storage/Resonix/Kateikyoushi Hitman REBORN! Music Collection/Kateikyoushi Hitman REBORN! ED14 Single - gr8 story [SuG]/1. gr8 story.mp3'
D: 698.18: GStreamerPlayer._end: End song
D: 698.18: PlaylistModel.go_to: Told to go to None
D: 698.18: SongFileLibrary._changed: Changing 1 items.
D: 698.18: qltk.completion.__update_song: Updating tag model for 1 songs
D: 698.18: qltk.completion.__update_song: Done updating tag model for 1 songs
D: 698.20: GStreamerPlayer._end: Next song
D: 699.07: qltk.completion.__build_model: Updating tag model for whole library
D: 699.20: qltk.completion.__build_model: Done updating tag model for whole library
D: 699.20: util.copool.remove: Removed copool function id <bound method GObjectMeta.__build_model of <class 'quodlibet.qltk.completion.LibraryTagCompletion'>>
D: 801.86: PlaylistModel.set: Clearing model.
D: 801.89: PlaylistModel.set: Setting 10299 songs.
D: 802.03: PlaylistModel.set: Done filling model.
D: 811.60: PlaylistModel.set: Clearing model.
D: 811.64: PlaylistModel.set: Setting 10299 songs.
D: 811.77: PlaylistModel.set: Done filling model.
D: 830.56: PlaylistModel.set: Clearing model.
D: 830.59: PlaylistModel.set: Setting 10299 songs.
D: 830.73: PlaylistModel.set: Done filling model.
D: 831.40: PlaylistModel.set: Clearing model.
D: 831.44: PlaylistModel.set: Setting 10299 songs.
D: 831.57: PlaylistModel.set: Done filling model.
D: 832.17: PlaylistModel.set: Clearing model.
D: 832.21: PlaylistModel.set: Setting 10299 songs.
D: 832.34: PlaylistModel.set: Done filling model.
D: 841.19: PlaylistModel.set: Clearing model.
D: 841.22: PlaylistModel.set: Setting 10299 songs.
D: 841.36: PlaylistModel.set: Done filling model.
D: 846.68: PluginManager.rescan: Rescanning..
D: 846.68: ModuleScanner.rescan: Rescanning..
D: 846.68: ModuleScanner.rescan: Rescanning done: 0 added, 0 removed, 3 error(s)
D: 846.68: PluginManager.rescan: Rescanning done.
D: 846.69: AnimOsd.__init__: Error parsing config for text ('tuple' object has no attribute 'split') - defaulting to (0.9, 0.9, 0.9, 0.0)
D: 846.69: AnimOsd.__init__: Error parsing config for fill ('tuple' object has no attribute 'split') - defaulting to (0.25, 0.25, 0.25, 0.5)
D: 846.69: AnimOsd.__init__: Error parsing config for shadow ('tuple' object has no attribute 'split') - defaulting to (-1.0, 0.0, 0.0, 0.1)
D: 846.69: AnimOsd.__init__: Error parsing config for outline ('tuple' object has no attribute 'split') - defaulting to (-1.0, 0.0, 0.0, 0.2)
D: 846.69: AnimOsd.__init__: Error parsing config for bcolor ('tuple' object has no attribute 'split') - defaulting to (0.0, 0.0, 0.0, 0.2)
D: 917.09: PluginManager.rescan: Rescanning..
D: 917.09: ModuleScanner.rescan: Rescanning..
D: 917.09: ModuleScanner.rescan: Rescanning done: 0 added, 0 removed, 3 error(s)
D: 917.09: PluginManager.rescan: Rescanning done.
D: 920.01: PluginManager.enable: Enable 'FilterAll'
D: 920.01: PluginManager.save: Saving plugins: 1 active
D: 996.74: config.save: Writing config...
D: 996.74: library.save: Saving all libraries...
D: 996.74: SongFileLibrary.save: Saving contents to '/home/eoxuszx/.quodlibet/songs'.
D: 296.74: config.save: Writing config...
D: 296.74: library.save: Saving all libraries...
D: 596.74: config.save: Writing config...
D: 596.74: library.save: Saving all libraries...


=== LOG: u'Warnings'
W: Couldn't talk to Squeezebox server at localhost:9090


```

**Comment by declension** [comment]
3.0.2 is very old now, and that code has changed.

I think this _might_ be a unicode search issue which is since fixed (perhaps in: revision 43bdd3fb909ffbed950e8e504f2b8b6e568fe74d).

 Please can the OP retry with a newer version of QL.
