### ISSUE TITLE
Crash on library update or search

### ISSUE THREAD

**Issue by ulijh** [quodlibet/quodlibet#1646]
Hi guys,

firstly thanks for this nice piece of software.

Since I added some music a few days ago I keep getting crashes of quodlibet when searching the library or library rescans after removal of ~/.quodlibet. Please see the crash dump below.

Cheers
Uli

Crash dump:
```
=== SYSTEM INFORMATION:
Quod Libet 3.4.1
Mutagen 1.29
Python 2.7.10 (default, May 26 2015, 04:16:29) 
[GCC 5.1.0] linux2
Platform Linux-4.0.7-2-ARCH-x86_64-with-glibc2.2.5

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/quodlibetwindow.py", line 1205, in __browser_cb
    self.songlist.set_songs(songs, sorted)

  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/songlist.py", line 796, in set_songs
    self._sort_songs(songs)

  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/songlist.py", line 735, in _sort_songs
    songs.sort(key=lambda s: s.sort_key, reverse=reverse)

  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/songlist.py", line 735, in <lambda>
    songs.sort(key=lambda s: s.sort_key, reverse=reverse)

  File "/usr/lib/python2.7/site-packages/quodlibet/util/__init__.py", line 728, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)

  File "/usr/lib/python2.7/site-packages/quodlibet/formats/_audio.py", line 98, in sort_key
    return [self.album_key, self.__song_key()]

  File "/usr/lib/python2.7/site-packages/quodlibet/formats/_audio.py", line 86, in __song_key
    human(self.get("title", "")),

  File "/usr/lib/python2.7/site-packages/quodlibet/util/__init__.py", line 416, in human_sort_key
    s = s.decode("utf-8")

  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 10: invalid continuation byte


=== LOG:
D: 929.00: quodlibet._gettext_init: LANGUAGE: None
D: 929.00: quodlibet._gettext_init: LANG: 'de_DE.utf8'
D: 929.02: quodlibet._gettext_init: Translations loaded: '/usr/share/locale/de/LC_MESSAGES/quodlibet.mo'
D: 929.11: qltk.add_signal_watch: Register Python signal handler: 'SIGHUP'
D: 929.11: qltk.add_signal_watch: Register Python signal handler: 'SIGINT'
D: 929.11: qltk.add_signal_watch: Register Python signal handler: 'SIGTERM'
D: 929.11: qltk.add_signal_watch: Register GLib signal handler: 'SIGHUP'
D: 929.11: qltk.add_signal_watch: Register GLib signal handler: 'SIGINT'
D: 929.11: qltk.add_signal_watch: Register GLib signal handler: 'SIGTERM'
D: 929.14: formats.init: MimeType=application/x-flac;audio/aac;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpeg4;audio/mpg;audio/ogg;audio/vorbis;audio/wav;audio/wave;audio/x-aac;audio/x-flac;audio/x-m4a;audio/x-midi;audio/x-mp3;audio/x-mpc;audio/x-mpeg;audio/x-ms-wma;audio/x-ms-wmv;audio/x-musepack;audio/x-oggflac;audio/x-speex;audio/x-tta;audio/x-wav;audio/x-wavpack;audio/x-wma;video/ogg;video/x-ms-asf;video/x-theora;video/x-wmv;
D: 929.18: quodlibet.init: Entering quodlibet.init
D: 929.21: quodlibet._init_debug: Initializing debugging extensions
D: 929.21: quodlibet.init: Finished initialization.
D: 929.21: __main__.main: Initializing main library (~/.quodlibet/songs)
D: 929.21: library.init: Supported formats: aac, midi, mod, monkeysaudio, mp3, mp4, mpc, spc, trueaudio, vgm, wav, wavpack, wma, xiph
D: 929.21: SongFileLibrary.__init__: Initializing SongFileLibrary "main".
D: 929.21: SongFileLibrary.__init__: Using pickling persistence for library "main"
D: 929.21: SongFileLibrary.load: Loading contents of '/home/user/.quodlibet/songs'.
D: 929.22: SongFileLibrary.load: Done loading contents of '/home/user/.quodlibet/songs'.
D: 929.22: quodlibet.init_backend: Initializing audio backend (gstbe)
W: »libgpod« nicht gefunden, iPod-Unterstützung deaktiviert.
D: 929.23: devices.init: Initialisiere Geräte-Backend.
D: 929.23: devices.init: Versuche »UDisks2«
D: 929.24: devices.init: Geräte-Backend initialisiert.
W: »python-feedparser« konnte nicht importiert werden, der Browser für Audio-Feeds wurde deaktiviert.
D: 929.27: SongFileLibrary.__init__: Initializing SongFileLibrary "filesystem".
D: 929.27: SongFileLibrary.__init__: Using pickling persistence for library "filesystem"
D: 929.27: UDisks2Manager._try_build_device: Found device: '/dev/sda1'
D: 929.31: UDisks2Manager._try_build_device: '/dev/sda1' not a media player
D: 929.31: UDisks2Manager._try_build_device: Found device: '/dev/sda2'
D: 929.33: UDisks2Manager._try_build_device: '/dev/sda2' not a media player
D: 929.33: UDisks2Manager._try_build_device: Found device: '/dev/sda3'
D: 929.35: UDisks2Manager._try_build_device: '/dev/sda3' not a media player
D: 929.35: UDisks2Manager._try_build_device: Found device: '/dev/sda4'
D: 929.37: UDisks2Manager._try_build_device: '/dev/sda4' not a media player
D: 929.37: quodlibet.init_plugins: Starting plugin manager
D: 929.37: quodlibet.init_plugins: Scanning folders: ['/usr/lib/python2.7/site-packages/quodlibet/ext/editing', '/usr/lib/python2.7/site-packages/quodlibet/ext/events', '/usr/lib/python2.7/site-packages/quodlibet/ext/playorder', '/usr/lib/python2.7/site-packages/quodlibet/ext/songsmenu', '/usr/lib/python2.7/site-packages/quodlibet/ext/playlist', '/usr/lib/python2.7/site-packages/quodlibet/ext/gstreamer', '/usr/lib/python2.7/site-packages/quodlibet/ext/covers', '/home/user/.quodlibet/plugins']
D: 929.37: plugins.__restore: Restoring plugins: 2
D: 929.37: PluginManager.rescan: Rescanning..
D: 929.37: ModuleScanner.rescan: Rescanning..
D: 929.43: ModuleScanner.rescan: Rescanning done: 70 added, 0 removed, 4 error(s)
D: 929.43: PluginManager.rescan: Rescanning done.
D: 929.43: PluginManager.register_handler: Registering handler: 'EditTagsPluginHandler'
D: 929.43: PluginManager.register_handler: Registering handler: 'RenameFilesPluginHandler'
D: 929.43: PluginManager.register_handler: Registering handler: 'TagsFromPathPluginHandler'
D: 929.43: PluginManager.register_handler: Registering handler: 'GStreamerPlayer'
D: 929.43: PluginManager.register_handler: Registering handler: 'SongsMenuPluginHandler'
D: 929.44: PluginManager.register_handler: Registering handler: 'CoverPluginHandler'
D: 929.44: PluginManager.register_handler: Registering handler: 'PlaylistPluginHandler'
D: 929.44: PluginManager.enable: Enable 'Shuffle Playlist'
D: 929.44: PluginManager.enable: Enable 'Remove Playlist Duplicates'
D: 929.51: PluginManager.register_handler: Registering handler: 'PlayOrder'
D: 929.51: GStreamerPlayer.go_to: Going to None
D: 929.51: PlaylistMux.go_to: Told to go to None
D: 929.51: QueueModel.go_to: Told to go to None
D: 929.51: PlaylistModel.go_to: Told to go to None
D: 929.51: CoPool.add: Added copool function <bound method GObjectMeta.__build_model of <class 'quodlibet.qltk.completion.LibraryTagCompletion'>> with id <bound method GObjectMeta.__build_model of <class 'quodlibet.qltk.completion.LibraryTagCompletion'>>
D: 929.57: CoPool.add: Added copool function <bound method SongFileLibrary.rebuild of <SongFileLibrary object at 0x7f8a76353eb0 (quodlibet+library+libraries+SongFileLibrary at 0x7f8a91064940)>> with id 'library'
D: 929.57: qltk.window.__restore_state: Restore state
D: 929.57: qltk.window.__restore_position: Restore position
D: 929.57: qltk.window.__restore_size: Restore size
D: 929.57: PluginManager.register_handler: Registering handler: 'EventPluginHandler'
D: 929.57: mmkeys.find_active_backend: Trying to find a mmkeys backend
D: 929.57: mmkeys.find_active_backend: Found 'GnomeBackend'
D: 929.58: qltk.session.init: Connected with gnome session manager: /org/gnome/SessionManager/Client20
D: 929.58: CoPool.add: Added copool function <function periodic_config_save at 0x7f8a5310a230> with id <function periodic_config_save at 0x7f8a5310a230>
D: 929.58: CoPool.add: Added copool function <function periodic_library_save at 0x7f8a5310a2a8> with id <function periodic_library_save at 0x7f8a5310a2a8>
D: 929.58: quodlibet.main: Entering quodlibet.main
D: 929.64: quodlibet._override_exceptions: Enabling custom exception handler.
```

**Comment by lazka** [comment]
Can you narrow down which song is causing this?

**Comment by ulijh** [comment]
No, sry, when I try to remove some songs from the library path, it doesn't start at all. I know that some of the songs I added had Cyrillic names and tags...

This is the error I just got:
```W: »libgpod« nicht gefunden, iPod-Unterstützung deaktiviert.
W: »python-feedparser« konnte nicht importiert werden, der Browser für Audio-Feeds wurde deaktiviert.
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 203, in <module>
    main()
  File "/usr/bin/quodlibet", line 135, in main
    restore_cb=lambda:
  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/quodlibetwindow.py", line 584, in __init__
    restore_browser)
  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/quodlibetwindow.py", line 939, in select_browser
    self.browser.activate()
  File "/usr/lib/python2.7/site-packages/quodlibet/browsers/empty.py", line 78, in activate
    songs = self._get_songs()
  File "/usr/lib/python2.7/site-packages/quodlibet/browsers/empty.py", line 75, in _get_songs
    return self._query.filter(self._library)
  File "/usr/lib/python2.7/site-packages/quodlibet/query/_match.py", line 35, in filter
    return filter(self.search, sequence)
  File "/usr/lib/python2.7/site-packages/quodlibet/query/_match.py", line 240, in search
    if self.res.search(unicode(val)):
UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 10: invalid continuation byte
```

**Comment by ulijh** [comment]
Sry for that, wrong button...

**Comment by lazka** [comment]
OK, can you send me your "~/.quodlibet/songs" file per mail? reiter.christoph@gmail.com

**Comment by lazka** [comment]
Thanks.

Our WAVE code doesn't decode the filename derived title tag properly.

**Comment by ulijh** [comment]
Thank you lazka for the quick help and identifying the "bad" songs and fixing the ~/.quodlibet/songs. This and renaming the bad wav-files and everythings works perfectly again. I'll leave the issue open for now 'cause of the "bug" tag.
