### ISSUE TITLE
RuntimeError("threads can only be started once") in LyricsWiki Plugin

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1653]
Dump.txt:

```
=== SYSTEM INFORMATION:
Quod Libet 3.4.1
Mutagen 1.29
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] linux2
Platform Linux-3.13.0-57-generic-x86_64-with-Ubuntu-14.04-trusty

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/util/__init__.py", line 650, in _wrap
    self.func(*self.args)

  File "/home/anon/.quodlibet/plugins/lyricwiki.py", line 160, in set_song
    self._thread.search_song(song, self._callback)

  File "/home/anon/.quodlibet/plugins/lyricwiki.py", line 48, in search_song
    self.start()

  File "/usr/lib/python2.7/threading.py", line 739, in start
    raise RuntimeError("threads can only be started once")

RuntimeError: threads can only be started once


=== LOG:
D: 038.62: PlaylistModel.go_to: Told to go to <GtkTreeIter at 0x7f3bb8038a00>
D: 038.62: GStreamerPlayer._end: End song
D: 038.63: util.cover.manager.run: Found local cover from FilesystemCover
D: 038.63: GStreamerPlayer._end: Next song
D: 038.68: SongFileLibrary._changed: Changing 2 items.
D: 038.68: library.libraries.__changed: Updating affected albums for 2 items
D: 047.99: SongFileLibrary._changed: Changing 1 items.
D: 048.00: library.libraries.__changed: Updating affected albums for 1 items
D: 048.98: GStreamerPlayer.go_to: Going to <GtkTreeIter at 0x8f87a20>
D: 048.98: PlaylistMux.go_to: Told to go to <GtkTreeIter at 0x8f87a20>
D: 048.98: QueueModel.go_to: Told to go to None
D: 048.98: PlaylistModel.go_to: Told to go to <GtkTreeIter at 0x8f87a20>
D: 048.98: GStreamerPlayer._end: End song
D: 048.98: util.cover.manager.run: Found local cover from FilesystemCover
D: 048.99: GStreamerPlayer._end: Next song
D: 049.07: SongFileLibrary._changed: Changing 2 items.
D: 049.07: library.libraries.__changed: Updating affected albums for 2 items
D: 054.33: config.save: Writing config...
D: 054.34: library.save: Saving all libraries...
D: 054.34: SongFileLibrary.save: Saving contents to '/home/anon/.quodlibet/songs'.
D: 067.65: SongFileLibrary._changed: Changing 1 items.
D: 067.65: library.libraries.__changed: Updating affected albums for 1 items
D: 072.66: GStreamerPlayer.go_to: Going to <GtkTreeIter at 0x84dc100>
D: 072.66: PlaylistMux.go_to: Told to go to <GtkTreeIter at 0x84dc100>
D: 072.66: QueueModel.go_to: Told to go to None
D: 072.66: PlaylistModel.go_to: Told to go to <GtkTreeIter at 0x84dc100>
D: 072.66: GStreamerPlayer._end: End song
D: 072.67: util.cover.manager.run: Found local cover from FilesystemCover
D: 072.67: GStreamerPlayer._end: Next song
D: 072.76: SongFileLibrary._changed: Changing 2 items.
D: 072.77: library.libraries.__changed: Updating affected albums for 2 items
D: 085.10: SongFileLibrary._changed: Changing 1 items.
D: 085.10: library.libraries.__changed: Updating affected albums for 1 items
D: 088.00: GStreamerPlayer.go_to: Going to <GtkTreeIter at 0x7f3b9c0af440>
D: 088.00: PlaylistMux.go_to: Told to go to <GtkTreeIter at 0x7f3b9c0af440>
D: 088.00: QueueModel.go_to: Told to go to None
D: 088.00: PlaylistModel.go_to: Told to go to <GtkTreeIter at 0x7f3b9c0af440>
D: 088.00: GStreamerPlayer._end: End song
D: 088.00: util.cover.manager.run: Found local cover from FilesystemCover
D: 088.00: GStreamerPlayer._end: Next song
D: 088.09: SongFileLibrary._changed: Changing 2 items.
D: 088.09: library.libraries.__changed: Updating affected albums for 2 items
D: 095.92: SongFileLibrary._changed: Changing 1 items.
D: 095.92: library.libraries.__changed: Updating affected albums for 1 items
D: 106.72: SongFileLibrary._changed: Changing 1 items.
D: 106.72: library.libraries.__changed: Updating affected albums for 1 items
D: 108.20: GStreamerPlayer.go_to: Going to <GtkTreeIter at 0x837d920>
D: 108.20: PlaylistMux.go_to: Told to go to <GtkTreeIter at 0x837d920>
D: 108.20: QueueModel.go_to: Told to go to None
D: 108.20: PlaylistModel.go_to: Told to go to <GtkTreeIter at 0x837d920>
D: 108.20: GStreamerPlayer._end: End song
D: 108.21: util.cover.manager.run: Found local cover from FilesystemCover
D: 108.21: GStreamerPlayer._end: Next song
D: 108.30: SongFileLibrary._changed: Changing 2 items.
D: 108.30: library.libraries.__changed: Updating affected albums for 2 items
D: 119.31: SongFileLibrary._changed: Changing 1 items.
D: 119.31: library.libraries.__changed: Updating affected albums for 1 items
D: 141.01: SongFileLibrary._changed: Changing 1 items.
D: 141.02: library.libraries.__changed: Updating affected albums for 1 items
D: 161.81: GStreamerPlayer.go_to: Going to <GtkTreeIter at 0x2861a60>
D: 161.81: PlaylistMux.go_to: Told to go to <GtkTreeIter at 0x2861a60>
D: 161.82: QueueModel.go_to: Told to go to None
D: 161.82: PlaylistModel.go_to: Told to go to <GtkTreeIter at 0x2861a60>
D: 161.82: GStreamerPlayer._end: End song
D: 161.82: util.cover.manager.run: Found local cover from FilesystemCover
D: 161.82: GStreamerPlayer._end: Next song
D: 161.92: SongFileLibrary._changed: Changing 2 items.
D: 161.92: library.libraries.__changed: Updating affected albums for 2 items
D: 173.51: GStreamerPlayer.go_to: Going to <GtkTreeIter at 0x5d05800>
D: 173.51: PlaylistMux.go_to: Told to go to <GtkTreeIter at 0x5d05800>
D: 173.51: QueueModel.go_to: Told to go to None
D: 173.51: PlaylistModel.go_to: Told to go to <GtkTreeIter at 0x5d05800>
D: 173.51: GStreamerPlayer._end: End song
D: 173.52: util.cover.manager.run: Found local cover from FilesystemCover
D: 173.52: GStreamerPlayer._end: Next song
```

**Comment by CreamyCookie** [comment]
I'm closing this for now, since I hadn't had this problem ever since.

**Comment by lazka** [comment]
I've had a look at it once but couldn't figure out how this can happen. Maybe you changed something? (considering the plugin failing here is in your home dir and not the one shipped with QL)

**Comment by CreamyCookie** [comment]
Hmm.. I don't remember, but that could really have been the cause. Anyway, thanks for looking into this! :)
