### ISSUE TITLE
Crash at start on ubuntu 12.04

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#1690]
```
>>> quodlibet 
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 224, in <module>
    main(util.argv)
  File "/usr/bin/quodlibet", line 27, in main
    startup_actions, cmds_todo = process_arguments(argv)
  File "/usr/lib/python2.7/dist-packages/quodlibet/cli.py", line 250, in process_arguments
    control('focus', ignore_error=True)
  File "/usr/lib/python2.7/dist-packages/quodlibet/cli.py", line 44, in control
    if not is_running():
  File "/usr/lib/python2.7/dist-packages/quodlibet/cli.py", line 32, in is_running
    return Remote.remote_exists()
  File "/usr/lib/python2.7/dist-packages/quodlibet/remote.py", line 106, in remote_exists
    return fifo.fifo_exists(cls._PATH)
  File "/usr/lib/python2.7/dist-packages/quodlibet/util/fifo.py", line 136, in fifo_exists
    print_d("%r not a FIFO. Removing it." % fifo_path)
NameError: global name 'print_d' is not defined
```

QL version : 3.4.99+7492~6f1ca92-0~ppa0~precise.
Works fine on another machine running ubuntu 14.04.

**Comment by lazka** [comment]
Thanks
