### ISSUE TITLE
Enhancement: Better errors for non-readable files

### ISSUE THREAD

**Issue by lorentrogers** [quodlibet/quodlibet#1721]
I have a bunch of files that don't show up, either because they're formatted incorrectly, or they're corrupted. So, when I launch the app, I get a bunch of `W: Error Loading <filename>` messages, but no clues about how to fix them, or what the problem really is. (I'm still trying to figure out the exact issues with my files, but that's another story.)

I'd propose that a message of some sort be added that says why the file can't be loaded. (As opposed to just showing the folder as being empty, which it's not.)

I'm currently running version 3.2.2 from the Debian repos on Debian 8.

**Comment by lazka** [comment]
Three things:

* Running with "--debug" should show more info (the Python stacktrace) when loading fails
* Loading mostly depends on the mutagen library and both Quod Libet/mutagen are quite old in jessie. Please try our stable repository: https://quodlibet.readthedocs.org/en/latest/downloads.html#debian which contains new versions of both.
* Either way, feel free to mail me some affected files to reiter.christoph@gmail.com and I can have a look on why they fail and maybe fix mutagen.

**Comment by lazka** [comment]
And yeah, error reporting should be improved/exposed in the UI in some way.

**Comment by declension** [comment]
+1
Perhaps a collapsible log view panel would be useful, much like an IDE...

**Comment by lorentrogers** [comment]
Emailed a file, in case you were interested. It's probably corrupt, but worth testing out. 

Here's the output I get during debug:

W: Error loading '/mnt/music/Classical/Philip Glass/Minimalism/08 - Company - Movement 3.flac'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/quodlibet/formats/__init__.py", line 74, in MusicFile
    return _infos[ext](filename)
  File "/usr/lib/python2.7/dist-packages/quodlibet/formats/xiph.py", line 491, in info
    audio = mutagen.File(filename, options=ogg_formats)
  File "/usr/lib/python2.7/dist-packages/mutagen/_file.py", line 230, in File
    return Kind(filename)
  File "/usr/lib/python2.7/dist-packages/mutagen/_file.py", line 38, in __init__
    self.load(filename, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mutagen/flac.py", line 705, in load
    self.__check_header(fileobj)
  File "/usr/lib/python2.7/dist-packages/mutagen/flac.py", line 828, in __check_header
    "%r is not a valid FLAC file" % fileobj.name)
FLACNoHeaderError: '/mnt/music/Classical/Philip Glass/Minimalism/08 - Company - Movement 3.flac' is not a valid FLAC file

**Comment by lorentrogers** [comment]
Yep -- just updated, same issue on 3.5.1

Supported formats: AAC, ASF, FLAC, MIDI,
MOD/XM/IT, MPEG-1/2, MPEG-4, Monkey's Audio,
Musepack, Ogg FLAC, Ogg Opus, Ogg Speex,
Ogg Theora, Ogg Vorbis, SPC700, True Audio,
VGM, WAVE, WavPack

Audio device: GStreamer (alsasink device=hw:1,0)
Python: 2.7.9
Mutagen: 1.31
GTK+: 3.14.5
PyGObject: 3.14.0
GStreamer: 1.4.4.0

**Comment by lorentrogers** [comment]
In my case, it looks like the files were never unencrypted from ownCloud. (Possible issue: https://github.com/owncloud/apps/issues/1594) Thanks to @lazka for pointing me in the right direction. 

Regardless, there should probably still be a better error message for why the file can't be read.
