### ISSUE TITLE
AttributeError: 'int' object has no attribute 'encode' when writing tag changes.

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#1725]
Quod Libet 3.5.-1
Changing a tag in many files and attempting to write them to the files results in this error:

    D: 228.48: MP3File.write: Not using invalid language code 'English' in TLAN
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/edittags.py", line 799, in __save_files
        song.write()
      File "/usr/lib/python2.7/dist-packages/quodlibet/formats/_id3.py", line 329, in write enc = encoding_for(self[key])
      File "/usr/lib/python2.7/dist-packages/quodlibet/formats/_id3.py", line 24, in encoding_for return 3 if isascii(s) else 1
      File "/usr/lib/python2.7/dist-packages/quodlibet/util/string/__init__.py", line 19, in isascii string.encode("ascii")
    AttributeError: 'int' object has no attribute 'encode'

Here is an example dict(songs[0]) from the Python Console: https://dpaste.de/knKu

Notice, that this behavior is different from that of editing just one song, which is working fine. Even with the problematic songs.

**Comment by pschwede** [comment]
Nevermind. I found the cause: I did song["rating"] = 0 for some songs before. That's where the int came from.
