### ISSUE TITLE
Crash trying to add a tag

### ISSUE THREAD

**Issue by ArchangeGabriel** [quodlibet/quodlibet#1757]
I was trying to add a musicbrainz_artistid for several selected tracks using ExFalso, and it crashed while clicking on Add after pasting the id (reproducible).

I’m running ExFalso 3.5.1 on ArchLinux.

MiniDump:
```
=== SYSTEM INFORMATION:
Quod Libet 3.5.1
Mutagen 1.31
Python 2.7.10 (default, Sep  7 2015, 13:51:49) 
[GCC 5.2.0] linux2
Platform Linux-4.2.5-1-ARCH-x86_64-with-glibc2.2.5

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/edittags.py", line 693, in __add_tag
    self.__add_new_tag(model, tag, value)

  File "/usr/lib/python2.7/site-packages/quodlibet/qltk/edittags.py", line 654, in __add_new_tag
    assert isinstance(value, unicode)

AssertionError
```

**Comment by lazka** [comment]
3.5.2 will come out this week.

Workaround: Add it as "musicbrainz_artistid2" and rename afterwards to "musicbrainz_artistid"

**Comment by ArchangeGabriel** [comment]
OK, thanks!
