### ISSUE TITLE
Last.fm Sync: ImportError: no dbm clone found; tried ['dbhash', 'gdbm', 'dbm', 'dumbdbm']

### ISSUE THREAD

**Issue by LordSputnik** [quodlibet/quodlibet#1777]
I just downloaded and installed Quod Libet 3.5.1 on Windows. Library loading/playback works, but I just tried to refresh my playcounts using the Last.fm Sync plugin (which works on Linux). However, I'm seeing the following error in the console:

    Traceback (most recent call last):
      File "quodlibet\qltk\songsmenu.pyc", line 211, in __handle
      File "quodlibet\ext\songsmenu\lastfmsync.pyc", line 253, in plugin_songs
      File "shelve.pyc", line 239, in open
      File "shelve.pyc", line 222, in __init__
      File "anydbm.pyc", line 53, in <module>
    ImportError: no dbm clone found; tried ['dbhash', 'gdbm', 'dbm', 'dumbdbm']

This seems like it's an issue with bundling, from the few Google results I've looked at.

**Comment by lazka** [comment]
Thanks.
