### ISSUE TITLE
global name 'gtk_version' is not defined when opening preferences or plugins dialog

### ISSUE THREAD

**Issue by lpinner** [quodlibet/quodlibet#1788]
I get a dump (extract below) when opening the preferences or plugins winodws.

 Looks like the issue was fixed by this [commit](https://github.com/quodlibet/quodlibet/commit/ac04b2805e2dd0932c76bae4ebe31f1d657b651a#diff-2643b9c22df9fb50ff62fabcc9b72295R15). 

Just raising a ticket in case any other users stumble across this given QL 3.5.2 was only published in the stable PPA a couple of days ago.
 
```=== SYSTEM INFORMATION:
Quod Libet 3.5.2
Mutagen 1.31
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] linux2
Platform Linux-4.2.0-23-generic-x86_64-with-Ubuntu-15.10-wily

=== STACK TRACE
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/quodlibetwindow.py", line 1179, in __plugins
    window = PluginWindow(self)

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/pluginwin.py", line 349, in __init__
    if not self.has_close_button():

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/window.py", line 163, in has_close_button
    if wm_name == "GNOME Shell" and gtk_version < (3, 18):

NameError: global name 'gtk_version' is not defined
```

**Comment by lazka** [comment]
argh... worst release ever. Thanks for the report.

**Comment by lazka** [comment]
New release is out, PPA is updated. Thanks again.
