### ISSUE TITLE
Crashing (repeatedly)

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#1823]
So, I have waited a bit before reporting this, but I have no idea what's causing it. Whether I'm playing a radio stream or something locally, it seems to just randomly crash now and then. Interestingly, `~/.quodlibet/dumps` doesn't contain a single log file from 2016.

I just ran QuodLibet in the terminal, clicked on another song and got a Segmentation fault. (This didn't happen again when I clicked on that song after restarting QL.) Still nothing in `~/.quodlibet/dumps`.

Version: 3.5.3 — This didn't happen in earlier versions, although I don't know in which version it started.

**Comment by lazka** [comment]
Which distro+version?

**Comment by CreamyCookie** [comment]
Ubuntu 15.10 (64 bit)
Kernel: 4.2.0-27-generic

I just noticed that the last playcount and rating modifications weren't saved.

**Comment by lazka** [comment]
If you install "python-faulthandler" it should print the crashing library to the terminal.

Does it happen after you do some action? like seeking/pausing etc..?

**Comment by CreamyCookie** [comment]
> Does it happen after you do some action? like seeking/pausing etc..?

No, it also happens, when QL is running in the background.

> If you install "python-faulthandler" it should print the crashing library to the terminal.

Okay, I installed it. (Cool! faulthandler is [part of the standard library](https://docs.python.org/3.5/library/faulthandler.html) since Python 3.3)

Here's the result of a crash:

```
Fatal Python error: Segmentation fault

Thread 0x00007f5768ff9700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 389 in _handle_results
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f57697fa700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 336 in _handle_tasks
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f5769ffb700:
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 327 in _handle_workers
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f576a7fc700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f576affd700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f576b7fe700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f576bfff700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f5790d68700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f5791569700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f5791d6a700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f579256b700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f57a48bb700:
  File "/usr/lib/python2.7/threading.py", line 340 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/home/pirat/.quodlibet/plugins/lyricswindow.py", line 135 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Current thread 0x00007f5825550700:
  File "/usr/lib/python2.7/dist-packages/quodlibet/__init__.py", line 737 in main
  File "/usr/bin/quodlibet", line 209 in main
  File "/usr/bin/quodlibet", line 225 in <module>
Segmentation fault
```

**Comment by lazka** [comment]
> Okay, I installed it. (Cool! faulthandler is part of the standard library since Python 3.3)

Yeah, ideally we could integrate crash/exception handling better and provide a way to submit the log to a some service on the next start.

On the crash: This looks like /home/pirat/.quodlibet/plugins/lyricswindow.py is the problem.

**Comment by CreamyCookie** [comment]
Oh, good thing that the pull request isn't merged yet. Any idea what could cause this? It must be code that invokes some extension or something that's not pure Python, right?

**Comment by lazka** [comment]
I don't see any obvious error. I've ported the plugin to WebKit2 recently: https://github.com/quodlibet/quodlibet/commit/e2bf01f04fce4f16677affb01e99050867104733 which uses a separate process for the web stuff. Maybe that helps if webkit is the cause.

**Comment by CreamyCookie** [comment]
Good idea.

I've installed `gir1.2-webkit2-4.0` and tried it, but I get the following exception. Anything that I missed?

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/lyricwiki.py", line 29, in <module>
    from gi.repository import WebKit, Gtk, GLib
  File "/usr/lib/python2.7/dist-packages/gi/importer.py", line 158, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 271, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 120, in __init__
    repository.require(namespace, version)
RepositoryError: Requiring namespace 'JavaScriptCore' version '3.0', but '4.0' is already loaded
```

**Comment by lazka** [comment]
You need to use the development version of quodlibet as WebKit1 and WebKit2 can't coexist in the same process.

**Comment by CreamyCookie** [comment]
@lazka Nice! I think it's fixed by porting it to WebKit2 as you suggested. QL has now been running for a few hours without crashing. :)

Regarding the PR #1709: Sorry for the noob question, but how do I merge?
