### ISSUE TITLE
setup.py test fails - QL 3.6 on OS X

### ISSUE THREAD

**Issue by urielz** [quodlibet/quodlibet#1886]
looks like not everything that is needed is in the bundle?

```
./setup.py test
Traceback (most recent call last):
  File "./setup.py", line 27, in <module>
    import quodlibet
  File "/Users/uriel/quodlibet/quodlibet/quodlibet/__init__.py", line 21, in <module>
    from quodlibet.util import set_process_title, environ, cached_func
  File "/Users/uriel/quodlibet/quodlibet/quodlibet/util/__init__.py", line 30, in <module>
    from quodlibet.util.path import iscommand
  File "/Users/uriel/quodlibet/quodlibet/quodlibet/util/path.py", line 24, in <module>
    from Foundation import NSString
ImportError: No module named Foundation
```

**Comment by lazka** [comment]
looks like you are not using the bundle at all

Did you have a look at: https://quodlibet.readthedocs.org/en/latest/development/devenv.html#macosx-logo-os-x ?

**Comment by urielz** [comment]
Thanks
