### ISSUE TITLE
ImportError: Mutagen 1.27 required. 1.25.1 found.

### ISSUE THREAD

**Issue by kenden** [quodlibet/quodlibet#1888]
On Linux Mint Debian Edition 2, after installing using the stable repo:
https://quodlibet.readthedocs.org/en/latest/downloads.html#debian
I get the message:
```
$ quodlibet
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 225, in <module>
    main(util.argv)
  File "/usr/bin/quodlibet", line 25, in main
    quodlibet.init_cli()
  File "/usr/lib/python2.7/dist-packages/quodlibet/__init__.py", line 494, in init_cli
    _init_formats()
  File "/usr/lib/python2.7/dist-packages/quodlibet/__init__.py", line 473, in _init_formats
    init()
  File "/usr/lib/python2.7/dist-packages/quodlibet/formats/__init__.py", line 33, in init
    (MinVersions.MUTAGEN, mutagen.version_string))
ImportError: Mutagen 1.27 required. 1.25.1 found.
```
It seems to be this issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807526
It says "Updating python-mutagen to the latest version solved the problem."

Another related issue:
https://github.com/quodlibet/quodlibet/issues/1771

Version info:
```
$ uname -a
Linux qna-d400 3.16.0-4-586 #1 Debian 3.16.7-ckt7-1 (2015-03-01) i686 GNU/Linux
qna@qna-d400 ~ $ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=2
DISTRIB_CODENAME=betsy
DISTRIB_DESCRIPTION="LMDE 2 Betsy"

qna@qna-d400 ~ $ cat /etc/debian_version 
8.3

$ dpkg --list |grep quodlibet  # quodlibet --version also crashes
ii  exfalso                                      3.5.3-0~ppa0~quodlibet~stable        all          audio tag editor for GTK+
ii  quodlibet                                    3.5.3-0~ppa0~quodlibet~stable        all          audio library manager and player for GTK3
```

Note: The quodlibet from the debian repo worked fine but was old: version 3.2.2.

**Comment by kenden** [comment]
Fixed by:
```
$ sudo apt-get update
$ sudo apt-get install python-dev build-essential  python-pip
$ sudo pip install --upgrade pip
$ sudo pip install --upgrade mutagen
Collecting mutagen
  Downloading mutagen-1.31.tar.gz (897kB)
    100% |████████████████████████████████| 901kB 567kB/s 
Building wheels for collected packages: mutagen
  Running setup.py bdist_wheel for mutagen ... done
  Stored in directory: /root/.cache/pip/wheels/52/de/01/86c9fc612017a4010465876a3f44bb192902a72686efc427fd
Successfully built mutagen
Installing collected packages: mutagen
  Found existing installation: mutagen 1.25.1
    DEPRECATION: Uninstalling a distutils installed project (mutagen) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling mutagen-1.25.1:
      Successfully uninstalled mutagen-1.25.1
Successfully installed mutagen-1.31

Hope it helps someone.

**Comment by kenden** [comment]
@lazka reopen to install the proper version of mutagen with Quodlibet ?

**Comment by lazka** [comment]
Yeah, the mutagen dependency version is missing in the PPA. But newest mutagen is in the PPA.. maybe you hit it due to mint not being ubuntu..

**Comment by lazka** [comment]
Should be fixed now.
