### ISSUE TITLE
Missing Namespace

### ISSUE THREAD

**Issue by morpheusbeing** [quodlibet/quodlibet#1933]
After update on Debian Stretch:

    Traceback (most recent call last):
    File "/usr/bin/quodlibet", line 231, in <module>
    main(util.argv)
    File "/usr/bin/quodlibet", line 35, in main quodlibet.init()
    File "/usr/lib/python2.7/dist-packages/quodlibet/__init__.py", line 555, in init _init_gtk()
    File "/usr/lib/python2.7/dist-packages/quodlibet/__init__.py", line 283, in _init_gtk
    gi.require_version('Soup', '2.4')
    File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 102, in require_version raise    ValueError('Namespace %s not available' % namespace)
    ValueError: Namespace Soup not available

**Comment by lazka** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820443 ?

But this should be fixed in testing for a while now.. hmm

**Comment by morpheusbeing** [comment]
The fix suggested fixed the problem, gir1.2-soup-2.4 was missing, working know that I have installed it.

Thank you very much.
