### ISSUE TITLE
quodlibet and exfalso crash with ConfigParser.MissingSectionHeaderError

### ISSUE THREAD

**Issue by kylebarbour** [quodlibet/quodlibet#1951]
Both quodlibet and exfalso have begun to regularly crash with similar errors immediately upon opening (in both cases, the programs fail to load). System information:

distribution: Ubuntu 14.04.4 LTS trusty
kernel:  3.19.0-59-generic #65~14.04.1-Ubuntu SMP
quodlibet: 3.0.2
exfalso: 3.0.2

quodlibet prints the following terminal error:

 ```
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 445, in <module>
    main()
  File "/usr/bin/quodlibet", line 42, in main
    config.init(const.CONFIG)
  File "/usr/lib/python2.7/dist-packages/quodlibet/config.py", line 273, in init
    _config.read(rc_files)
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/kyle/.quodlibet/config, line: 1
'\xdb\xea\xe1`\xe2\xb5\xe3A\xe9\xbf\xed+\xbf\xac\xec\xca=\xe3\x9a5\xbf+(\xb3\x90\xf3\xf0\xd8*\xd7\x12\xb2\x16\xa1\x12]&\xb2\xdfA2\xb9T\x99\xc1$v[(\xf3\x85\x92d>\x0b\xe6\xb6\x00\xd2\xf5\x85u\xde\xf4~\xee\xa5P\x96N\x19\x1b3\xa9g\x1f*\xd0\x01SU;\xd5F\xe1+T\xa9%M\xf0\x80m\x1e\xedr\x15KQ\xa8t{e4\xecg\x16\xae\x9d\x01\xb0E\x80!9\x0beyX$\xa30S\x80\x98E +:O>ViD\xa6]1\x86\xd6$\xa17\xd9\x8a\'\x83\x8d\x84\x9d\xd1\x0e\x02/\xab\x80y\x8b\x90\xd8\x9d\xd1\xf2\xac\x90\x88\xa7)3\xe0";}fb\x947\xe2\xea\xf4\x11\xd2\x1eihj\xeb\x13\x7f*e\xect\xef\xec~e+-\x00m\xa0\x08E\xae(#v\xc5\x88\xdd\x00g\x0f\x89K\xa8\x8c9\xce\'Wt\xa8hO6wSy\x04\x04>[\x8a\x97Z\xe6\xe6\x1b&\xc5\xf9\x8a\x07_\x16\xb8\x9b:\xa2\xa4\x95\xcb\x14>\xc7#R\xfe\xad\x8eyD\x8b\x97\xc5\xf4\x02C3\xe3h\xfc\xbc&\xd0\x08y(\x02;\xbb\xbbP\x17\x10\xf8F\xb2\xd1\xf4\x1a\xf13\x9d2x\xe1,\xf3w\xc2\xf6/\xa8M[wBC\x9a\x07\x94 \x1e\x99\xa1\xc4\xf7@\x1f|\xb65Q\'\n'
```

exfalso provide a similar trace:

```
Traceback (most recent call last):
  File "/usr/bin/exfalso", line 58, in <module>
    main()
  File "/usr/bin/exfalso", line 33, in main
    config.init(const.CONFIG)
  File "/usr/lib/python2.7/dist-packages/quodlibet/config.py", line 273, in init
    _config.read(rc_files)
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /home/kyle/.quodlibet/config, line: 1
'\xdb\xea\xe1`\xe2\xb5\xe3A\xe9\xbf\xed+\xbf\xac\xec\xca=\xe3\x9a5\xbf+(\xb3\x90\xf3\xf0\xd8*\xd7\x12\xb2\x16\xa1\x12]&\xb2\xdfA2\xb9T\x99\xc1$v[(\xf3\x85\x92d>\x0b\xe6\xb6\x00\xd2\xf5\x85u\xde\xf4~\xee\xa5P\x96N\x19\x1b3\xa9g\x1f*\xd0\x01SU;\xd5F\xe1+T\xa9%M\xf0\x80m\x1e\xedr\x15KQ\xa8t{e4\xecg\x16\xae\x9d\x01\xb0E\x80!9\x0beyX$\xa30S\x80\x98E +:O>ViD\xa6]1\x86\xd6$\xa17\xd9\x8a\'\x83\x8d\x84\x9d\xd1\x0e\x02/\xab\x80y\x8b\x90\xd8\x9d\xd1\xf2\xac\x90\x88\xa7)3\xe0";}fb\x947\xe2\xea\xf4\x11\xd2\x1eihj\xeb\x13\x7f*e\xect\xef\xec~e+-\x00m\xa0\x08E\xae(#v\xc5\x88\xdd\x00g\x0f\x89K\xa8\x8c9\xce\'Wt\xa8hO6wSy\x04\x04>[\x8a\x97Z\xe6\xe6\x1b&\xc5\xf9\x8a\x07_\x16\xb8\x9b:\xa2\xa4\x95\xcb\x14>\xc7#R\xfe\xad\x8eyD\x8b\x97\xc5\xf4\x02C3\xe3h\xfc\xbc&\xd0\x08y(\x02;\xbb\xbbP\x17\x10\xf8F\xb2\xd1\xf4\x1a\xf13\x9d2x\xe1,\xf3w\xc2\xf6/\xa8M[wBC\x9a\x07\x94 \x1e\x99\xa1\xc4\xf7@\x1f|\xb65Q\'\n'
```

Removing ~/.quodlibet/config fixes the problem, although it's not clear to me if that erases any of my preferences (on surface look, I didn't see any obvious changes).

Any thoughts on why this occurred?

**Comment by lazka** [comment]
Probably a computer/kernel crash corrupting the config file. This shouldn't happen in newer quodlibet versions. If you are a frequent user of quodlibet I recommend using our latest version through the PPA: https://quodlibet.readthedocs.io/en/latest/downloads.html#ubuntu

**Comment by lazka** [comment]
> Removing ~/.quodlibet/config fixes the problem, although it's not clear to me if that erases any of my preferences (on surface look, I didn't see any obvious changes).

It resets all preferences, but the library is in a separate file.

**Comment by kylebarbour** [comment]
Understood. Thank you for the help!
