### ISSUE TITLE
ValueError while storing float to a MP4 tag

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#2028]
BPM in MP4 doesn't seem to store float but integers instead. QL should do some rounding here.

```log
=== SYSTEM INFORMATION:
Quod Libet 3.8 (development, 3142815)
Mutagen 1.35.-1
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] linux2
Platform Linux-4.4.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
=== STACK TRACE

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/edittags.py", line 802, 
in __save_files
    song.write()

  File "/usr/lib/python2.7/dist-packages/quodlibet/formats/mp4.py", line 127, in
 write
    values = list(map(int, values))

ValueError: invalid literal for int() with base 10: '95.490'

```

**Comment by lazka** [comment]
Thanks
