### ISSUE TITLE
Quodlibet does not start. ValueError: Namespace Soup not available

### ISSUE THREAD

**Issue by belkka** [quodlibet/quodlibet#2079]
```
$ quodlibet
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 228, in <module>
    main(util.argv)
  File "/usr/bin/quodlibet", line 33, in main
    quodlibet.init()
  File "/usr/lib/python2.7/dist-packages/quodlibet/__init__.py", line 560, in init
    _init_gtk()
  File "/usr/lib/python2.7/dist-packages/quodlibet/__init__.py", line 299, in _init_gtk
    gi.require_version('Soup', '2.4')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Soup not available
$ screenfetch
         _,met$$$$$gg.           user@computer
      ,g$$$$$$$$$$$$$$$P.        OS: Debian unstable sid
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.7.0-1-amd64
   ,$$P'              `$$$.      Uptime: 3h 43m
  ',$$P       ,ggs.     `$$b:    Packages: 1873
  `d$$'     ,$P"'   .    $$$     Shell: sh
   $$P      d$'     ,    $$P     Resolution: 1366x768
   $$:      $$.   -    ,d$$'     DE: XFCE
   $$\;      Y$b._   _,d$P'      WM: Xfwm4
   Y$$.    `.`"Y$$$$P"'          WM Theme: axe
   `$$b      "-.__               GTK Theme: Xfce-light [GTK2]
    `Y$$                         Icon Theme: gnome-wine
     `Y$$.                       Font: Liberation Sans 10
       `$$b.                     CPU: Intel Pentium CPU P6200 @ 931MHz
         `Y$$b.                  GPU: Mesa DRI Intel(R) Ironlake Mobile 
            `"Y$b._              RAM: 1439MiB / 3757MiB
                `""""           
                                
$ 
 
```

**Comment by lazka** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834771
