### ISSUE TITLE
python3: pycairo broken in msys2

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2133]
import fails:

```
$ python3
Python 3.5.2 (default, Nov  7 2016, 14:30:59)  [GCC 6.2.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cairo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw32/lib/python3.5/site-packages\cairo\__init__.py", line 18, in <module>
    from ._cairo import *
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 5: invalid continuation byte
>>>
```

https://github.com/Alexpux/MINGW-packages/issues/195

**Comment by lazka** [comment]
Fixed: https://github.com/Alexpux/MINGW-packages/pull/2000
