### ISSUE TITLE
PY3: Audio Error

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2153]
Quite a lot of separate failures, but the trickiest one so far seems to be related to `urllib`:

```
Traceback (most recent call last):
  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/browsers/audiofeeds.py", line 360, in __download
    DownloadWindow.download(source, target, self)
  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/qltk/downloader.py", line 32, in download
    win._download(source, target)
  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/qltk/downloader.py", line 146, in _download
    self.__start_next()
  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/qltk/downloader.py", line 109, in __start_next
    sock = url.fp._sock
```

**Comment by lazka** [comment]
An async task API would be nice.

Maybe something like this: https://bpaste.net/show/6b96ee78531e ?
Any thoughts?

**Comment by declension** [comment]
That could be good... thoguh can't we use the existing task / pulse stuff actually? Either way, the http stuff here needs a rewrite probably, it'd be good to use either `requests` or the existing `libsoup` (which definitely does async), this feels a bit anomalous (and also low level now).

**Comment by declension** [comment]
I think this can be shut now - haven't seen it for ages
