### ISSUE TITLE
test commando not working (problem with setlocale)

### ISSUE THREAD

**Issue by scootergrisen** [quodlibet/quodlibet#2167]
I try running with Python 2.7 on Debian Linux:
`./setup.py test --to-run PO.da`

And get:
```
running test
Traceback (most recent call last):
  File "./setup.py", line 111, in <module>
    main()
  File "./setup.py", line 107, in main
    setup(**setup_kwargs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/[USERNAME]/quodlibet/quodlibet/gdist/tests.py", line 49, in run
    import tests
  File "/home/[USERNAME]/quodlibet/quodlibet/tests/__init__.py", line 209, in <module>
    init_test_environ()
  File "/home/[USERNAME]/quodlibet/quodlibet/tests/__init__.py", line 188, in init_test_environ
    environ["LANG"] = locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

```
    # try to make things the same in case a different locale is active.
    # LANG for gettext, setlocale for number formatting etc.
    # Note: setlocale has to be called after Gtk.init()
    if os.name != "nt":
        environ["LANG"] = locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
    else:
        environ["LANG"] = "en_US.utf8"
        locale.setlocale(locale.LC_ALL, "english")

```
Changing:
`        environ["LANG"] = locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
`
To:
`        environ["LANG"] = locale.setlocale(locale.LC_ALL, "da_DK.UTF-8")
`
Makes it run for me so i guess i did not have en_US.UTF-8 installed.
I installed it with sudo dpkg-reconfigure locales but maybe change the test so people can run it without it or is it normal that code expect to have it?

**Comment by lazka** [comment]
Some tests currently expect number formatting to follow en_US rules.
