### ISSUE TITLE
Add the ability to get song length and current play time via CLI

### ISSUE THREAD

**Issue by ReactorofR** [quodlibet/quodlibet#2212]
I'd like these so I can output the information for my bar.

EDIT: I guess I can already get the length currently but I don't see a way to get the second it's at

**Comment by lazka** [comment]
There is a 0.0-1.0 progress value returned by "--status". But invoking quodlibet all the time will result in quite a bit of load, I'd recommend to use our dbus interface instead or the mpris dbus interface provided by the mpris plugin.

**Comment by ReactorofR** [comment]
Thanks. I made a little python script to get the info from dbus.

```python
import dbus
import time

bus = dbus.SessionBus()
quodlibet_bus = bus.get_object('net.sacredchao.QuodLibet','/net/sacredchao/QuodLibet')
is_playing = quodlibet_bus.IsPlaying()
if is_playing :
    symbol = ''
else :
    symbol = ''
try:
    song = quodlibet_bus.CurrentSong()
    artist = str(song['artist'])
    title = str(song['title'])
    length = divmod(float(song['~#length']),60)
    current_pos = (divmod(quodlibet_bus.GetPosition()/1000,60))
    output = f"{symbol} {artist} - {title} {int(current_pos[0]):0>2}:{int(current_pos[1]):0>2}/{int(length[0]):0>2}:{int(length[1]):0>2}"
except :
    output = f"{symbol} Nothing Playing"
print(output)```

**Comment by lazka** [comment]
:+1:

**Comment by beucismis** [comment]
```sh
$ python3 playing.py 
Traceback (most recent call last):
  File "/home/adil/Scripts/current_playing.py", line 6, in <module>
    is_playing = quodlibet_bus.IsPlaying()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/net/sacredchao/QuodLibet”
```
