### ISSUE TITLE
Album Art: Discogs parser overloads service

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2221]
When downloading album art, the Discogs engine sends a lot of requests, which, especially when no cover can be found, soon result in an exceptions thrown wrapping the `HTTP 429` from the server:

```E: 75.408: fake.plugins.albumart.__search_thread:
    Traceback (most recent call last):
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/ext/songsmenu/albumart.py", line 858, in __search_thread
        result = engine().start(clean_query, self.overall_limit)
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/ext/songsmenu/albumart.py", line 295, in start
        self.__parse_page(1, query)
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/ext/songsmenu/albumart.py", line 250, in __parse_page
        self.__parse_item(item)
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/ext/songsmenu/albumart.py", line 263, in __parse_item
        data = get_url(res_url, get=self.creds)
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/ext/songsmenu/albumart.py", line 79, in get_url
        url_sock = urlopen(request)
      File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.5/urllib/request.py", line 472, in open
        response = meth(req, response)
      File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.5/urllib/request.py", line 510, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```

**Comment by declension** [comment]
It can also takes a long time (10s+ here) to get this many results, during which time results are not rendered as each engine is single-threaded, so users often won't even see the results (Amazon results have long displayed by then).

**Comment by knockoutMice** [comment]
Thanks for the tweaks! 
Discogs has pretty serious rate-limiting and we can't really get past that.
