### ISSUE TITLE
Duplicate Browser doesn't start (no window)

### ISSUE THREAD

**Issue by spxxxk** [quodlibet/quodlibet#2244]
Output from `quodlibet --debug` shows
```
D: 36.032: Duplicates.plugin_songs: Calculating duplicates for 18 song(s)...
E: 36.033: qltk.songsmenu.__handle:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/songsmenu.py", line 218, in __handle
        ret = plugin.plugin_songs(songs)
      File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/duplicates.py", line 466, in plugin_songs
        key = self.get_key(song)
      File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/duplicates.py", line 450, in get_key
        key = (key.translate(cls.__trans, string.punctuation) if PY2
    TypeError: translate() takes exactly one argument (2 given)
D: 52.290: Duplicates.plugin_songs: Calculating duplicates for 18 song(s)...
E: 52.291: qltk.songsmenu.__handle:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/songsmenu.py", line 218, in __handle
        ret = plugin.plugin_songs(songs)
      File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/duplicates.py", line 466, in plugin_songs
        key = self.get_key(song)
      File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/duplicates.py", line 450, in get_key
        key = (key.translate(cls.__trans, string.punctuation) if PY2
    TypeError: translate() takes exactly one argument (2 given)

```

QL version : `3.8.99+8900~05c6d0e1b-0~ppa0~xenial`

**Comment by declension** [comment]
Thanks. Replicated (in Python2 only - a first perhaps... my fault though)
