### ISSUE TITLE
Opening song/context menu causes error. (Dump)

### ISSUE THREAD

**Issue by pschwede** [quodlibet/quodlibet#2245]
```
=== SYSTEM INFORMATION:
Quod Libet 3.9 (development, 05c6d0e1b)
Mutagen 1.37.-1
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] linux2
Platform Linux-4.8.0-38-generic-x86_64-with-Ubuntu-16.10-yakkety
=== STACK TRACE

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/info.py", line 86, in _on_label_popup
    song_menu = self._get_menu(player, library)

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/info.py", line 112, in _get_menu
    accels=False, items=[[item]])

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/songsmenu.py", line 301, in __init__
    submenu = self.plugins.Menu(librarian, songs)

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/songsmenu.py", line 127, in Menu
    % Kind)

  File "/usr/lib/python2.7/dist-packages/quodlibet/util/dprint.py", line 297, in print_e
    _print_message(string, context, False, "E", "red", "errors")

  File "/usr/lib/python2.7/dist-packages/quodlibet/util/dprint.py", line 220, in _print_message
    print_(string, file=file_, flush=True)

  File "/usr/lib/python2.7/dist-packages/quodlibet/senf/_print.py", line 59, in print_
    _print_unix(objects, sep, end, file, flush)

  File "/usr/lib/python2.7/dist-packages/quodlibet/senf/_print.py", line 103, in _print_unix
    file.write(data)

IOError: [Errno 5] Input/output error
```

Message me in private if you need details.

**Comment by lazka** [comment]
Should be fixed with 2fb97a9b241df, but I'm wondering how this can happen in your case, how do you start QL?

**Comment by pschwede** [comment]
Good point. I think it was `quodlibet --debug`

**Comment by lazka** [comment]
Ah, I see, it's the same thing, closing the terminal closes stderr and aborts QL's shutdown, so any following action leads to the same error.

Thanks.
