### ISSUE TITLE
Queue: Moving elements fails with PY3

### ISSUE THREAD

**Issue by ptitjes** [quodlibet/quodlibet#2268]
While moving elements inside the queue works correctly with python 2, it fails with python 3.

It produces the following error

```
Traceback (most recent call last):
  File "/home/didier/Code/external/quodlibet/quodlibet/quodlibet/qltk/songlist.py", line 329, in __drag_data_received
    model.move_before(self.__drag_iters.pop(0), iter)
AttributeError: 'map' object has no attribute 'pop'
```

or

```
Traceback (most recent call last):
  File "/home/didier/Code/external/quodlibet/quodlibet/quodlibet/qltk/songlist.py", line 332, in __drag_data_received
    model.move_after(self.__drag_iters.pop(), iter)
AttributeError: 'map' object has no attribute 'pop'
```

depending on whether you move the elements before or after themselves.

This boils down from the fact that 'map' results are not lists anymore.
Thus changing line 275 of file `songlist.py` from
```
self.__drag_iters = map(model.get_iter, paths)
```
to
```
self.__drag_iters = list(map(model.get_iter, paths))
```

I could do a PR but I am not sure it is the best fix.

**Comment by lazka** [comment]
the fix looks good

**Comment by ptitjes** [comment]
Here it is then.
