### ISSUE TITLE
driver.encode("utf-8") AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by edyatl** [quodlibet/quodlibet#2370]
**Gentoo** quodlibet-3.8.1-r1 does not start after recent update
```
 ~ $ quodlibet
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 14, in <module>
    sys.exit(main())
  File "/usr/lib64/python2.7/site-packages/quodlibet/main.py", line 69, in main
    player = quodlibet.player.init_player(backend, app.librarian)
  File "/usr/lib64/python2.7/site-packages/quodlibet/player/__init__.py", line 49, in init_player
    return backend.init(librarian)
  File "/usr/lib64/python2.7/site-packages/quodlibet/player/xinebe/player.py", line 341, in init
    return XinePlaylistPlayer(driver, librarian)
  File "/usr/lib64/python2.7/site-packages/quodlibet/player/xinebe/player.py", line 82, in __init__
    driver = driver.encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'
```
#quodlibet 
#Gentoo
#python2.7
#utf-8
#AttributeError

**Comment by lazka** [comment]
Oops, some fallout from python 3 porting. Thanks

Using the GStreamer backend would be a workaround..
