### ISSUE TITLE
Importing playlists raises AttrributeError

### ISSUE THREAD

**Issue by brenthuisman** [quodlibet/quodlibet#2421]
If I import a playlist (rather, a bunch of them) by dragging and dropping them over the playlist view (as per https://quodlibet.readthedocs.io/en/latest/guide/browse/playlists.html), I get an error, and nothing is imported:

`AttributeError: 'FileBackedPlaylist' object has no attribute 'startswith'`

I suppose strings were replaced with a FileBackedPlaylist class at some point.

**Comment by declension** [comment]
Thanks for the report. 

What kind of playlists were you drag-and-dropping? 

Also, can you post the full stack trace please.

**Comment by brenthuisman** [comment]
An m3u playlist.

`
AttributeError: 'FileBackedPlaylist' object has no attribute 'startswith'
------
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/playlists/main.py", line 404, in __drag_data_received
    library.add_filename(playlist)

  File "/usr/lib/python2.7/dist-packages/quodlibet/library/libraries.py", line 850, in add_filename
    key = normalize_path(filename, True)

  File "/usr/lib/python2.7/dist-packages/quodlibet/util/path.py", line 331, in _normalize_path
    filename = os.path.realpath(filename)

  File "/usr/lib/python2.7/posixpath.py", line 375, in realpath
    path, ok = _joinrealpath('', filename, {})

  File "/usr/lib/python2.7/posixpath.py", line 381, in _joinrealpath
    if isabs(rest):

  File "/usr/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')

AttributeError: 'FileBackedPlaylist' object has no attribute 'startswith'

`

**Comment by declension** [comment]
Replicated on f42bd9cd145856a620ee67f08449c3894cea6457.
