### ISSUE TITLE
PY3: import playlist throws TypeError

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2426]
Looks like the usual `filter` problems. Uncovered by tests...
```
Traceback (most recent call last):

  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/browsers/playlists/main.py", line 580, in __import
    playlist = parse_m3u(filename, library=library)

  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/browsers/playlists/util.py", line 70, in parse_m3u
    return __create_playlist(pl_name, filename, filenames, library)

  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/browsers/playlists/util.py", line 118, in __create_playlist
    playlist.extend(filter(None, songs))

  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/util/collection.py", line 347, in extend
    self._emit_changed(songs, msg="extend")

  File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/util/collection.py", line 483, in _emit_changed
    % (msg, len(songs), self))

TypeError: object of type 'filter' has no len()
```

**Comment by declension** [comment]
This is fixed now
