### ISSUE TITLE
PY3: Searching with ~lyrics raises AttributeError

### ISSUE THREAD

**Issue by declension** [quodlibet/quodlibet#2524]
### Steps
* Switch to Search Browser
* Have at least one working lyrics file in the library
* Enter `~lyrics=''` or similar

### Expected 
* Results with no lyrics set

### Actual
This error:
```
Traceback (most recent call last):
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/browsers/search.py", line 119, in __text_parse
        self.activate()
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/browsers/search.py", line 113, in activate
        songs = self._get_songs()
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/browsers/search.py", line 110, in _get_songs
        return self._query.filter(self._library)
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/query/_match.py", line 36, in filter
        return [s for s in sequence if self.search(s)]
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/query/_match.py", line 36, in <listcomp>
        return [s for s in sequence if self.search(s)]
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/query/_match.py", line 518, in search
        if search(data(name)):
      File "/home/nick/workspace/quodlibet/quodlibet/quodlibet/formats/_audio.py", line 454, in __call__
        return fileobj.read().decode("utf-8", "replace")
    AttributeError: 'str' object has no attribute 'decode'
```

**Comment by declension** [comment]
Interestingly [that line is not covered](https://codecov.io/gh/quodlibet/quodlibet/src/master/quodlibet/quodlibet/formats/_audio.py#L454) in testing...
