### ISSUE TITLE
Error by an attempt to edit empty field "ID3 encodings"

### ISSUE THREAD

**Issue by galexrry** [quodlibet/quodlibet#2527]
* What did you try to do when the error occurred?
Just installed a fresh copy of quodlibet and was exploring the menus of this application: 
- File, Plugins
- Selected "Advanced Preferences"
- clicked on the icon to the right of the (empty) field "ID3 encodings"

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/quodlibet/ext/events/advanced_preferences.py", line 32, in on_reverted
    config.reset(section, option)

  File "/usr/lib/python2.7/site-packages/quodlibet/util/config.py", line 126, in reset
    self._config.remove_option(section, option)

  File "/usr/lib64/python2.7/ConfigParser.py", line 424, in remove_option
    raise NoSectionError(section)

NoSectionError: No section: 'editing'


Version: 3.9.1
Python: 2.7.13 (default, May 10 2017, 20:04:28) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
Platform: Linux-4.11.12-200.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five
```

**Comment by lazka** [comment]
Thanks for the detailed report. This was recently fixed, see #2519
