### ISSUE TITLE
Python3 crash when closing app

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2587]
https://sentry.io/quodlibet/quodlibet/issues/369069300/

```
FaultHandlerCrash: Fatal Python error: Segmentation fault

Stack (most recent call first):
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/qltk/_editutils.py", line 207 in __refresh_plugins
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/qltk/_editutils.py", line 85 in changed
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/qltk/_editutils.py", line 82 in plugin_disable
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/plugins/__init__.py", line 344 in enable
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/plugins/__init__.py", line 392 in __remove_module
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/plugins/__init__.py", line 386 in quit
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/plugins/__init__.py", line 31 in quit
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/_main.py", line 299 in quit_gtk
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/qltk/quodlibetwindow.py", line 1064 in <lambda>
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/_main.py", line 350 in run
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/main.py", line 196 in main
  File "quodlibet/quodlibet.py", line 14 in <module>
  File "quodlibet/errorreport/faulthandling.py", line 137, in raise_and_clear_error
    raise FaultHandlerCrash(text)

FaultHandlerCrash: Fatal Python error: Segmentation fault

Stack (most recent call first):
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/qltk/_editutils.py", line 207 in __refresh_plugins
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/qltk/_editutils.py", line 85 in changed
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/qltk/_editutils.py", line 82 in plugin_disable
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/plugins/__init__.py", line 344 in enable
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/plugins/__init__.py", line 392 in __remove_module
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/plugins/__init__.py", line 386 in quit
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/plugins/__init__.py", line 31 in quit
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/_main.py", line 299 in quit_gtk
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/qltk/quodlibetwindow.py", line 1064 in <lambda>
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/_main.py", line 350 in run
  File "/home/lazka/Desktop/quodlibet/quodlibet/quodlibet/main.py", line 196 in main
  File "quodlibet/quodlibet.py", line 14 in <module>
```

**Comment by lazka** [comment]
* enable kakasi plugin
* edit tags
* click expand in rename files to show plugins
* close edit tags
* close app

-> crash
```
gtk_css_gadget_set_state (gadget=0x0, state=state@entry=GTK_STATE_FLAG_DIR_LTR)
    at ../../../../gtk/gtkcssgadget.c:413
413	../../../../gtk/gtkcssgadget.c: No such file or directory.
(gdb) bt
#0  0x00007fffebd98e37 in gtk_css_gadget_set_state (gadget=0x0, state=state@entry=GTK_STATE_FLAG_DIR_LTR)
    at ../../../../gtk/gtkcssgadget.c:413
#1  0x00007fffebdddda9 in update_node_state (expander=expander@entry=0x2e10d30 [GtkExpander])
    at ../../../../gtk/gtkexpander.c:758
#2  0x00007fffebdde727 in gtk_expander_set_expanded (expander=0x2e10d30 [GtkExpander], expanded=0)
    at ../../../../gtk/gtkexpander.c:1286
```
