### ISSUE TITLE
[Error] ValueError: could not convert string to float:

### ISSUE THREAD

**Issue by rohshall** [quodlibet/quodlibet#2637]
* What did you try to do when the error occurred?

I was adding this podcast URL: http://abcnews.go.com/xmldata/xmlPodcast?id=868748&src=i

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/quodlibet/browsers/audiofeeds.py", line 507, in __new_feed
    feed.changed = feed.parse()

  File "/usr/lib/python2.7/site-packages/quodlibet/browsers/audiofeeds.py", line 181, in parse
    size = float(enclosure.length)

ValueError: could not convert string to float: 


Version: 3.9.1
Python: 2.7.14 (default, Nov  2 2017, 19:02:24) 
[GCC 7.2.1 20170829 (Red Hat 7.2.1-1)]
Platform: Linux-4.15.0-0.rc0.git7.1.fc28.x86_64-x86_64-with-fedora-28-Rawhide
```

**Comment by lazka** [comment]
Thanks
