### ISSUE TITLE
bug when testing enqueue-files

### ISSUE THREAD

**Issue by pfps** [quodlibet/quodlibet#2657]
I did 

 quodlibet --debug --enqueue-files foo\\,bar.ogg 

and the running quodlibet got into a sequence of error and had to be restarted.   This is in the development version (and I had done a tiny fix to --enqueue).    

W: 42.713: formats._misc.MusicFile: Error loading '/home/local/music/Albums/The Beatles/Please Please Me/foo\\,bar.ogg'
E: 42.718: formats._misc.MusicFile:
    Traceback (most recent call last):
      File "/home/pfps/.local/lib/python3.6/site-packages/mutagen/_util.py", line 231, in _openfile
        fileobj = open(filename, "rb+" if writable else "rb")
    FileNotFoundError: [Errno 2] No such file or directory: '/home/local/music/Albums/The Beatles/Please Please Me/foo\\,bar.ogg'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/formats/_misc.py", line 46, in translate_errors
        yield
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/formats/xiph.py", line 487, in loader
        audio = mutagen.File(filename, options=ogg_formats)
      File "/home/pfps/.local/lib/python3.6/site-packages/mutagen/_util.py", line 147, in wrapper_func
        writable, create) as h:
      File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/pfps/.local/lib/python3.6/site-packages/mutagen/_util.py", line 252, in _openfile
        raise MutagenError(e)
    mutagen.MutagenError: [Errno 2] No such file or directory: '/home/local/music/Albums/The Beatles/Please Please Me/foo\\,bar.ogg'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/formats/_misc.py", line 118, in MusicFile
        return loader(filename)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/formats/xiph.py", line 500, in loader
        raise AudioFileError("file type could not be determined")
      File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/formats/_misc.py", line 50, in translate_errors
        reraise(AudioFileError, e)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/util/__init__.py", line 1160, in reraise
        py_reraise(tp, value, tb)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/compat.py", line 138, in reraise
        raise tp(value).with_traceback(tb)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/formats/_misc.py", line 46, in translate_errors
        yield
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/formats/xiph.py", line 487, in loader
        audio = mutagen.File(filename, options=ogg_formats)
      File "/home/pfps/.local/lib/python3.6/site-packages/mutagen/_util.py", line 147, in wrapper_func
        writable, create) as h:
      File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/home/pfps/.local/lib/python3.6/site-packages/mutagen/_util.py", line 252, in _openfile
        raise MutagenError(e)
    quodlibet.formats._misc.AudioFileError: [Errno 2] No such file or directory: '/home/local/music/Albums/The Beatles/Please Please Me/foo\\,bar.ogg'
E: 42.719: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/util/__init__.py", line 706, in _wrap
        self.func(*self.args)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/queue.py", line 250, in __check_expand
        self.__update_count(model, path, lab)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/queue.py", line 242, in __update_count
        time = sum([row[0].get("~#length", 0) for row in model])
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/queue.py", line 242, in <listcomp>
        time = sum([row[0].get("~#length", 0) for row in model])
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.327: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 385, in _fetch_value
        return model.get_value(iter_).comma(self.header_name)
    AttributeError: 'NoneType' object has no attribute 'comma'
E: 43.327: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 454, in _fetch_value
        return model.get_value(iter_).get("~#length", 0)
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.328: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 350, in _fetch_value
        return self._pattern % song
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 247, in format
        value = u"".join(self.__func(self.SongProxy(song, self._format)))
      File "<string>", line 5, in f
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 224, in comma
        value = self.__song.comma(key)
    AttributeError: 'NoneType' object has no attribute 'comma'
E: 43.328: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 350, in _fetch_value
        return self._pattern % song
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 247, in format
        value = u"".join(self.__func(self.SongProxy(song, self._format)))
      File "<string>", line 5, in f
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 224, in comma
        value = self.__song.comma(key)
    AttributeError: 'NoneType' object has no attribute 'comma'
E: 43.328: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 311, in _fetch_value
        return model.get_value(iter_).get(self.header_name, "")
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.329: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 311, in _fetch_value
        return model.get_value(iter_).get(self.header_name, "")
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.329: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 311, in _fetch_value
        return model.get_value(iter_).get(self.header_name, "")
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.329: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 350, in _fetch_value
        return self._pattern % song
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 247, in format
        value = u"".join(self.__func(self.SongProxy(song, self._format)))
      File "<string>", line 5, in f
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 224, in comma
        value = self.__song.comma(key)
    AttributeError: 'NoneType' object has no attribute 'comma'
E: 43.329: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 311, in _fetch_value
        return model.get_value(iter_).get(self.header_name, "")
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.329: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 311, in _fetch_value
        return model.get_value(iter_).get(self.header_name, "")
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.330: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 262, in _fetch_value
        return model.get_value(iter_).comma(self.header_name)
    AttributeError: 'NoneType' object has no attribute 'comma'
E: 43.330: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 385, in _fetch_value
        return model.get_value(iter_).comma(self.header_name)
    AttributeError: 'NoneType' object has no attribute 'comma'
E: 43.331: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 454, in _fetch_value
        return model.get_value(iter_).get("~#length", 0)
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.332: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 350, in _fetch_value
        return self._pattern % song
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 247, in format
        value = u"".join(self.__func(self.SongProxy(song, self._format)))
      File "<string>", line 5, in f
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 224, in comma
        value = self.__song.comma(key)
    AttributeError: 'NoneType' object has no attribute 'comma'
E: 43.332: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 350, in _fetch_value
        return self._pattern % song
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 247, in format
        value = u"".join(self.__func(self.SongProxy(song, self._format)))
      File "<string>", line 5, in f
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 224, in comma
        value = self.__song.comma(key)
    AttributeError: 'NoneType' object has no attribute 'comma'
E: 43.333: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 311, in _fetch_value
        return model.get_value(iter_).get(self.header_name, "")
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.333: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 311, in _fetch_value
        return model.get_value(iter_).get(self.header_name, "")
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.334: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 311, in _fetch_value
        return model.get_value(iter_).get(self.header_name, "")
    AttributeError: 'NoneType' object has no attribute 'get'
E: 43.334: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 350, in _fetch_value
        return self._pattern % song
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 247, in format
        value = u"".join(self.__func(self.SongProxy(song, self._format)))
      File "<string>", line 5, in f
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/pattern/_pattern.py", line 224, in comma
        value = self.__song.comma(key)
    AttributeError: 'NoneType' object has no attribute 'comma'
E: 43.335: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 205, in _cdf
        value = self._fetch_value(model, iter_)
      File "/home/local/SoftwareDownloads/quodlibet-fork/quodlibet/quodlibet/qltk/songlistcolumns.py", line 311, in _fetch_value
        return model.get_value(iter_).get(self.header_name, "")
    AttributeError: 'NoneType' object has no attribute 'get'
D: 37.805: player.gstbe.player.__about_to_finish: About to finish (async)
D: 37.806: player.gstbe.player.__about_to_finish_sync: About to finish (sync)
D: 37.807: player.gstbe.player.__about_to_finish_sync: Select next song in mainloop..
D: 37.807: QueueModel.next_ended: Using <In Order>.next_implicit() to get next song
D: 37.808: player.gstbe.player.__about_to_finish_sync: ..done.
D: 37.808: player.gstbe.player.__about_to_finish: About to finish (async):

**Comment by pfps** [comment]
I think a one-line fix fixes this.  It will be included in my fixes for --queue.

**Comment by pfps** [comment]
Fixed in recent pull.
