### ISSUE TITLE
[Error] OverflowError: long too big to convert

### ISSUE THREAD

**Issue by zdzichu** [quodlibet/quodlibet#2698]
* What did you try to do when the error occurred?
listening musinc

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/quodlibet/ext/events/mpris/mpris2.py", line 151, in __library_changed
    self.emit_properties_changed(self.PLAYER_IFACE, ["Metadata"])

  File "/usr/lib/python2.7/site-packages/quodlibet/util/dbusutils.py", line 307, in emit_properties_changed
    self.PropertiesChanged(iface, values, inval)

  File "/usr/lib64/python2.7/site-packages/dbus/decorators.py", line 323, in emit_signal
    message.append(signature=signature, *args)

OverflowError: long too big to convert


Version: 3.9.1
Python: 2.7.14 (default, Dec 11 2017, 14:52:53) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
Platform: Linux-4.14.8-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
```

**Comment by zdzichu** [comment]
That was quick… thanks! :)
