### ISSUE TITLE
adding new radio stations with PLS links is broken

### ISSUE THREAD

**Issue by deutrino** [quodlibet/quodlibet#2709]
Steps to reproduce:

1. Open radio browser.
2. Select New Station.
3. Paste a URL to a .pls playlist (e.g. https://somafm.com/bagel.pls) and click OK.

```
TypeError: a bytes-like object is required, not 'str'
------
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/quodlibet/browsers/iradio.py", line 800, in __add
    self.__add_station(uri)

  File "/usr/lib/python3/dist-packages/quodlibet/browsers/iradio.py", line 803, in __add_station
    irfs = add_station(uri)

  File "/usr/lib/python3/dist-packages/quodlibet/browsers/iradio.py", line 224, in add_station
    irfs = ParsePLS(sock)

  File "/usr/lib/python3/dist-packages/quodlibet/browsers/iradio.py", line 138, in ParsePLS
    if not lines or "[playlist]" not in lines.pop(0):

TypeError: a bytes-like object is required, not 'str'
```

**Comment by lazka** [comment]
Thanks, should be fixed in master: 83fb5e5a1df
