### ISSUE TITLE
Hang in WaveformSeekBar._clean_pipeline

### ISSUE THREAD

**Issue by Bob131** [quodlibet/quodlibet#2730]
Occasionally whilst skipping through songs, QuodLibet will lock up: the UI becomes unresponsive, the UI display becomes stuck on-screen, it doesn't respond to media keys, DBus messages time out etc. No song seems to trigger it reproducibly, and I haven't noticed any pattern to the occurrences (it just seems to happen after some indeterminate period of time, ranging from an hour to days).

I've got a backtrace from a coredump I got via `kill -SIGTRAP`:

```
#0  0x00007f061d7af3bd in __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f061d7a81d8 in __GI___pthread_mutex_lock (mutex=0x562c2cfb4b00) at ../nptl/pthread_mutex_lock.c:115
#2  0x00007f05ffd48ea4 in gst_pad_stop_task (pad=0x7f05a80b41f0 [GstPad]) at gstpad.c:6209
#3  0x00007f05de4b36fd in gst_type_find_element_activate_sink_mode (pad=<optimized out>, parent=0x562c2c803d20 [GstTypeFindElement], mode=<optimized out>, active=<optimized out>) at gsttypefindelement.c:1258
#4  0x00007f05ffd42415 in activate_mode_internal (pad=pad@entry=0x7f05a80b41f0 [GstPad], parent=parent@entry=0x562c2c803d20 [GstTypeFindElement], mode=mode@entry=GST_PAD_MODE_PULL, active=active@entry=0) at gstpad.c:1216
#5  0x00007f05ffd42ee5 in gst_pad_set_active (pad=pad@entry=0x7f05a80b41f0 [GstPad], active=0) at gstpad.c:1114
#6  0x00007f05ffd219bd in activate_pads (vpad=<optimized out>, ret=0x7ffddff6fa00, active=0x7ffddff6fa5c) at gstelement.c:2831
#7  0x00007f05ffd33774 in gst_iterator_fold (it=it@entry=0x562c2beed280, func=func@entry=0x7f05ffd219a0 <activate_pads>, ret=ret@entry=0x7ffddff6fa00, user_data=user_data@entry=0x7ffddff6fa5c) at gstiterator.c:617
#8  0x00007f05ffd224c6 in iterator_activate_fold_with_resync (iter=iter@entry=0x562c2beed280, user_data=user_data@entry=0x7ffddff6fa5c, func=0x7f05ffd219a0 <activate_pads>) at gstelement.c:2855
#9  0x00007f05ffd241ee in gst_element_pads_activate (element=element@entry=0x562c2c803d20 [GstTypeFindElement], active=<optimized out>, active@entry=0) at gstelement.c:2899
#10 0x00007f05ffd24496 in gst_element_change_state_func (element=0x562c2c803d20 [GstTypeFindElement], transition=<optimized out>) at gstelement.c:2965
#11 0x00007f05de4b3866 in gst_type_find_element_change_state (element=0x562c2c803d20 [GstTypeFindElement], transition=GST_STATE_CHANGE_PAUSED_TO_READY) at gsttypefindelement.c:1323
#12 0x00007f05ffd263ae in gst_element_change_state (element=element@entry=0x562c2c803d20 [GstTypeFindElement], transition=transition@entry=GST_STATE_CHANGE_PAUSED_TO_READY) at gstelement.c:2743
#13 0x00007f05ffd26ae9 in gst_element_set_state_func (element=0x562c2c803d20 [GstTypeFindElement], state=GST_STATE_READY) at gstelement.c:2697
#14 0x00007f05ffd04c22 in gst_bin_element_set_state (next=GST_STATE_READY, current=GST_STATE_PAUSED, start_time=0, base_time=0, element=0x562c2c803d20 [GstTypeFindElement], bin=0x562c2cbd7cd0 [GstDecodeBin]) at gstbin.c:2595
#15 0x00007f05ffd04c22 in gst_bin_change_state_func (element=0x562c2cbd7cd0 [GstDecodeBin], transition=GST_STATE_CHANGE_PAUSED_TO_READY) at gstbin.c:2937
#16 0x00007f05de6e2809 in gst_decode_bin_change_state (element=0x562c2cbd7cd0 [GstDecodeBin], transition=GST_STATE_CHANGE_PAUSED_TO_READY) at gstdecodebin2.c:5342
#17 0x00007f05ffd263ae in gst_element_change_state (element=element@entry=0x562c2cbd7cd0 [GstDecodeBin], transition=transition@entry=GST_STATE_CHANGE_PAUSED_TO_READY) at gstelement.c:2743
#18 0x00007f05ffd26ae9 in gst_element_set_state_func (element=0x562c2cbd7cd0 [GstDecodeBin], state=GST_STATE_READY) at gstelement.c:2697
#19 0x00007f05ffd04c22 in gst_bin_element_set_state (next=GST_STATE_READY, current=GST_STATE_PAUSED, start_time=0, base_time=0, element=0x562c2cbd7cd0 [GstDecodeBin], bin=0x7f05e4059440 [GstPipeline]) at gstbin.c:2595
#20 0x00007f05ffd04c22 in gst_bin_change_state_func (element=0x7f05e4059440 [GstPipeline], transition=GST_STATE_CHANGE_PAUSED_TO_READY) at gstbin.c:2937
#21 0x00007f05ffd263ae in gst_element_change_state (element=element@entry=0x7f05e4059440 [GstPipeline], transition=transition@entry=GST_STATE_CHANGE_PAUSED_TO_READY) at gstelement.c:2743
#22 0x00007f05ffd26ae9 in gst_element_set_state_func (element=0x7f05e4059440 [GstPipeline], state=GST_STATE_NULL) at gstelement.c:2697
#23 0x00007f061284cd1e in ffi_call_unix64 () at ../src/x86/unix64.S:76
#24 0x00007f061284c68f in ffi_call (cif=cif@entry=0x562c2cbc6f78, fn=<optimized out>, rvalue=<optimized out>, rvalue@entry=0x7ffddff70028, avalue=<optimized out>) at ../src/x86/ffi64.c:525
#25 0x00007f0611ba6dda in pygi_invoke_c_callable (function_cache=0x562c2cbc6ed0, state=<optimized out>, py_args=<optimized out>, py_kwargs=<optimized out>) at pygi-invoke.c:682
#26 0x00007f0611ba89b8 in pygi_function_cache_invoke (function_cache=<optimized out>, py_args=py_args@entry=(<Pipeline at remote 0x7f05b0327870>, <State at remote 0x7f05dee93fc0>), py_kwargs=<optimized out>) at pygi-cache.c:863
#27 0x00007f0611ba7648 in pygi_callable_info_invoke (info=<optimized out>, py_args=py_args@entry=(<Pipeline at remote 0x7f05b0327870>, <State at remote 0x7f05dee93fc0>), kwargs=<optimized out>, cache=<optimized out>, user_data=user_data@entry=0x0) at pygi-invoke.c:725
#28 0x00007f0611ba767f in _wrap_g_callable_info_invoke (self=<optimized out>, py_args=py_args@entry=(<Pipeline at remote 0x7f05b0327870>, <State at remote 0x7f05dee93fc0>), kwargs=<optimized out>) at pygi-invoke.c:762
#29 0x00007f0611b9cc29 in _callable_info_call (self=0x7f05deff3f80, args=(<State at remote 0x7f05dee93fc0>,), kwargs=0x0) at pygi-info.c:561
#30 0x00007f061dadb204 in _PyObject_FastCallDict (func=<gi.FunctionInfo at remote 0x7f05deff3f80>, args=0x7f0613bbe3d8, nargs=<optimized out>, kwargs=0x0) at /usr/src/debug/python3-3.6.3-2.fc27.x86_64/Objects/abstract.c:2331
#31 0x00007f061db4a3ad in call_function (pp_stack=0x7ffddff70268, oparg=<optimized out>, kwnames=0x0) at /usr/src/debug/python3-3.6.3-2.fc27.x86_64/Python/ceval.c:4848
#32 0x00007f061db73eca in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.6.3-2.fc27.x86_64/Python/ceval.c:3322
#33 0x00007f061db0cbea in _PyFunction_FastCall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /usr/src/debug/python3-3.6.3-2.fc27.x86_64/Python/ceval.c:4906
#34 0x00007f061db0cbea in fast_function (func=<optimized out>, stack=0x562c2b3aa870, nargs=1, kwnames=<optimized out>) at /usr/src/debug/python3-3.6.3-2.fc27.x86_64/Python/ceval.c:4941
#35 0x00007f061db4a33e in call_function (pp_stack=0x7ffddff70418, oparg=<optimized out>, kwnames=0x0) at /usr/src/debug/python3-3.6.3-2.fc27.x86_64/Python/ceval.c:4845
#36 0x00007f061db73eca in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /usr/src/debug/python3-3.6.3-2.fc27.x86_64/Python/ceval.c:3322

   <...snip...>

(gdb) f 36
#36 0x00007f061db73eca in _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.3-2.fc27.x86_64/Python/ceval.c:3322
3322	            res = call_function(&sp, oparg, NULL);
(gdb) py-bt
Traceback (most recent call first):
  (frame information optimized out)
  File "/usr/lib/python3.6/site-packages/quodlibet/ext/events/waveformseekbar.py", line 176, in _on_song_changed
    self._create_waveform(player.info, CONFIG.max_data_points)
  <built-in method emit of SongLibrarian object at remote 0x7f05ff678d80>
  File "/usr/lib/python3.6/site-packages/quodlibet/library/librarians.py", line 76, in __changed
    self.emit('changed', items)
  <built-in method emit of SongFileLibrary object at remote 0x7f05ff678cf0>
  (frame information optimized out)
  File "/usr/lib/python3.6/site-packages/quodlibet/library/librarians.py", line 90, in changed
    library._changed(in_library)
  (frame information optimized out)
  File "/usr/lib/python3.6/site-packages/quodlibet/_main.py", line 351, in run
    Gtk.main()
  File "/usr/lib/python3.6/site-packages/quodlibet/main.py", line 197, in main
    quodlibet.run(window, before_quit=before_quit)
  (frame information optimized out)
(gdb) p tstate->frame->f_code->co_filename
$93 = '/usr/lib/python3.6/site-packages/quodlibet/ext/events/waveformseekbar.py'
(gdb) p sp[0]->ob_type->tp_name
$101 = 0x7f05fd183a60 "WaveformSeekBar"
(gdb) p tstate->frame->f_code->co_name
$92 = '_clean_pipeline'
```

Some info about my system:

```
fedora-release-27-1.noarch
gstreamer1-1.12.4-1.fc27.x86_64
gstreamer1-plugins-good-1.12.4-1.fc27.x86_64
python3-3.6.3-2.fc27.x86_64
quodlibet-4.0.0-2.fc27.noarch
```

**Comment by lazka** [comment]
Thanks, probably #2714

**Comment by lazka** [comment]
#gstreamer says that the next bugfix release will be out in 1-2 weeks.

Otherwise downgrading "gstreamer1" to 1.12.3 should helps as well.

**Comment by Bob131** [comment]
Okay, thanks! Sorry for the dup
