### ISSUE TITLE
ValueError raised for some radio URLs lacking protocol

### ISSUE THREAD

**Issue by am4c130d** [quodlibet/quodlibet#2731]
* What did you try to do when the error occurred?

Add a pls from Dandelion radio.

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/iradio.py", line 793, in __add
    self.__add_station(uri)

  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/iradio.py", line 796, in __add_station
    irfs = add_station(uri)

  File "/usr/lib/python2.7/dist-packages/quodlibet/browsers/iradio.py", line 215, in add_station
    sock = urlopen(uri)

  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)

  File "/usr/lib/python2.7/urllib2.py", line 421, in open
    protocol = req.get_type()

  File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
    raise ValueError, "unknown url type: %s" % self.__original

ValueError: unknown url type: www.dandelion.com/dandelion.pls


Version: 3.9.1
Python: 2.7.14+ (default, Dec  5 2017, 15:17:02) 
[GCC 7.2.0]
Platform: Linux-4.14.0-2-amd64-x86_64-with-debian-buster-sid
```

**Comment by declension** [comment]
@am4c130d could you provide a working URL with a playlist on that servers please?
