### ISSUE TITLE
Cover grid & Album list browsers error

### ISSUE THREAD

**Issue by brunob** [quodlibet/quodlibet#2836]
Tested on QL 4.1 from https://launchpad.net/~lazka/+archive/ubuntu/dumpingplace on ubuntu 18.04 (and 17.10 too) i get this error on startup with the two cover borwsers : 

```log
error: bad character range {-. at position 22
------
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/quodlibet/util/__init__.py", line 711, in wrap
    return handler(that, *args)

  File "/usr/lib/python3/dist-packages/quodlibet/browsers/albums/main.py", line 313, in __update_visibility
    for i in self.__scan_paths():

  File "/usr/lib/python3/dist-packages/quodlibet/browsers/albums/main.py", line 325, in __scan_paths
    self._update_row(model, iter_)

  File "/usr/lib/python3/dist-packages/quodlibet/browsers/albums/main.py", line 599, in _update_row
    cancel=self._cover_cancel)

  File "/usr/lib/python3/dist-packages/quodlibet/browsers/albums/models.py", line 44, in scan_cover
    self.album.songs, s, s, cancel, set_cover_cb)

  File "/usr/lib/python3/dist-packages/quodlibet/util/cover/manager.py", line 216, in get_pixbuf_many_async
    fileobj = self.get_cover_many(songs)

  File "/usr/lib/python3/dist-packages/quodlibet/util/cover/manager.py", line 189, in get_cover_many
    return self.acquire_cover_sync_many(songs)

  File "/usr/lib/python3/dist-packages/quodlibet/util/cover/manager.py", line 169, in acquire_cover_sync_many
    cover = plugin(song).cover

  File "/usr/lib/python3/dist-packages/quodlibet/util/cover/built_in.py", line 99, in cover
    for path in glob.glob(path):

  File "/usr/lib/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))

  File "/usr/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:

  File "/usr/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:

  File "/usr/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:

  [Previous line repeated 3 more times]

  File "/usr/lib/python3.6/glob.py", line 72, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):

  File "/usr/lib/python3.6/glob.py", line 83, in _glob1
    return fnmatch.filter(names, pattern)

  File "/usr/lib/python3.6/fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)

  File "/usr/lib/python3.6/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match

  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)

  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)

  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)

  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))

  File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)

  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))

  File "/usr/lib/python3.6/sre_parse.py", line 553, in _parse
    raise source.error(msg, len(this) + 1 + len(that))

sre_constants.error: bad character range {-. at position 22

```

**Comment by brunob** [comment]
It may be related to this commit 25a37c917ef240723646773c679b1d6db8a4c28d

**Comment by lazka** [comment]
What's the value of "fixed image filename" under preferences>browsers>albumart?

**Comment by brunob** [comment]
simply `cover.jpg`

**Comment by brunob** [comment]
And it works well if i untick the checkbox for this option.

**Comment by lazka** [comment]
Thanks, reproduced: https://sentry.io/share/issue/be3b3a92ab8d46fd9563da68223ddd8b/

**Comment by KoO-303** [comment]
Cover Grid is a great addition to the player. Looks Sweet

**Comment by brunob** [comment]
Thx @frestr :)
