### ISSUE TITLE
[Error] TypeError: long() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by xtetox** [quodlibet/quodlibet#2908]
* What did you try to do when the error occurred?

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/events/notify.py", line 235, in on_preview_button_clicked
    if not self.plugin_instance.show_notification(app.player.info):

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/events/notify.py", line 430, in show_notification
    get_conf_int("timeout"))

  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)

  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)

TypeError: long() argument must be a string or a number, not 'NoneType'


Version: 3.9.1
Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]
Platform: Linux-4.17.5-041705-generic-x86_64-with-Ubuntu-18.04-bionic
```

**Comment by frestr** [comment]
Does the problem still occur with a newer (>=4.0.0) QL version? This may perhaps have been fixed in 5a8ef7f7d2d2e230358ad3684218fbc83b951bea.
