### ISSUE TITLE
4.1.0 won't run on Windows 10

### ISSUE THREAD

**Issue by tomscytale** [quodlibet/quodlibet#2910]
Windows 10 x86_64

3.9.0 was running fine

downloaded and installed 4.1.0 - now quodlibet.exe won't run - nothing happens at all, even from the command line. 

I tried `quodlibet-cmd.exe`:
```
c:\Program Files (x86)\Quod Libet\bin>quodlibet-cmd.exe --debug
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Quod Libet\lib\python3.6\site-packages\quodlibet\main.py", line 17, in <module>
    from quodlibet.cli import process_arguments, exit_
  File "C:\Program Files (x86)\Quod Libet\lib\python3.6\site-packages\quodlibet\cli.py", line 15, in <module>
    from quodlibet.remote import Remote, RemoteError
  File "C:\Program Files (x86)\Quod Libet\lib\python3.6\site-packages\quodlibet\remote.py", line 13, in <module>
    from quodlibet.util import fifo, print_w
  File "C:\Program Files (x86)\Quod Libet\lib\python3.6\site-packages\quodlibet\util\fifo.py", line 23, in <module>
    from gi.repository import GLib
  File "__init__.py", line 42, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
```

I then installed 4.0.2 - it runs ok. The first time I ran it reported an internal error which I submitted via the GUI.

**Comment by lazka** [comment]
I can't reproduce on Windows Sever 2016 at least. I don't have a win 10 around atm.

**Comment by tomscytale** [comment]
I'm a python developer, but Windows is a strange land to me. Any pointers on how to start debugging this?

**Comment by lazka** [comment]
not sure. maybe you have Python installed and in PATH and that results in a conflict?

**Comment by tomscytale** [comment]
Yep, python is installed and `PATH` looks like 
```
C:\Users\hp142>echo %PATH% | tr ";" "\n"
C:\ProgramData\Oracle\Java\javapath
C:\Python27\
C:\Python27\Scripts
...
```

However quodlibet 4.0.2 works fine when run under the same environment and that runs python 3.5. Has something changed in `PATH` handling or whatever between quodlibet 4.0.2 and 4.1.0? 

I've also tried (via GIT BASH command line) reducing `$PATH` to something reasonable and trying again:

```bash
/c/Program Files (x86)/Quod Libet/bin $ export PATH=/c/Users/hp142/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/WINDOWS/system32:/c/WINDOWS

/c/Program Files (x86)/Quod Libet/bin $ ./quodlibet-cmd.exe
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Quod Libet\lib\python3.6\site-packages\quodlibet\main.py", line 17, in <module>
    from quodlibet.cli import process_arguments, exit_
  File "C:\Program Files (x86)\Quod Libet\lib\python3.6\site-packages\quodlibet\cli.py", line 15, in <module>
    from quodlibet.remote import Remote, RemoteError
  File "C:\Program Files (x86)\Quod Libet\lib\python3.6\site-packages\quodlibet\remote.py", line 13, in <module>
    from quodlibet.util import fifo, print_w
  File "C:\Program Files (x86)\Quod Libet\lib\python3.6\site-packages\quodlibet\util\fifo.py", line 23, in <module>
    from gi.repository import GLib
  File "__init__.py", line 42, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
```

Some Googling lead me to this [GH bug](https://github.com/python-pillow/Pillow/issues/2479#issuecomment-292252147) and a comment that said
```
The difference is that Pillow 4.1.0 was built with Python 3.6.1 while Pillow 4.0.0 was built with Python 3.6.0.

Apparently PYTHON36.DLL from Python 3.6.0 is missing functions (PySlice_AdjustIndices and PySlice_Unpack) that are used when building with Python 3.6.1.

The solution is to upgrade to Python 3.6.1.
```

Is there a difference in python minor version number between what is used to build quodlibet and what is used to build GLib?

**Comment by lazka** [comment]
```
export PATH=/c/Users/hp142/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/WINDOWS/system32:/c/WINDOWS
```

there is MSYS2 still in there, which moved to Python3.7 in the mean time.

Can you try:

```
export PATH=/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem
```

which should be the minimal Windows default

**Comment by tomscytale** [comment]
```bash
/c/Program Files (x86)/Quod Libet/bin $ echo $PATH
/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem

/c/Program Files (x86)/Quod Libet/bin $ ./quodlibet-cmd.exe --debug
Traceback (most recent call last):
...
    from gi.repository import GLib
  File "__init__.py", line 42, in <module>
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by lazka** [comment]
> Should there be a file /c/msys64/mingw32/lib/python3.7/site-packages/gi/_gi.py ? Is there something up with the gobject install? If this file is supposed to be there it presumably should come with mingw-w64-i686-python3-gobject

It's _gi-cpython-37m.dll, see http://quodlibet.duckdns.org/msys2/package/mingw-w64-i686-python3-gobject?repo=mingw32

> It also seems that bootstrap.sh is just installing the latest versions of all dependencies - how do I know if what I'm getting is compatible with what current master actually requires?

We run our test suite with all the latest versions on each commit, so theoretically this shouldn't be a problem: https://github.com/quodlibet/quodlibet/blob/master/.appveyor/msys2.sh

**Comment by The4thLaw** [comment]
Sorry if this doesn't bring a lot of information but 4.1.0 runs fine on my Windows 10 x86-64. So, at least, it's not a universal issue.

I ran it from the shortcut and from Cygwin. I don't have MinGW or a separate Python installation.

**Comment by lazka** [comment]
@The4thLaw thanks!

The best next step here is to force the DLL lookup to rule out any name clashes with DLLs in system directories. There was a related discussion with examples in https://github.com/gpodder/gpodder/issues/478 recently.

**Comment by lazka** [comment]
Thanks for the update!
