### ISSUE TITLE
[Error] TypeError: Argument 0 does not allow None as a value

### ISSUE THREAD

**Issue by cosscara** [quodlibet/quodlibet#2938]
* What did you try to do when the error occurred?

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/albumart.py", line 501, in __scale_pixbuf
    surface = get_surface_for_pixbuf(self, pixbuf)

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/image.py", line 21, in get_surface_for_pixbuf
    pixbuf, scale_factor, widget.get_window())

TypeError: Argument 0 does not allow None as a value


Version: 3.9.1
Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]
Platform: Linux-4.15.0-30-generic-x86_64-with-LinuxMint-19-tara
```

**Comment by lazka** [comment]
Do you know how to trigger the issue?

**Comment by CreamyCookie** [comment]
Closing this as not enough information.
