### ISSUE TITLE
[Error] FaultHandlerCrash: Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by cosscara** [quodlibet/quodlibet#2939]
* What did you try to do when the error occurred?

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/errorreport/faulthandling.py", line 137, in raise_and_clear_error
    raise FaultHandlerCrash(text)

FaultHandlerCrash: Fatal Python error: Segmentation fault

Stack (most recent call first):
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1927 in parseString
  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/albumart.py", line 133 in __parse_page
  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/albumart.py", line 205 in start
  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/albumart.py", line 856 in __search_thread
  File "/usr/lib/python2.7/threading.py", line 754 in run
  File "/usr/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 774 in __bootstrap


Version: 3.9.1
Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]
Platform: Linux-4.15.0-32-generic-x86_64-with-LinuxMint-19-tara
```

**Comment by lazka** [comment]
Same as #2940
