### ISSUE TITLE
[Error] FaultHandlerCrash: Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by cosscara** [quodlibet/quodlibet#2940]
* What did you try to do when the error occurred?

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/errorreport/faulthandling.py", line 137, in raise_and_clear_error
    raise FaultHandlerCrash(text)

FaultHandlerCrash: Fatal Python error: Segmentation fault

Stack (most recent call first):
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 769 in start_element_handler
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 354 in first_element_handler
  File "/build/python2.7-nbjU53/python2.7-2.7.15~rc1/Modules/pyexpat.c", line 566 in StartElement
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223 in parseString
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940 in parseString
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928 in parseString
  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/albumart.py", line 133 in __parse_page
  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/albumart.py", line 205 in start
  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/songsmenu/albumart.py", line 856 in __search_thread
  File "/usr/lib/python2.7/threading.py", line 754 in run
  File "/usr/lib/python2.7/threading.py", line 801 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 774 in __bootstrap


Version: 3.9.1
Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]
Platform: Linux-4.15.0-32-generic-x86_64-with-LinuxMint-19-tara
```

**Comment by lazka** [comment]
Thanks.

* We switched to Python 3 with version 4.0, so in case this is a Python problem it might be fixed there
* I can't seem to find a similar report in our online crash report database
* 3.9.1 is quite old

Based on the above points I'm closing this.

Feel free to post here if you can reproduce the error with a current version of QL.
