### ISSUE TITLE
Plugin "Set Exact Rating" cannot be used on multiple songs at once

### ISSUE THREAD

**Issue by Phidica** [quodlibet/quodlibet#3022]
When selecting two or more songs in any browser (I've tried Playlists and Cover Grid specifically), choosing Plugins > Set Exact Rating... in the context menu, and entering any valid value, I receive the following error:
```
TypeError: __init__() missing 1 required positional argument: 'value'
------
Traceback (most recent call last):

  File "/home/phidica/Code/quodlibet/quodlibet/quodlibet/qltk/songsmenu.py", line 205, in __handle
    ret = plugin.plugin_songs(songs)

  File "/home/phidica/Code/quodlibet/quodlibet/quodlibet/ext/songsmenu/exact_rating.py", line 55, in plugin_songs
    self.plugin_window, count, value)

TypeError: __init__() missing 1 required positional argument: 'value'
```
The rating does not seem to be applied. I would expect that each of the selected songs receive the same rating I specified.

I'm using the latest QL master, with all dependencies drawn from PureOS Green (basically Debian Testing).

**Comment by Phidica** [comment]
I do have the "confirm multiple ratings" option turned on. If it is turned off, then there is no problem and the rating is applied to all songs as expected.
