### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by formaj** [quodlibet/quodlibet#3150]
Steps to reproduce
------------------

Try to open, hangs for awhile.

Expected Output
---------------

Fails to open, no error message

Actual Output
-------------

at bottom

Test System
-----------

### Which version of Quod Libet?
>  4.2.0, 4.2.1, also tried 4.1.0. 
> 4.0.2 works fine.

### Which operating system 
> Mac OS 10.14

Additional Information
----------------------

=== SYSTEM INFORMATION:
Quod Libet 4.2.1
Mutagen 1.41.1
Python 3.7.1 (default, Oct 20 2018, 22:52:10) 
[Clang 7.3.0 (clang-703.0.31)] darwin
Platform Darwin-18.2.0-x86_64-i386-64bit
=== STACK TRACE

Traceback (most recent call last):

  File "/Applications/QuodLibet.app/Contents/Resources/bin/quodlibet", line 15, in <module>
    sys.exit(main())

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/main.py", line 38, in main
    quodlibet.init()

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/_init.py", line 58, in init
    _init_gst()

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/_init.py", line 379, in _init_gst
    environ["GST_REGISTRY"] = os.path.join(get_cache_dir(), registry_name)

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/util/misc.py", line 37, in wrapper
    res.append(f())

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/_main.py", line 136, in get_cache_dir
    mkdir(path, 0o700)

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/util/path.py", line 36, in mkdir
    os.makedirs(dir_, *args)

  File "os.py", line 221, in makedirs

PermissionError: [Errno 13] Permission denied: '/Users/al/.cache/quodlibet'

=== LOG:
D: 0.382: util.i18n.init: LANGUAGE: 'en_US:C:sv'
D: 0.382: util.i18n.init: LANG: 'en_US'
D: 0.383: util.i18n.register_translation: No translation found for the domain 'quodlibet'
D: 0.423: formats._misc.init: MimeType=application/x-flac;audio/aac;audio/aiff;audio/dsf;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpeg4;audio/mpg;audio/ogg;audio/vorbis;audio/wav;audio/wave;audio/x-aac;audio/x-aiff;audio/x-flac;audio/x-m4a;audio/x-midi;audio/x-mp3;audio/x-mpc;audio/x-mpeg;audio/x-ms-wma;audio/x-ms-wmv;audio/x-musepack;audio/x-oggflac;audio/x-speex;audio/x-tta;audio/x-wav;audio/x-wavpack;audio/x-wma;video/ogg;video/x-ms-asf;video/x-theora;video/x-wmv;
D: 0.423: formats._misc.init: Supported formats: aac, aiff, dsf, midi, monkeysaudio, mp3, mp4, mpc, spc, trueaudio, vgm, wav, wavpack, wma, xiph
E: 1.646: errorreport.main.errorhook: os.py:221:makedirs: PermissionError: [Errno 13] Permission denied: '/Users/al/.cache/quodlibet'

**Comment by frestr** [comment]
Hi. Does removing `/Users/al/.cache/quodlibet` fix the problem?

**Comment by formaj** [comment]
It didn't appear there but I created it myself. That seems to have fixed it.

**Comment by frestr** [comment]
Ok, so either the permissions of the cache directory is higher than usual or QL ran with too few permissions. There were some cache changes with 4.1.0, so it's possible that the directory was not touched before and therefore the issue didn't occur.

It's hard to say, but it's possible that the permissions of your file system are a bit unusual, since I would otherwise expect more people to have this problem.

Would still be good to have some failsafe for this case though.
