### ISSUE TITLE
mpris2 plugin raises ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by jversusk** [quodlibet/quodlibet#3272]
Started seeing this error yesterday, apparently happens on track changes. Disabling the MPRIS D-Bus plugin prevents the error, but then I lose the system applet integration too.

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/events/mpris/mpris2.py", line 151, in __library_changed
    self.emit_properties_changed(self.PLAYER_IFACE, ["Metadata"])

  File "/usr/lib/python2.7/dist-packages/quodlibet/util/dbusutils.py", line 300, in emit_properties_changed
    values[prop] = self.get_value(iface, prop, path)

  File "/usr/lib/python2.7/dist-packages/quodlibet/util/dbusutils.py", line 259, in get_value
    value = self.get_property(interface, prop)

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/events/mpris/mpris2.py", line 367, in get_property
    return self.__get_metadata()

  File "/usr/lib/python2.7/dist-packages/quodlibet/ext/events/mpris/mpris2.py", line 279, in __get_metadata
    metadata["xesam:" + xesam] = int(val)

ValueError: cannot convert float NaN to integer


Version: 3.9.1
Python: 2.7.15+ (default, Oct  7 2019, 17:39:04) 
[GCC 7.4.0]
Platform: Linux-4.15.0-66-generic-x86_64-with-LinuxMint-19.1-tessa
```

**Comment by declension** [comment]
@jversusk could you try a newer version (with Python 3) - I think this has been fixed a while ago

**Comment by jversusk** [comment]
@declension Appears to have been fixed, I'm not getting the error now. Thanks for the update.
