### ISSUE TITLE
[Error] OSError: [Errno 30] Sistema de arquivos somente para leitura: '/mnt/01D5C965F4430350/Backups/Mi5/Music/2018/2004 - Dead Letters/10) Funeral Song.m4a'

### ISSUE THREAD

**Issue by victorvmaciel** [quodlibet/quodlibet#3353]
* What did you try to do when the error occurred?

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/songsmenu.py", line 402, in trash_cb
    trash_songs(parent, songs, librarian)

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/delete.py", line 305, in trash_songs
    _do_trash_songs(parent, songs, librarian)

  File "/usr/lib/python2.7/dist-packages/quodlibet/qltk/delete.py", line 162, in _do_trash_songs
    trash.trash(filename)

  File "/usr/lib/python2.7/dist-packages/quodlibet/util/trash.py", line 154, in trash
    trash_free_desktop(path)

  File "/usr/lib/python2.7/dist-packages/quodlibet/util/trash.py", line 139, in trash_free_desktop
    shutil.move(path, target_path)

  File "/usr/lib/python2.7/shutil.py", line 326, in move
    os.unlink(src)

OSError: [Errno 30] Sistema de arquivos somente para leitura: '/mnt/01D5C965F4430350/Backups/Mi5/Music/2018/2004 - Dead Letters/10) Funeral Song.m4a'


Version: 3.9.1
Python: 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0]
Platform: Linux-5.3.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
```

**Comment by victorvmaciel** [comment]
Missunderstood.
