### ISSUE TITLE
[WinError 1005] The volume does not contain a recognized file system

### ISSUE THREAD

**Issue by 894-572** [quodlibet/quodlibet#3354]
Steps to reproduce
------------------

I'm trying to scan my network drive which is mounted with rclone.

Expected Output
---------------

The drive should be scanned.

Actual Output
-------------

No albums are added and the drive isn't scanned at all.

Test System
-----------

### Which version of Quod Libet?
4.3.0

### Which operating system 
Windows 10

Additional Information
----------------------
```
OSError: [WinError 1005] The volume does not contain a recognized file system.
------
Traceback (most recent call last):

  File "ntpath.py", line 660, in realpath

OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'F:\\007 - Agent Under Fire - Manual.pdf'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\util\copool.py", line 23, in wrap
    for value in func(*args, **kwargs):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\library\libraries.py", line 686, in rebuild
    for value in self.scan(paths, exclude, cofuncid):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\library\libraries.py", line 731, in scan
    for real_path in iter_paths(scan_path, exclude=exclude):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\library\libraries.py", line 511, in iter_paths
    fullfilename = os.path.realpath(fullfilename)

  File "ntpath.py", line 664, in realpath

  File "ntpath.py", line 614, in _getfinalpathname_nonstrict

OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'F:\\007 - Agent Under Fire - Manual.pdf'
```

**Comment by CreamyCookie** [comment]
@894-572 Is this still an issue in 4.4? (If not, please close this.)

**Comment by 894-572** [comment]
> @894-572 Is this still an issue in 4.4? (If not, please close this.)

No idea, sorry -- I don't use Windows anymore, thus closing.

**Comment by CreamyCookie** [comment]
Thanks! :+1: 

> I don't use Windows anymore

@894-572 That's always great to hear :)
