### ISSUE TITLE
iTunes Importer plugin

### ISSUE THREAD

**Issue by azarmadr** [quodlibet/quodlibet#3376]
The proposed change
-------------------
I wanted to import my itunes track stats so i just copied functions from rbimport and bansheeimport plugins and created one for itunes with `import plistlib`. 
I tried with my itunes lib and QL one. It was success.

Benefits of this change
-----------------------
1. this is for those who have itunes library with them to synchronize.
2. this plugin implements adding previous stats rather than just setting them.
3. I created average rating of the two ratings we have, this might not be ideal for everyone.

Any issues this might cause
---------------------------
- I dont know any issues as of now. i've tried it with my own library of 1500 songs, with success.

**Comment by azarmadr** [comment]
will attach the plugin here in the evening 👍

**Comment by sandersantema** [comment]
Will this allow me to import the date added metadata based on the iTunes.xml file?

**Comment by azarmadr** [comment]
> 
> 
> Will this allow me to import the date added metadata based on the iTunes.xml file?

we can only sync the stat metadata like plays and skips, ratings as such

**Comment by mmccul** [comment]
Tried it on Windows and got an error.  First, it presumed the wrong location for my iTunes library, easy fix.  Then I got the below error.


> AttributeError: 'iTunesimporter' object has no attribute '_library'
> ------
> Traceback (most recent call last):
> 
>   File "C:\Users\markm\AppData\Roaming\Quod Libet\plugins\itunesimport.py", line 114, in do_import
>     importer.read(plist)
> 
>   File "C:\Users\markm\AppData\Roaming\Quod Libet\plugins\itunesimport.py", line 31, in read
>     filename = uri2fsn(track['Location']).replace('\\','',2)
> 
> KeyError: 'Location'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\markm\AppData\Roaming\Quod Libet\plugins\itunesimport.py", line 139, in clicked_cb
>     do_import(button, app.library)
> 
>   File "C:\Users\markm\AppData\Roaming\Quod Libet\plugins\itunesimport.py", line 117, in do_import
>     importer.finish()
> 
>   File "C:\Users\markm\AppData\Roaming\Quod Libet\plugins\itunesimport.py", line 104, in finish
>     self._library.changed(self._changed_songs)
> 
> AttributeError: 'iTunesimporter' object has no attribute '_library'

For the first one, making the plist path configurable would likely be a good idea.  Not sure on the second one.
