### ISSUE TITLE
Not launching, error with Unity detection 

### ISSUE THREAD

**Issue by arielsboiardi** [quodlibet/quodlibet#3488]
Steps to reproduce
------------------
I tried to launch QuodLibet, bot from desktop entry and command line.

Expected Output
---------------
QuodLibet should launch. 

Actual Output
-------------
Nothing happend. `quodlibet -d` after some successful operations (scanning library) gives following error
```
E: 1.103: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/usr/bin/quodlibet", line 14, in <module>
        sys.exit(main())
      File "/usr/lib/python3.9/site-packages/quodlibet/main.py", line 104, in main
        unity.init("io.github.quodlibet.QuodLibet.desktop", player)
      File "/usr/lib/python3.9/site-packages/quodlibet/qltk/unity.py", line 46, in init
        launcher = Unity.LauncherEntry.get_for_desktop_id(desktop_id)
    gi.repository.GLib.GError: g-invoke-error-quark: Could not locate unity_launcher_entry_get_for_desktop_id: 'unity_launcher_entry_get_for_desktop_id': /usr/bin/python3: undefined symbol: unity_launcher_entry_get_for_desktop_id (1)
```

Test System
-----------

### Which version of Quod Libet?
Quod Libet 4.3.0

### Which operating system 
Fedora release 33 (Thirty Three) x86_64

Additional Information
----------------------
I found an hacky solution by changing `quodlibet/qltk/unity.py` setting `is_unity = False` by default. Sure there is a better solution (I bet mine does not work on Unity...), but I did not have time to figure it out. 

Thanks for the great work!

**Comment by arielsboiardi** [comment]
Sorry, I noticed that (I don't know why) `libunity` was installed on my system.
