### ISSUE TITLE
Lrc file larger than 60 minutes cause synchronized lyrics plugin failure

### ISSUE THREAD

**Issue by Boycottangent** [quodlibet/quodlibet#3498]
Steps to reproduce
------------------

Play a audio file longer than 1 hour, with a lrc file loaded to display synchronized lyrics

Expected Output
---------------

Everything should be working fine as this plugin worked well with my other lrc files

Actual Output
-------------

Quadlibet prompted Error
<img width="451" alt="image" src="https://user-images.githubusercontent.com/23280916/99180169-f83ba680-275e-11eb-88b1-1dd70174580c.png">
```
ValueError: time data '60:05.22' does not match format '%M:%S.%f'
------
Traceback (most recent call last):

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/plugins/events.py", line 140, in __invoke
    handler(*args)

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/ext/events/synchronizedlyrics.py", line 281, in plugin_on_song_started
    self._build_data()

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/ext/events/synchronizedlyrics.py", line 196, in _build_data
    self._parse_lrc_file(new_lrc)

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/ext/events/synchronizedlyrics.py", line 220, in _parse_lrc_file
    t = datetime.strptime(line[1:close_bracket], '%M:%S.%f')

  File "_strptime.py", line 577, in _strptime_datetime

  File "_strptime.py", line 359, in _strptime

ValueError: time data '60:05.22' does not match format '%M:%S.%f'
```

Test System
-----------

### Which version of Quod Libet?
4.3.0
### Which operating system 
macOS Big Sur (macOS 11)

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-N3](https://sentry.io/organizations/quodlibet/issues/2176893263/?referrer=github_plugin)
