### ISSUE TITLE
Decoding error appears twice after starting a new song

### ISSUE THREAD

**Issue by racuna** [quodlibet/quodlibet#3579]
Just starting to play a song this message appears:

> An Error Ocurred
> You can ignore this error, but the application might be unstable until it restarted. Submitting an error report will only take few seconds and would help us a lot.
> Error details:
```
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 4: invalid continuation byte
> ------
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 4: invalid continuation byte
```

I already reported it, and also tried to restart the app, and even Windows, but the problem persists. If I clic in Ignore Error, a second message appears with different details:

```
> RuntimeError: Converting the GError failed

------
Traceback (most recent call last):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\plugins\events.py", line 140, in __invoke
    handler(*args)

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\ext\events\animosd\main.py", line 53, in plugin_on_song_started
    window = OSDWindow(self.Conf, song)

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\ext\events\animosd\osdwindow.py", line 66, in __init__
    cover_pixbuf = app.cover_manager.get_pixbuf(

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\util\cover\manager.py", line 206, in get_pixbuf
    return self.get_pixbuf_many([song], width, height)

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\util\cover\manager.py", line 201, in get_pixbuf_many
    return get_thumbnail_from_file(fileobj, (width, height))

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\util\thumbnails.py", line 85, in get_thumbnail_from_file
    return get_thumbnail(path, boundary)
```

**Comment by declension** [comment]
Thanks. This has definitely been happening a lot recently.

Do you think you could run with `--debug` and post a bit of the logs before this happens?

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-P1](https://sentry.io/organizations/quodlibet/issues/2272631661/?referrer=github_plugin)

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-NQ](https://sentry.io/organizations/quodlibet/issues/2248960297/?referrer=github_plugin)

**Comment by racuna** [comment]
Sorry, no output with quodlibet.exe --debug

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-NR](https://sentry.io/organizations/quodlibet/issues/2248960390/?referrer=github_plugin)

**Comment by TeamSpen210** [comment]
Did a little digging, and found this [pygobject](https://gitlab.gnome.org/GNOME/pygobject/-/issues/442) issue with the same kind of error and a GDB trace. The message I got which failed to decode was:
```py
b'Failed to open file \x93C:\\Users\\Spencer Brown\\AppData\\Local\\Microsoft\\Windows\\INetCache\\quodlibet\\thumbnails\\large\\e251d6ff4ebea994c30beb85d7ff34e9.png\x94: No such file or directory'
```
Seems Windows is generating a CP-1252 encoded string with curly quotes, but it's trying to UTF-8 decode it. That would need to be fixed upstream.

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-R0](https://sentry.io/organizations/quodlibet/issues/2570164333/?referrer=github_plugin)

**Comment by declension** [comment]
We need to add a workaround here I think, too much breakage whilst waiting for any upstream fixes (on Windows)

Probably just a few simple exception catch-and-log will do the trick here. Shame Sentry isn't giving the stack trace here actually...

**Comment by TeamSpen210** [comment]
It just needs an [updated binary for `gdk-pixbuf` to version 2.42.4](https://packages.msys2.org/base/mingw-w64-gdk-pixbuf2), which is done now so quodlibet just needs to do a release.
