### ISSUE TITLE
QL fails to create new configuration on exFAT disk

### ISSUE THREAD

**Issue by bassstorm** [quodlibet/quodlibet#3604]
Steps to reproduce
------------------
0. Have an exFAT-formatted SSD
1. Run QL for first time pointing $QUODLIBET_USERDIR to the disk

```
[bassstorm@bassstorm ~]$ export QUODLIBET_USERDIR=/run/media/bassstorm/EXFAT_SSD/.quodlibet
[bassstorm@bassstorm ~]$ quodlibet --debug
D: 0.083: util.i18n.init: LANGUAGE: ''
D: 0.083: util.i18n.init: LANG: 'en_US.UTF-8'
D: 0.083: util.i18n.register_translation: No translation found for domain 'quodlibet' in None
D: 0.103: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/formats/__pycache__'
D: 0.153: formats._misc.init: MimeType=application/x-flac;audio/aac;audio/aiff;audio/dsf;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpeg4;audio/mpg;audio/ogg;audio/vorbis;audio/wav;audio/wave;audio/x-aac;audio/x-aiff;audio/x-flac;audio/x-m4a;audio/x-midi;audio/x-mp3;audio/x-mpc;audio/x-mpeg;audio/x-ms-wma;audio/x-ms-wmv;audio/x-musepack;audio/x-oggflac;audio/x-speex;audio/x-tta;audio/x-wav;audio/x-wavpack;audio/x-wma;video/ogg;video/x-ms-asf;video/x-theora;video/x-wmv;
D: 0.153: formats._misc.init: Supported formats: aac, aiff, dsf, midi, mod, monkeysaudio, mp3, mp4, mpc, spc, trueaudio, vgm, wav, wavpack, wma, xiph

(quodlibet:898421): Gtk-WARNING **: 17:35:25.946: Locale not supported by C library.
        Using the fallback 'C' locale.

(quodlibet:898421): Gtk-WARNING **: 17:35:25.956: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(quodlibet:898421): Gtk-WARNING **: 17:35:25.957: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(quodlibet:898421): Gtk-WARNING **: 17:35:25.957: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
D: 0.322: qltk.add_signal_watch: Register Python signal handler: 'SIGINT'
D: 0.322: qltk.add_signal_watch: Register Python signal handler: 'SIGTERM'
D: 0.322: qltk.add_signal_watch: Register Python signal handler: 'SIGHUP'
D: 0.425: main.main: Initializing main library (/run/media/bassstorm/EXFAT_SSD/.quodlibet/songs)
D: 0.425: SongFileLibrary.__init__: Initializing <class 'quodlibet.library.libraries.SongFileLibrary'>: 'main'
D: 0.425: SongFileLibrary.__init__: Using pickling persistence for library "main"
D: 0.425: SongFileLibrary.load: Loading contents of '/run/media/bassstorm/EXFAT_SSD/.quodlibet/songs'.
W: 0.425: library.libraries._load_items: Couldn't load library file from: '/run/media/bassstorm/EXFAT_SSD/.quodlibet/songs'
D: 0.425: SongFileLibrary.load('main'): Done loading contents of '/run/media/bassstorm/EXFAT_SSD/.quodlibet/songs'
D: 0.434: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/__pycache__'
D: 0.434: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/playlists/__pycache__'
D: 0.434: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/soundcloud/__pycache__'
D: 0.434: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/collection/__pycache__'
D: 0.435: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/paned/__pycache__'
D: 0.435: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/albums/__pycache__'
D: 0.435: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/covergrid/__pycache__'
D: 0.591: PlaylistsBrowser.load_pattern: Loading pattern from /run/media/bassstorm/EXFAT_SSD/.quodlibet/playlist_pattern
D: 0.591: PlaylistsBrowser.load_pattern: Couldn't load pattern for PlaylistsBrowser ([Errno 2] No such file or directory: '/run/media/bassstorm/EXFAT_SSD/.quodlibet/playlist_pattern'), using default.
D: 0.592: AlbumList.load_pattern: Loading pattern from /run/media/bassstorm/EXFAT_SSD/.quodlibet/album_pattern
D: 0.592: AlbumList.load_pattern: Couldn't load pattern for AlbumList ([Errno 2] No such file or directory: '/run/media/bassstorm/EXFAT_SSD/.quodlibet/album_pattern'), using default.
D: 0.594: CoverGrid.load_pattern: Loading pattern from /run/media/bassstorm/EXFAT_SSD/.quodlibet/album_pattern
D: 0.594: CoverGrid.load_pattern: Couldn't load pattern for CoverGrid ([Errno 2] No such file or directory: '/run/media/bassstorm/EXFAT_SSD/.quodlibet/album_pattern'), using default.
D: 0.594: SongFileLibrary.__init__: Initializing <class 'quodlibet.library.libraries.SongFileLibrary'>: 'filesystem'
D: 0.594: SongFileLibrary.__init__: Using pickling persistence for library "filesystem"
D: 0.594: _main.init_plugins: Starting plugin manager
D: 0.594: _main.init_plugins: Scanning folders: ['/usr/lib/python3.9/site-packages/quodlibet/ext/editing', '/usr/lib/python3.9/site-packages/quodlibet/ext/events', '/usr/lib/python3.9/site-packages/quodlibet/ext/playorder', '/usr/lib/python3.9/site-packages/quodlibet/ext/songsmenu', '/usr/lib/python3.9/site-packages/quodlibet/ext/playlist', '/usr/lib/python3.9/site-packages/quodlibet/ext/gstreamer', '/usr/lib/python3.9/site-packages/quodlibet/ext/covers', '/usr/lib/python3.9/site-packages/quodlibet/ext/query', '/run/media/bassstorm/EXFAT_SSD/.quodlibet/plugins']
D: 0.594: plugins.__restore: Restoring plugins: 0
D: 0.594: PluginManager.rescan: Rescanning..
D: 0.594: ModuleScanner.rescan: Rescanning..
D: 0.595: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/editing/__pycache__'
D: 0.595: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/events/__pycache__'
D: 0.595: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/events/mpdserver/__pycache__'
D: 0.595: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/events/animosd/__pycache__'
D: 0.595: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/events/mpris/__pycache__'
D: 0.595: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/events/trayicon/__pycache__'
D: 0.596: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/playorder/__pycache__'
D: 0.596: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/songsmenu/__pycache__'
D: 0.596: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/songsmenu/fingerprint/__pycache__'
D: 0.596: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/songsmenu/brainz/__pycache__'
D: 0.596: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/playlist/__pycache__'
D: 0.596: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/gstreamer/__pycache__'
D: 0.597: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/covers/__pycache__'
D: 0.597: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/query/__pycache__'
D: 1.075: ModuleScanner.rescan: Rescanning done: 98 added, 0 removed, 3 error(s)
D: 1.078: PluginManager.rescan: Rescanning done.
D: 1.078: PluginManager.register_handler: Registering handler: 'EditTagsPluginHandler'
D: 1.078: PluginManager.register_handler: Registering handler: 'RenameFilesPluginHandler'
D: 1.078: PluginManager.register_handler: Registering handler: 'TagsFromPathPluginHandler'
D: 1.078: PluginManager.register_handler: Registering handler: 'GStreamerPlayer'
D: 1.080: PluginManager.register_handler: Registering handler: 'SongsMenuPluginHandler'
D: 1.080: PluginManager.register_handler: Registering handler: 'CoverPluginHandler'
D: 1.080: PluginManager.register_handler: Registering handler: 'PlaylistPluginHandler'
D: 1.080: PluginManager.register_handler: Registering handler: 'QueryPluginHandler'
D: 1.134: PluginManager.register_handler: Registering handler: 'PluggableOrders'
D: 1.135: PluginManager.register_handler: Registering handler: 'PluggableOrders'
D: 1.136: qltk.playorder.__compose_order: Updating PlaylistModel order to <In Order>
D: 1.156: GStreamerPlayer.go_to: Going to None
D: 1.156: PlaylistMux.go_to: Told to go to None
D: 1.156: QueueModel.go_to: Told to go to None
D: 1.156: PlaylistModel.go_to: Told to go to None
D: 1.183: Query.__init__: Creating query ''
D: 1.183: Query.__init__: Creating query ''
D: 1.185: qltk.window.__restore_state: Restore state
D: 1.185: qltk.window.__restore_position: Restore position
D: 1.185: qltk.window.__restore_size: Restore size
D: 1.185: PluginManager.register_handler: Registering handler: 'EventPluginHandler'
D: 1.185: PluginManager.register_handler: Registering handler: 'UserInterfacePluginHandler'
D: 1.188: mmkeys.find_active_backend: Trying to find a mmkeys backend
D: 1.197: mmkeys.find_active_backend: Found 'KeybinderBackend'

** (io.github.quodlibet.QuodLibet:898421): WARNING **: 17:35:26.936: Binding 'XF86AudioPrev' failed!

** (io.github.quodlibet.QuodLibet:898421): WARNING **: 17:35:26.936: Binding 'XF86AudioNext' failed!

** (io.github.quodlibet.QuodLibet:898421): WARNING **: 17:35:26.937: Binding 'XF86AudioStop' failed!

** (io.github.quodlibet.QuodLibet:898421): WARNING **: 17:35:26.937: Binding 'XF86AudioPlay' failed!

** (io.github.quodlibet.QuodLibet:898421): WARNING **: 17:35:26.938: Binding 'XF86AudioRepeat' failed!

** (io.github.quodlibet.QuodLibet:898421): WARNING **: 17:35:26.938: Binding 'XF86AudioRandomPlay' failed!
D: 1.203: session.init: Trying GnomeSessionClient
D: 1.203: GnomeSessionClient.open: Connecting with gnome session manager
D: 1.204: session.init: org.gnome.SessionManager unowned
D: 1.204: session.init: Trying XfceSessionClient
D: 1.204: XfceSessionClient.open: Connecting with gnome session manager
D: 1.205: session.init: org.xfce.SessionManager unowned
D: 1.206: session.init: Trying XSMPSessionClient
D: 1.209: XSMPSessionClient.open: Connecting with XSMP
D: 1.210: XSMPSessionClient.open: Connected. Client ID: 106d3200000161789612600000011450233
D: 1.210: _main.run: Entering quodlibet.main
D: 1.267: qltk.quodlibetwindow.__configure_scan_dirs: Couldn't find any scan dirs
E: 1.362: errorreport.main.errorhook:
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/quodlibet/util/fifo.py", line 241, in _open
        fcntl.flock(fifo, fcntl.LOCK_EX | fcntl.LOCK_NB)
    BlockingIOError: [Errno 11] Resource temporarily unavailable
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/gi/overrides/GLib.py", line 671, in <lambda>
        func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
      File "/usr/lib/python3.9/site-packages/quodlibet/util/fifo.py", line 284, in _process
        self._open(*args)
      File "/usr/lib/python3.9/site-packages/quodlibet/util/fifo.py", line 250, in _open
        raise FIFOError("fifo already locked")
    quodlibet.util.fifo.FIFOError: fifo already locked
D: 1.682: session.xsmp.save_yourself: xsmp: save_yourself (<SaveType.LOCAL: 1>, False, <InteractStyle.NONE: 0>, False)
D: 1.684: session.xsmp.save_complete: xsmp: save_complete
D: 1.830: Query.__init__: Creating query ''
D: 1.832: PlaylistModel.set: Filling view model with 0 songs.
D: 1.837: qltk.completion.__build_model: Updating tag model for whole library
D: 1.837: qltk.completion.__build_model: Done updating tag model for whole library
D: 1.837: SongFileLibrary.rebuild('main'): Rebuilding, force is False
D: 1.838: SongFileLibrary.rebuild('main'): Removing 0, changing 0).
D: 45.210: qltk.window.__restore_state: Restore state
D: 45.210: qltk.window.__restore_position: Restore position
D: 45.210: qltk.window.__restore_size: Restore size
D: 45.213: main.before_quit: Saving active browser state
D: 45.213: main.before_quit: Shutting down player device 'GStreamer: 1.18.4.0'.
D: 45.215: player.gstbe.player.__destroy_pipeline: Destroying Gstreamer pipeline
D: 45.215: PluginManager.save: Saving plugins: 0 active
D: 45.218: _main.quit_gtk: Quit GTK: done.
D: 45.239: _main.run: Gtk.main() done.
D: 45.253: library.save: Saving all libraries...
D: 45.253: config.save: Writing config...
D: 45.267: XSMPSessionClient.close: Disconnecting from XSMP
D: 45.267: main.main: Finished shutdown.
```

Expected Output
---------------
New default configuration applied. No errors occured.

Actual Output
-------------
I/O error in logs and on UI

Test System
-----------

### Which version of Quod Libet?
[bassstorm@bassstorm ~]$ quodlibet --version
Quod Libet 4.4.0

### Which operating system 
[bassstorm@bassstorm ~]$ uname -r
5.4.105-1-MANJARO

### If it's audio-related, what back-end?
N/A

Additional Information
----------------------
Same steps work fine for NTFS-formatted HDD

```
[bassstorm@bassstorm ~]$ export QUODLIBET_USERDIR=/run/media/bassstorm/NTFS_HDD/.quodlibet
[bassstorm@bassstorm ~]$ quodlibet --debug
D: 0.058: util.i18n.init: LANGUAGE: ''
D: 0.058: util.i18n.init: LANG: 'en_US.UTF-8'
D: 0.059: util.i18n.register_translation: No translation found for domain 'quodlibet' in None
D: 0.073: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/formats/__pycache__'
D: 0.102: formats._misc.init: MimeType=application/x-flac;audio/aac;audio/aiff;audio/dsf;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpeg4;audio/mpg;audio/ogg;audio/vorbis;audio/wav;audio/wave;audio/x-aac;audio/x-aiff;audio/x-flac;audio/x-m4a;audio/x-midi;audio/x-mp3;audio/x-mpc;audio/x-mpeg;audio/x-ms-wma;audio/x-ms-wmv;audio/x-musepack;audio/x-oggflac;audio/x-speex;audio/x-tta;audio/x-wav;audio/x-wavpack;audio/x-wma;video/ogg;video/x-ms-asf;video/x-theora;video/x-wmv;
D: 0.103: formats._misc.init: Supported formats: aac, aiff, dsf, midi, mod, monkeysaudio, mp3, mp4, mpc, spc, trueaudio, vgm, wav, wavpack, wma, xiph

(quodlibet:898622): Gtk-WARNING **: 17:36:54.630: Locale not supported by C library.
        Using the fallback 'C' locale.

(quodlibet:898622): Gtk-WARNING **: 17:36:54.638: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(quodlibet:898622): Gtk-WARNING **: 17:36:54.638: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(quodlibet:898622): Gtk-WARNING **: 17:36:54.639: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
D: 0.233: qltk.add_signal_watch: Register Python signal handler: 'SIGINT'
D: 0.233: qltk.add_signal_watch: Register Python signal handler: 'SIGTERM'
D: 0.234: qltk.add_signal_watch: Register Python signal handler: 'SIGHUP'
D: 0.308: main.main: Initializing main library (/run/media/bassstorm/NTFS_HDD/.quodlibet/songs)
D: 0.308: SongFileLibrary.__init__: Initializing <class 'quodlibet.library.libraries.SongFileLibrary'>: 'main'
D: 0.308: SongFileLibrary.__init__: Using pickling persistence for library "main"
D: 0.308: SongFileLibrary.load: Loading contents of '/run/media/bassstorm/NTFS_HDD/.quodlibet/songs'.
W: 0.309: library.libraries._load_items: Couldn't load library file from: '/run/media/bassstorm/NTFS_HDD/.quodlibet/songs'
D: 0.309: SongFileLibrary.load('main'): Done loading contents of '/run/media/bassstorm/NTFS_HDD/.quodlibet/songs'
D: 0.314: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/__pycache__'
D: 0.314: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/playlists/__pycache__'
D: 0.314: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/soundcloud/__pycache__'
D: 0.314: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/collection/__pycache__'
D: 0.314: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/paned/__pycache__'
D: 0.314: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/albums/__pycache__'
D: 0.314: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/browsers/covergrid/__pycache__'
D: 0.442: PlaylistsBrowser.load_pattern: Loading pattern from /run/media/bassstorm/NTFS_HDD/.quodlibet/playlist_pattern
D: 0.442: PlaylistsBrowser.load_pattern: Couldn't load pattern for PlaylistsBrowser ([Errno 2] No such file or directory: '/run/media/bassstorm/NTFS_HDD/.quodlibet/playlist_pattern'), using default.
D: 0.444: AlbumList.load_pattern: Loading pattern from /run/media/bassstorm/NTFS_HDD/.quodlibet/album_pattern
D: 0.444: AlbumList.load_pattern: Couldn't load pattern for AlbumList ([Errno 2] No such file or directory: '/run/media/bassstorm/NTFS_HDD/.quodlibet/album_pattern'), using default.
D: 0.445: CoverGrid.load_pattern: Loading pattern from /run/media/bassstorm/NTFS_HDD/.quodlibet/album_pattern
D: 0.445: CoverGrid.load_pattern: Couldn't load pattern for CoverGrid ([Errno 2] No such file or directory: '/run/media/bassstorm/NTFS_HDD/.quodlibet/album_pattern'), using default.
D: 0.445: SongFileLibrary.__init__: Initializing <class 'quodlibet.library.libraries.SongFileLibrary'>: 'filesystem'
D: 0.445: SongFileLibrary.__init__: Using pickling persistence for library "filesystem"
D: 0.446: _main.init_plugins: Starting plugin manager
D: 0.446: _main.init_plugins: Scanning folders: ['/usr/lib/python3.9/site-packages/quodlibet/ext/editing', '/usr/lib/python3.9/site-packages/quodlibet/ext/events', '/usr/lib/python3.9/site-packages/quodlibet/ext/playorder', '/usr/lib/python3.9/site-packages/quodlibet/ext/songsmenu', '/usr/lib/python3.9/site-packages/quodlibet/ext/playlist', '/usr/lib/python3.9/site-packages/quodlibet/ext/gstreamer', '/usr/lib/python3.9/site-packages/quodlibet/ext/covers', '/usr/lib/python3.9/site-packages/quodlibet/ext/query', '/run/media/bassstorm/NTFS_HDD/.quodlibet/plugins']
D: 0.446: plugins.__restore: Restoring plugins: 0
D: 0.446: PluginManager.rescan: Rescanning..
D: 0.446: ModuleScanner.rescan: Rescanning..
D: 0.446: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/editing/__pycache__'
D: 0.446: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/events/__pycache__'
D: 0.447: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/events/mpdserver/__pycache__'
D: 0.447: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/events/animosd/__pycache__'
D: 0.447: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/events/mpris/__pycache__'
D: 0.447: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/events/trayicon/__pycache__'
D: 0.447: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/playorder/__pycache__'
D: 0.447: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/songsmenu/__pycache__'
D: 0.447: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/songsmenu/fingerprint/__pycache__'
D: 0.447: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/songsmenu/brainz/__pycache__'
D: 0.448: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/playlist/__pycache__'
D: 0.448: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/gstreamer/__pycache__'
D: 0.448: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/covers/__pycache__'
D: 0.448: util.importhelper.get_importables: Ignoring '/usr/lib/python3.9/site-packages/quodlibet/ext/query/__pycache__'
D: 0.840: ModuleScanner.rescan: Rescanning done: 98 added, 0 removed, 3 error(s)
D: 0.842: PluginManager.rescan: Rescanning done.
D: 0.842: PluginManager.register_handler: Registering handler: 'EditTagsPluginHandler'
D: 0.843: PluginManager.register_handler: Registering handler: 'RenameFilesPluginHandler'
D: 0.843: PluginManager.register_handler: Registering handler: 'TagsFromPathPluginHandler'
D: 0.843: PluginManager.register_handler: Registering handler: 'GStreamerPlayer'
D: 0.844: PluginManager.register_handler: Registering handler: 'SongsMenuPluginHandler'
D: 0.844: PluginManager.register_handler: Registering handler: 'CoverPluginHandler'
D: 0.844: PluginManager.register_handler: Registering handler: 'PlaylistPluginHandler'
D: 0.844: PluginManager.register_handler: Registering handler: 'QueryPluginHandler'
D: 0.969: PluginManager.register_handler: Registering handler: 'PluggableOrders'
D: 0.971: PluginManager.register_handler: Registering handler: 'PluggableOrders'
D: 0.973: qltk.playorder.__compose_order: Updating PlaylistModel order to <In Order>
D: 0.993: GStreamerPlayer.go_to: Going to None
D: 0.993: PlaylistMux.go_to: Told to go to None
D: 0.993: QueueModel.go_to: Told to go to None
D: 0.994: PlaylistModel.go_to: Told to go to None
D: 1.012: Query.__init__: Creating query ''
D: 1.012: Query.__init__: Creating query ''
D: 1.014: qltk.window.__restore_state: Restore state
D: 1.014: qltk.window.__restore_position: Restore position
D: 1.015: qltk.window.__restore_size: Restore size
D: 1.015: PluginManager.register_handler: Registering handler: 'EventPluginHandler'
D: 1.015: PluginManager.register_handler: Registering handler: 'UserInterfacePluginHandler'
D: 1.016: mmkeys.find_active_backend: Trying to find a mmkeys backend
D: 1.024: mmkeys.find_active_backend: Found 'KeybinderBackend'

** (io.github.quodlibet.QuodLibet:898622): WARNING **: 17:36:55.505: Binding 'XF86AudioPrev' failed!

** (io.github.quodlibet.QuodLibet:898622): WARNING **: 17:36:55.506: Binding 'XF86AudioNext' failed!

** (io.github.quodlibet.QuodLibet:898622): WARNING **: 17:36:55.506: Binding 'XF86AudioStop' failed!

** (io.github.quodlibet.QuodLibet:898622): WARNING **: 17:36:55.506: Binding 'XF86AudioPlay' failed!

** (io.github.quodlibet.QuodLibet:898622): WARNING **: 17:36:55.507: Binding 'XF86AudioRepeat' failed!

** (io.github.quodlibet.QuodLibet:898622): WARNING **: 17:36:55.507: Binding 'XF86AudioRandomPlay' failed!
D: 1.029: session.init: Trying GnomeSessionClient
D: 1.029: GnomeSessionClient.open: Connecting with gnome session manager
D: 1.030: session.init: org.gnome.SessionManager unowned
D: 1.031: session.init: Trying XfceSessionClient
D: 1.031: XfceSessionClient.open: Connecting with gnome session manager
D: 1.031: session.init: org.xfce.SessionManager unowned
D: 1.032: session.init: Trying XSMPSessionClient
D: 1.034: XSMPSessionClient.open: Connecting with XSMP
D: 1.034: XSMPSessionClient.open: Connected. Client ID: 106d3200000161789621500000011450234
D: 1.035: _main.run: Entering quodlibet.main
D: 1.091: qltk.quodlibetwindow.__configure_scan_dirs: Couldn't find any scan dirs
D: 1.112: session.xsmp.save_yourself: xsmp: save_yourself (<SaveType.LOCAL: 1>, False, <InteractStyle.NONE: 0>, False)
D: 1.113: session.xsmp.save_complete: xsmp: save_complete
D: 1.290: Query.__init__: Creating query ''
D: 1.291: PlaylistModel.set: Filling view model with 0 songs.
D: 1.294: qltk.completion.__build_model: Updating tag model for whole library
D: 1.294: qltk.completion.__build_model: Done updating tag model for whole library
D: 1.294: SongFileLibrary.rebuild('main'): Rebuilding, force is False
D: 1.295: SongFileLibrary.rebuild('main'): Removing 0, changing 0).
D: 6.715: qltk.window.__restore_state: Restore state
D: 6.716: qltk.window.__restore_position: Restore position
D: 6.716: qltk.window.__restore_size: Restore size
D: 6.718: main.before_quit: Saving active browser state
D: 6.718: main.before_quit: Shutting down player device 'GStreamer: 1.18.4.0'.
D: 6.719: player.gstbe.player.__destroy_pipeline: Destroying Gstreamer pipeline
D: 6.720: PluginManager.save: Saving plugins: 0 active
D: 6.724: _main.quit_gtk: Quit GTK: done.
D: 6.745: _main.run: Gtk.main() done.
D: 6.762: library.save: Saving all libraries...
D: 6.762: config.save: Writing config...
D: 6.988: XSMPSessionClient.close: Disconnecting from XSMP
D: 6.989: main.main: Finished shutdown.
```

**Comment by bassstorm** [comment]
From logs it's not clear, but in debug I see the issue is likely around `.quodlibet/control` resource. Should you have any ideas or suggestions, I'd be happy to check.

**Comment by declension** [comment]
Yes that's the one. Can you manually create one? e.g. `mkfifo -m 600 ~/.quodlibet/test'?

**Comment by bassstorm** [comment]
@declension thanks for the hint, here's what I see:
```
[bassstorm@bassstorm .quodlibet]$ ls
accels  config  dumps  feeds  playlists  queue  songs
[bassstorm@bassstorm .quodlibet]$ mkfifo -m 600 ./test
mkfifo: cannot create fifo './test': Input/output error
[bassstorm@bassstorm .quodlibet]$ ls
accels  config  dumps  feeds  playlists  queue  songs  test
[bassstorm@bassstorm .quodlibet]$ mkfifo -m 600 ./test
mkfifo: cannot create fifo './test': File exists
```

**Comment by bassstorm** [comment]
Small update: that `mkfifo -m 600 ./test` works good on macOS Big Sur.

**Comment by bassstorm** [comment]
Still reproducible on kernel 3.15 / python 3.10.

**Comment by declension** [comment]
Looks like FIFOs are somehow unsupported on this exFAT mount.

Perhaps this should be a non-fatal error for QL, disabling all UNIX control options... but this could be huge (no CLI?) so not sure what's best really

**Comment by bassstorm** [comment]
No worries. I would say this issue is quite minor for me since I finally managed to get used to distributed configuration. There's much more interesting QL feature requests and bugs around to tackle :)
