### ISSUE TITLE
BWF support

### ISSUE THREAD

**Issue by Blindekinder** [quodlibet/quodlibet#3667]
The proposed change
-------------------

Support for BWF, which is not recognized.

Benefits of this change
-----------------------

BWF tend to be the major professional, audio and broadcasting format.
https://en.wikipedia.org/wiki/Broadcast_Wave_Format
It uses the same .wav extension, and is the same raw sound flux, the only change is the extended informations.

**Comment by declension** [comment]
Thanks. I didn't even know about this format. Could you elaborate on it not being recognised - do you get errors (try with `--debug`)? 

What happens exactly? From scanning that article seems like it should be fairly compatible with WAV playing? 

For playing itself, Gstreamer would need to support it first as we use that for all audio streams.

For WAV metadata support see also #3556 actually.

**Comment by Blindekinder** [comment]
That's the output when trying to open a file using "open with..." from Nemo. Same errors appear when opening a directory with BWF files within QL, they even don't appear in track list.

```
D: 44.782: PlaylistModel.set: Filling view model with 0 songs.
D: 83.859: CommandRegistry.handle_line: command: 'play-file'(*['/home/raphael/Documents/Bibouac/export/#8_PostalSorting-AmbientSound1.wav'])
D: 83.859: CommandRegistry.run: Running '_play_file' with params ('/home/raphael/Documents/Bibouac/export/#8_PostalSorting-AmbientSound1.wav',) 
W: 83.859: formats._misc.MusicFile: Error loading '/home/raphael/Documents/Bibouac/export/#8_PostalSorting-AmbientSound1.wav'
E: 83.859: formats._misc.MusicFile:
    Traceback (most recent call last):
      File "/app/lib/python3.8/site-packages/quodlibet/formats/_misc.py", line 45, in translate_errors
        yield
      File "/app/lib/python3.8/site-packages/quodlibet/formats/wav.py", line 27, in __init__
        f = wave.open(h)
      File "/usr/lib/python3.8/wave.py", line 510, in open
        return Wave_read(f)
      File "/usr/lib/python3.8/wave.py", line 164, in __init__
        self.initfp(f)
      File "/usr/lib/python3.8/wave.py", line 144, in initfp
        self._read_fmt_chunk(chunk)
      File "/usr/lib/python3.8/wave.py", line 269, in _read_fmt_chunk
        raise Error('unknown format: %r' % (wFormatTag,))
    wave.Error: unknown format: 3
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/app/lib/python3.8/site-packages/quodlibet/formats/_misc.py", line 114, in MusicFile
        return loader(filename)
      File "/app/lib/python3.8/site-packages/quodlibet/formats/wav.py", line 31, in __init__
        self["~#bitdepth"] = f.getsampwidth() * 8
      File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/app/lib/python3.8/site-packages/quodlibet/formats/_misc.py", line 51, in translate_errors
        reraise(MutagenBug, e)
      File "/app/lib/python3.8/site-packages/quodlibet/util/__init__.py", line 1151, in reraise
        raise tp(value).with_traceback(tb)
      File "/app/lib/python3.8/site-packages/quodlibet/formats/_misc.py", line 45, in translate_errors
        yield
      File "/app/lib/python3.8/site-packages/quodlibet/formats/wav.py", line 27, in __init__
        f = wave.open(h)
      File "/usr/lib/python3.8/wave.py", line 510, in open
        return Wave_read(f)
      File "/usr/lib/python3.8/wave.py", line 164, in __init__
        self.initfp(f)
      File "/usr/lib/python3.8/wave.py", line 144, in initfp
        self._read_fmt_chunk(chunk)
      File "/usr/lib/python3.8/wave.py", line 269, in _read_fmt_chunk
        raise Error('unknown format: %r' % (wFormatTag,))
    quodlibet.formats._misc.MutagenBug: unknown format: 3
```
