### ISSUE TITLE
Thumbnails seems to be failing.

### ISSUE THREAD

**Issue by datakid** [quodlibet/quodlibet#3713]
Steps to reproduce
------------------
open QL

Expected Output
---------------
No error.

Actual Output
-------------
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 20: invalid start byte
```
and 

```
RuntimeError: Converting the GError failed
------

Traceback (most recent call last):

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\qltk\cover.py", line 180, in do_get_preferred_width_for_height
    width, height = self._get_size(300, req_height)

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\qltk\cover.py", line 154, in _get_size
    pixbuf = self._get_pixbuf()

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\qltk\cover.py", line 145, in _get_pixbuf
    self._pixbuf = thumbnails.get_thumbnail_from_file(

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\util\thumbnails.py", line 85, in get_thumbnail_from_file
    return get_thumbnail(path, boundary)

  File "C:\Program Files\Quod Libet\lib\python3.8\site-packages\quodlibet\util\thumbnails.py", line 139, in get_thumbnail
    pb = new_from_file_at_size(thumb_path, width, height)

RuntimeError: Converting the GError failed
```
and

```
{'event_id': '8b5b33a07de7411987a4e4306589aff7',
'exception': {'values': [{'module': 'builtins',
      'stacktrace': {'frames': [{'abs_path': 'C:/Program '
                'Files/Quod '
                'Libet/lib/python3.8/site-packages/quodlibet/qltk/cover.py',
             'context_line': '        '
                 'width, '
                 'height '
                 '= '
                 'self._get_size(300, '
                 'req_height)',
             'filename': 'quodlibet/qltk/cover.py',
             'function': 'do_get_preferred_width_for_height',
             'lineno': 180,
             'module': 'quodlibet.qltk.cover',
             'post_context': ['',
                 '        '
                 'if '
                 'width '
                 '> '
                 '256:',
                 '            '
                 'width '
                 '= '
                 'width',
                 '',
                 '        '
                 'return '
                 '(width, '
                 'width)'],
             'pre_context': ['        '
                 'else:',
                 '            '
                 'width, '
                 'height '
                 '= '
                 'self._get_size(self._size, '
                 'self._size)',
                 '            '
                 'return '
                 '(height, '
                 'height)',
                 '',
                 '    '
                 'def '
                 'do_get_preferred_width_for_height(self, '
                 'req_height):'],
             'vars': {'req_height': 82,
               'self': '<cover.ResizeImage '
                 'object '
                 'at '
                 '0x0000016678063e40 '
                 '(quodlibet+qltk+cover+ResizeImage '
                 'at '
                 '0x00000166771a9120)>'}},
             {'abs_path': 'C:/Program '
                'Files/Quod '
                'Libet/lib/python3.8/site-packages/quodlibet/qltk/cover.py',
             'context_line': '        '
                 'pixbuf '
                 '= '
                 'self._get_pixbuf()',
             'filename': 'quodlibet/qltk/cover.py',
             'function': '_get_size',
             'lineno': 154,
             'module': 'quodlibet.qltk.cover',
             'post_context': ['        '
                 'if '
                 'not '
                 'pixbuf:',
                 '            '
                 'return '
                 '0, '
                 '0',
                 '        '
                 'width, '
                 'height '
                 '= '
                 'pixbuf.get_width(), '
                 'pixbuf.get_height()',
                 '        '
                 'return '
                 'calc_scale_size((max_width, '
                 'max_height), '
                 '(width, '
                 'height))',
                 ''],
             'pre_context': ['            '
                 'self._pixbuf '
                 '= '
                 'get_no_cover_pixbuf(max_size, '
                 'max_size)',
                 '',
                 '        '
                 'return '
                 'self._pixbuf',
                 '',
                 '    '
                 'def '
                 '_get_size(self, '
                 'max_width, '
                 'max_height):'],
             'vars': {'max_height': 82,
               'max_width': 300,
               'self': '<cover.ResizeImage '
                 'object '
                 'at '
                 '0x0000016678063e40 '
                 '(quodlibet+qltk+cover+ResizeImage '
                 'at '
                 '0x00000166771a9120)>'}},
             {'abs_path': 'C:/Program '
                'Files/Quod '
                'Libet/lib/python3.8/site-packages/quodlibet/qltk/cover.py',
             'context_line': '            '
                 'self._pixbuf '
                 '= '
                 'thumbnails.get_thumbnail_from_file(',
             'filename': 'quodlibet/qltk/cover.py',
             'function': '_get_pixbuf',
             'lineno': 145,
             'module': 'quodlibet.qltk.cover',
             'post_context': ['                '
                 'self._file, '
                 '(max_size, '
                 'max_size))',
                 '',
                 '        '
                 'if '
                 'not '
                 'self._pixbuf:',
                 '            '
                 'self._pixbuf '
                 '= '
                 'get_no_cover_pixbuf(max_size, '
                 'max_size)',
                 ''],
             'pre_context': ['',
                 '        '
                 'max_size '
                 '= '
                 '256 '
                 '* '
                 'self.get_scale_factor()',
                 '',
                 '        '
                 'self._pixbuf '
                 '= '
                 'None',
                 '        '
                 'if '
                 'self._file:'],
             'vars': {'max_size': 256,
               'self': '<cover.ResizeImage '
                 'object '
                 'at '
                 '0x0000016678063e40 '
                 '(quodlibet+qltk+cover+ResizeImage '
                 'at '
                 '0x00000166771a9120)>'}},
             {'abs_path': 'C:/Program '
                'Files/Quod '
                'Libet/lib/python3.8/site-packages/quodlibet/util/thumbnails.py',
             'context_line': '        '
                 'return '
                 'get_thumbnail(path, '
                 'boundary)',
             'filename': 'quodlibet/util/thumbnails.py',
             'function': 'get_thumbnail_from_file',
             'lineno': 85,
             'module': 'quodlibet.util.thumbnails',
             'post_context': ['    '
                 'except '
                 'GLib.GError:',
                 '        '
                 'try:',
                 '            '
                 'loader '
                 '= '
                 'GdkPixbuf.PixbufLoader()',
                 '            '
                 'loader.set_size(*boundary)',
                 '            '
                 'loader.write(fileobj.read())'],
             'pre_context': ['    '
                 'assert '
                 'fileobj',
                 '',
                 '    '
                 'try:',
                 '        '
                 'path '
                 '= '
                 'fileobj.name',
                 '        '
                 'assert '
                 'isinstance(path, '
                 'fsnative), '
                 'path'],
             'vars': {'boundary': [256,
                   256],
               'fileobj': '<_io.BufferedReader '
                  "name='redacted'>",
               'path': "redacted"}},
             {'abs_path': 'C:/Program '
                'Files/Quod '
                'Libet/lib/python3.8/site-packages/quodlibet/util/thumbnails.py',
             'context_line': '        '
                 'pb '
                 '= '
                 'new_from_file_at_size(thumb_path, '
                 'width, '
                 'height)',
             'filename': 'quodlibet/util/thumbnails.py',
             'function': 'get_thumbnail',
             'lineno': 139,
             'module': 'quodlibet.util.thumbnails',
             'post_context': ['    '
                 'except '
                 'GLib.GError:',
                 '        '
                 '# '
                 'in '
                 'case '
                 'it '
                 'fails '
                 'to '
                 'load, '
                 'we '
                 'recreate '
                 'it',
                 '        '
                 'pass',
                 '    '
                 'else:',
                 '        '
                 'meta_mtime '
                 '= '
                 'pb.get_option("tEXt::Thumb::MTime")'],
             'pre_context': ['        '
                 'mkdir(cache_dir, '
                 '0o700)',
                 '    '
                 'except '
                 'OSError:',
                 '        '
                 'return '
                 'new_from_file_at_size(path, '
                 'width, '
                 'height)',
                 '',
                 '    '
                 'try:'],
             'vars': {'boundary': [256,
                   256],
               'cache_dir': "'C:\\Users\\datakid\\AppData\\Local\\Microsoft\\Windows\\INetCache\\quodlibet\\thumbnails\\large'",
               'height': 256,
               'ignore_temp': True,
               'new_from_file_at_size': 'gi.FunctionInfo(new_from_file_at_size)',
               'path': "'c:\\users\\datakid\\music\\very "
                 'long, '
                 'folder '
                 'name '
                 '& '
                 'with '
                 'odd '
                 '- '
                 "chars\\cover.jpg'",
               'path_mtime': 1621404803.0,
               'thumb_path': "'....AppData\\Local\\Microsoft\\Windows\\INetCache\\quodlibet\\thumbnails\\large\\7305a927d1d261c430f33f43a4dc6309.png'",
               'thumb_size': 256,
               'width': 256}}]},
      'type': 'RuntimeError',
      'value': 'Converting '
         'the '
         'GError '
         'failed'}]},
'extra': {'sys.argv': ("'C:\\Program "
      'Files\\Quod '
      "Libet\\bin\\quodlibet.exe'",)},
'level': 40,
'message': 'RuntimeError: Converting '
   'the GError failed',
'modules': {'python': '3.8.8'},
'platform': 'python',
'project': '142415',
'release': '4.4.0',
'repos': {},
'sdk': {'name': 'raven-python',
  'version': '6.5.0'},
'server_name': 'default',
'tags': {'build_info': '0f66ba2e3',
  'build_type': 'windows',
  'gtk_backend': 'Win32',
  'gtk_version': '3.24.25',
  'mutagen_version': '1.45.1',
  'platform': 'Windows-10-10.0.19041-SP0',
  'pycairo_version': '1.20.0',
  'pygobject_version': '3.38.0',
  'python_version': '3.8.8'},
'time_spent': None,
'timestamp': datetime.datetime(2021, 5, 26, 0, 26, 33, 978395)}
```

Test System
-----------

### Which version of Quod Libet?
4.4.0

### Which operating system 
Win 10, up to date.

Additional Information
----------------------

**Comment by declension** [comment]
Thanks, this is #3579, so merging into that.
