### ISSUE TITLE
[Error] FaultHandlerCrash: Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [quodlibet/quodlibet#3730]
* What did you try to do when the error occurred?

I launched [event 1] QL after the reboot, it shown this stacktrace. Before the reboot, I ran `sudo reboot 0` with QL running at XFCE4 and maybe that's what caused the subsequent (after the reboot) launch [the same event 1] of QL fail with this trace.

Before XFCE4 was installed, QL has been launched a lot of times at MATE DE.

If you need any details, just ask, I am an experienced programmer, I have 5 years of Python 2+3 exp.

Error Details:
```
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/quodlibet/errorreport/faulthandling.py", line 137, in raise_and_clear_error
    raise FaultHandlerCrash(text)

FaultHandlerCrash: Fatal Python error: Segmentation fault

Stack (most recent call first):
  File "/usr/lib/python2.7/dist-packages/quodlibet/_main.py", line 338 in run
  File "/usr/lib/python2.7/dist-packages/quodlibet/main.py", line 193 in main
  File "/usr/bin/quodlibet", line 14 in <module>


Version: 3.9.1
Python: 2.7.17 (default, Feb 27 2021, 15:10:58) 
[GCC 7.5.0]
Platform: Linux-5.4.0-77-generic-x86_64-with-Ubuntu-18.04-bionic

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

CURRENT SESSION'S DE: XFCE4.
OS: UBUNTU-MATE WITH `apt install xubuntu-desktop xfce4-*` and `apt install` (((some xorg drivers))).

used lxde for this session.

```

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
Volume settings after stack trace:

img:

![изображение](https://user-images.githubusercontent.com/19966907/123492612-86d3a880-d609-11eb-954f-4efd451d38d8.png)

("Фиктивный" means, like, "Fake" output)

List of hardware output devices: Empty: 

img:

![изображение](https://user-images.githubusercontent.com/19966907/123492692-bf738200-d609-11eb-95e0-5ef858c19b6a.png)

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
* After that, I rebooted the machine safely once again, with XFCE4 reboot button, then have shut it down with XFCE4 reboot button + powering off during GRUB menu display.

 * After that, I enabled the (non-bluetooth) headphones channel with `alsamixer`.

 * There were still no hardware output devices at the Volume Control GUI.

 * Then, I connected the Bluetooth headphones, their hardware output appeared okay at the Volume Control.

 * Then, QL was playing okay, I was hearing the audo okay.

**Comment by declension** [comment]
Can you narrow down what causes the segfault? Is it something to do with missing output devices?
