### ISSUE TITLE
utils/fifo:FIFO._process can call _open() without required ignore_lock argument.

### ISSUE THREAD

**Issue by mjpieters** [quodlibet/quodlibet#3745]
I'm not 100% yet on how this can be reproduced, just that I've seen this happen locally when using an external process that writes to the named pipe to control QuodLibet. I've not immediately been able to recreate the circumstances, but it appears the pipe was opened and immediately closed again. I've attached the dump log at the bottom of this issue.

The traceback is helpfully short:

```
Traceback (most recent call last):

  File "GLib.py", line 669, in <lambda>

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/util/fifo.py", line 284, in _process
    self._open(*args)

TypeError: _open() missing 1 required positional argument: 'ignore_lock'
```

The fix is simple, just add `True` to the call:

```python
self._open(True, *args)
```

However, there is, from reading the code, another location in the same method that needs fixing; there is no `self.__open()` function, but if `data = source.read()` fails with an `OSError` that is not `EWOULDBLOCK`, `EAGAIN` or `EINTR`, that's what `FIFO._process()` will try and call.

Personally, I'd replace the `ignore_lock` positional argument with a keyword argument (`ignore_lock=False`) and use explicit `_open(*args, ignore_lock=True)` calls, but the immediate fix would be to adjust those two `_open()` calls to use the correct name and argument count.

See https://github.com/quodlibet/quodlibet/blob/66acde05600d7efa1ca214102f59af856b6cf42c/quodlibet/util/fifo.py#L265-L289, the fixed version would be:

```python
    def _process(self, source, condition, *args):
        if condition in (GLib.IO_ERR, GLib.IO_HUP):
            self._open(True, *args)
            return False

        while True:
            try:
                data = source.read()
            except (IOError, OSError) as e:
                if e.errno in (errno.EWOULDBLOCK, errno.EAGAIN):
                    return True
                elif e.errno == errno.EINTR:
                    continue
                else:
                    self._open(True, *args)
                    return False
            break

        if not data:
            self._open(True, *args)
            return False

        self._callback(data)

        return True
```

Test System
-----------

### Which version of Quod Libet?
Quod Libet 4.3.0

### Which operating system 
macos 11.4 (Big Sur)

Additional Information
----------------------

<details>
  <summary>Dump log, click to expand</summary>

=== SYSTEM INFORMATION:
Quod Libet 4.3.0
Mutagen 1.41.1
Python 3.7.1 (default, Feb 12 2020, 19:26:39)
[Clang 7.3.0 (clang-703.0.31)] darwin
Platform Darwin-20.5.0-x86_64-i386-64bit
=== STACK TRACE

Traceback (most recent call last):

  File "GLib.py", line 669, in <lambda>

  File "/Applications/QuodLibet.app/Contents/Resources/lib/python3.7/site-packages/quodlibet/util/fifo.py", line 284, in _process
    self._open(*args)

TypeError: _open() missing 1 required positional argument: 'ignore_lock'

=== LOG:
D: 69.791: player.gstbe.player.__about_to_finish_sync: ..done.
D: 69.791: player.gstbe.player.__about_to_finish: About to finish (async): setting uri
D: 69.792: player.gstbe.player.__about_to_finish: About to finish (async): done
D: 70.825: player.gstbe.player.__message: Stream changed
D: 70.825: GStreamerPlayer._end: End song
D: 70.826: QLScrobbler.plugin_on_song_ended: Checking against filter
D: 70.826: QLSubmitQueue.send_submission: Submitting song(s): Joanna Newsom - This Side of the Blue
D: 70.827: GStreamerPlayer._end: Next song
D: 70.830: util.cover.manager.run: Found local cover from FilesystemCover: <_io.BufferedReader name='/Users/mj/Music/music/Newsom, Joanna/The Milk-Eyed Mender/cover.png'>
D: 71.012: SongFileLibrary._changed(<libraries.SongFileLibrary object at 0x1183e8480 (quodlibet+library+libraries+SongFileLibrary at 0x7faf89745140)>): Changing 2 items.
D: 71.013: library.libraries.__changed: Updating affected albums for 2 items
D: 71.037: QLSubmitQueue._check_submit: Submission status: OK
D: 71.038: QLSubmitQueue.send_nowplaying: Now playing song: Joanna Newsom - "En Gallop"
D: 71.277: QLSubmitQueue._check_submit: Submission status: OK
D: 04.331: config.save: Writing config...
D: 04.353: library.save: Saving all libraries...
D: 77.301: player.gstbe.player.__about_to_finish: About to finish (async)
D: 77.302: player.gstbe.player.__about_to_finish_sync: About to finish (sync)
D: 77.302: player.gstbe.player.__about_to_finish_sync: Select next song in mainloop..
D: 77.302: PlaylistModel.next_ended: Using <In Order>.next_implicit() to get next song
D: 77.302: player.gstbe.player.__about_to_finish_sync: ..done.
D: 77.302: player.gstbe.player.__about_to_finish: About to finish (async): setting uri
D: 77.303: player.gstbe.player.__about_to_finish: About to finish (async): done
D: 78.336: player.gstbe.player.__message: Stream changed
D: 78.336: GStreamerPlayer._end: End song
D: 78.337: QLScrobbler.plugin_on_song_ended: Checking against filter
D: 78.337: QLSubmitQueue.send_submission: Submitting song(s): Joanna Newsom - "En Gallop"
D: 78.338: GStreamerPlayer._end: Next song
D: 78.341: util.cover.manager.run: Found local cover from FilesystemCover: <_io.BufferedReader name='/Users/mj/Music/music/Newsom, Joanna/The Milk-Eyed Mender/cover.png'>
D: 78.510: SongFileLibrary._changed(<libraries.SongFileLibrary object at 0x1183e8480 (quodlibet+library+libraries+SongFileLibrary at 0x7faf89745140)>): Changing 2 items.
D: 78.512: library.libraries.__changed: Updating affected albums for 2 items
D: 78.735: QLSubmitQueue._check_submit: Submission status: OK
D: 78.735: QLSubmitQueue.send_nowplaying: Now playing song: Joanna Newsom - Cassiopeia
D: 78.871: QLSubmitQueue._check_submit: Submission status: OK
D: 77.718: player.gstbe.player.__about_to_finish: About to finish (async)
D: 77.719: player.gstbe.player.__about_to_finish_sync: About to finish (sync)
D: 77.719: player.gstbe.player.__about_to_finish_sync: Select next song in mainloop..
D: 77.719: PlaylistModel.next_ended: Using <In Order>.next_implicit() to get next song
D: 77.719: player.gstbe.player.__about_to_finish_sync: ..done.
D: 77.719: player.gstbe.player.__about_to_finish: About to finish (async): setting uri
D: 77.719: player.gstbe.player.__about_to_finish: About to finish (async): done
D: 78.764: player.gstbe.player.__message: Stream changed
D: 78.764: GStreamerPlayer._end: End song
D: 78.765: QLScrobbler.plugin_on_song_ended: Checking against filter
D: 78.765: QLSubmitQueue.send_submission: Submitting song(s): Joanna Newsom - Cassiopeia
D: 78.766: GStreamerPlayer._end: Next song
D: 78.768: util.cover.manager.run: Found local cover from FilesystemCover: <_io.BufferedReader name='/Users/mj/Music/music/Newsom, Joanna/The Milk-Eyed Mender/cover.png'>
D: 78.906: QLSubmitQueue._check_submit: Submission status: OK
D: 78.906: QLSubmitQueue.send_nowplaying: Now playing song: Joanna Newsom - Peach, Plum, Pear
D: 78.942: SongFileLibrary._changed(<libraries.SongFileLibrary object at 0x1183e8480 (quodlibet+library+libraries+SongFileLibrary at 0x7faf89745140)>): Changing 2 items.
D: 78.943: library.libraries.__changed: Updating affected albums for 2 items
D: 79.128: QLSubmitQueue._check_submit: Submission status: OK
D: 04.335: config.save: Writing config...
D: 04.358: library.save: Saving all libraries...
D: 91.735: player.gstbe.player.__about_to_finish: About to finish (async)
D: 91.736: player.gstbe.player.__about_to_finish_sync: About to finish (sync)
D: 91.736: player.gstbe.player.__about_to_finish_sync: Select next song in mainloop..
D: 91.736: PlaylistModel.next_ended: Using <In Order>.next_implicit() to get next song
D: 91.736: player.gstbe.player.__about_to_finish_sync: ..done.
D: 91.736: player.gstbe.player.__about_to_finish: About to finish (async): setting uri
D: 91.736: player.gstbe.player.__about_to_finish: About to finish (async): done
D: 92.749: player.gstbe.player.__message: Stream changed
D: 92.749: GStreamerPlayer._end: End song
D: 92.749: QLScrobbler.plugin_on_song_ended: Checking against filter
D: 92.750: QLSubmitQueue.send_submission: Submitting song(s): Joanna Newsom - Peach, Plum, Pear
D: 92.751: GStreamerPlayer._end: Next song
D: 92.753: util.cover.manager.run: Found local cover from FilesystemCover: <_io.BufferedReader name='/Users/mj/Music/music/Newsom, Joanna/The Milk-Eyed Mender/cover.png'>
D: 92.897: QLSubmitQueue._check_submit: Submission status: OK
D: 92.897: QLSubmitQueue.send_nowplaying: Now playing song: Joanna Newsom - Swansea
D: 92.917: SongFileLibrary._changed(<libraries.SongFileLibrary object at 0x1183e8480 (quodlibet+library+libraries+SongFileLibrary at 0x7faf89745140)>): Changing 2 items.
D: 92.918: library.libraries.__changed: Updating affected albums for 2 items
D: 93.029: QLSubmitQueue._check_submit: Submission status: OK
D: 32.162: CommandRegistry.handle_line: command: 'status'(*[])
D: 32.162: CommandRegistry.run: Running '_status' with params ()
E: 32.167: errorreport.main.errorhook: fifo.py:284:_process: TypeError: _open() missing 1 required positional argument: 'ignore_lock'%
</details>

**Comment by declension** [comment]
Thanks for the detailed exploration. Would you feel comfortable pushing a fix PR?

**Comment by mjpieters** [comment]
Sure; can you help me get started by giving me a pointer to the relevant test cases? :-)

Also, I'm going to assume that this is all internal implementation detail and not part of the plugin API; I'd be replacing the `ignore_lock` positional argument with a keyword argument: much less confusing when reading the code and less likely to cause similar issues in future.

**Comment by mjpieters** [comment]
I found `tests/test_util_fifo.py`, and possibly `tests/test_remote.py`, PR upcoming.
