### ISSUE TITLE
Error when a playlist file is added via DnD to playlist browser

### ISSUE THREAD

**Issue by TheMelmacian** [quodlibet/quodlibet#3973]
Steps to reproduce
------------------
Open the playlist browser: Browse -> Playlists
Drag and drop an m3u8 playlist file into the browser (or open one via the add button)

Expected Output
---------------
The playlist and all containing (and existing) audio files should be added to the library

Actual Output
-------------
An error is thrown:

```
AttributeError: 'NoneType' object has no attribute 'comma'
------
Traceback (most recent call last):

  File ".../quodlibet/quodlibet/browsers/playlists/main.py", line 430, in __drag_data_received
    playlist = parse_m3u(sock, name,

  File ".../quodlibet/quodlibet/browsers/playlists/util.py", line 61, in parse_m3u
    return __create_playlist(pl_name, _dir_for(filelike), filenames, songs_lib, pl_lib)

  File ".../quodlibet/quodlibet/browsers/playlists/util.py", line 104, in __create_playlist
    return pl_lib.create_from_songs(songs)

  File ".../quodlibet/quodlibet/library/playlist.py", line 84, in create_from_songs
    return XSPFBackedPlaylist.from_songs(

  File ".../quodlibet/quodlibet/util/collection.py", line 629, in from_songs
    title = title or cls.suggested_name_for(songs)

  File ".../quodlibet/quodlibet/util/collection.py", line 352, in suggested_name_for
    len(songs) - 1) % ({'title': songs[0].comma("title"),

AttributeError: 'NoneType' object has no attribute 'comma'
```

This bug masks another bug which occurs after fixing the cause of the above bug:

```
AttributeError: 'NoneType' object has no attribute 'keys'
------
Traceback (most recent call last):

  File ".../quodlibet/quodlibet/qltk/completion.py", line 100, in __update_song
    for tag in song.keys():

AttributeError: 'NoneType' object has no attribute 'keys'
```

which is followed by many other errors till the application freezes

Test System
-----------
QuodLibet 4.5 and master branch

Operating Systems:
- Win10
- openSUSE Tumbleweed

**Comment by declension** [comment]
PR #3974 merged but we can reopen if people find problem persisting

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-SV](https://sentry.io/organizations/quodlibet/issues/2997232171/?referrer=github_plugin)

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-W6](https://sentry.io/organizations/quodlibet/issues/3493625896/?referrer=github_plugin)
