### ISSUE TITLE
Xine player throws TypeError on setup

### ISSUE THREAD

**Issue by edhalter** [quodlibet/quodlibet#3993]
Steps to reproduce
------------------
1. load quodlibet
2. An Error Occurred dialog appears
3. click Ignore Error, attempt to play audio file

Expected Output
---------------
quodlibet loads, allows user to play audio file

Actual Output
-------------
After loading, quodlibet displays error dialog. After ignoring it and attempting to play an audio file, quodlibet segfaults.

Initial error is:
````
File "/usr/lib/python3.9/site-packages/quodlibet/qltk/quodlibetwindow.py", line 1351, in __browser_cb
    player.setup(self.playlist, song, seek_pos, False)

TypeError: XinePlaylistPlayer.setup() takes 4 positional arguments but 5 were given
````
Later, the segfault is:
````
faulthandling.py:138:raise_and_clear_error: quodlibet.errorreport.faulthandling.FaultHandlerCrash: Fatal Python error: Segmentation fault
    
    Stack (most recent call first):
      File "/usr/lib/python3.9/site-packages/quodlibet/player/xinebe/player.py", line 287 in _end
      File "/usr/lib/python3.9/site-packages/quodlibet/player/_base.py", line 305 in go_to
      File "/usr/lib/python3.9/site-packages/quodlibet/qltk/quodlibetwindow.py", line 248 in __select_song
      File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 1680 in main
      File "/usr/lib/python3.9/site-packages/quodlibet/_main.py", line 385 in run
      File "/usr/lib/python3.9/site-packages/quodlibet/main.py", line 203 in main
      File "/usr/lib/python-exec/python3.9/quodlibet", line 14 in <module>
````

Test System
-----------

### Which version of Quod Libet?
4.5.0

### Which operating system 
Gentoo Linux

### If it's audio-related, what back-end?
N/A

Additional Information
----------------------
Happens in both python 3.9 and 3.10. The faulty code was seemingly introduced in quodlibet/qltk/quodlibetwindow.py in [this commit](https://github.com/quodlibet/quodlibet/commit/a5c7a1e0a1db2b70f2cbf63f76ac765846cfe1b5) on 2022/3/28. It added a 4th argument (False) in its call to XinePlaylistPlayer.setup(). However, that method (I believe in quodlibet/player/xinebe/player.py) only has 3 parameters (plus self). ~~Editing quodlibetwindow.py to get rid of the 4th parameter gets rid of the bug.~~ Never mind -- that doesn't work.

**Comment by stainesa** [comment]
confirmed - error message is 

TypeError: setup() takes 4 positional arguments but 5 were given
------
Traceback (most recent call last):

  File "/usr/lib/python3.9/site-packages/quodlibet/qltk/quodlibetwindow.py", line 1351, in __browser_cb
    player.setup(self.playlist, song, seek_pos, False)

TypeError: setup() takes 4 positional arguments but 5 were given

**Comment by declension** [comment]
Sentry issue: [QUODLIBET-TY](https://sentry.io/organizations/quodlibet/issues/3251595768/?referrer=github_plugin)
