### ISSUE TITLE
Rename folders instead of creating new ones when moving files

### ISSUE THREAD

**Issue by Kaerheern** [quodlibet/quodlibet#4035]
The proposed change
-------------------

As far as I have observed, if I want to rename files **and** move them to a desired path, QuodLibet's "Rename Files" tab does so by creating a new folder when moving the files to that folder. 

As thing stand, if QuodLibet tries to move files from a folder with a name that is too long to a new one (that is more or less just as long), it'll immediately crash, showing the following error:

> error: bad character range A-1 at position 28
> ------
> Traceback (most recent call last):
> 
>   File "/app/lib/python3.9/site-packages/quodlibet/util/__init__.py", line 712, in wrap
>     return handler(that, *args)
> 
>   File "/app/lib/python3.9/site-packages/quodlibet/qltk/renamefiles.py", line 361, in _rename
>     self._moveart(moveart_sets, old_pathfile, new_pathfile, song)
> 
>   File "/app/lib/python3.9/site-packages/quodlibet/qltk/renamefiles.py", line 417, in _moveart
>     moves.extend(f for f in glob.glob(fn)
> 
>   File "/usr/lib/python3.9/glob.py", line 22, in glob
>     return list(iglob(pathname, recursive=recursive))
> 
>   File "/usr/lib/python3.9/glob.py", line 74, in _iglob
>     for dirname in dirs:
> 
>   File "/usr/lib/python3.9/glob.py", line 74, in _iglob
>     for dirname in dirs:
> 
>   File "/usr/lib/python3.9/glob.py", line 75, in _iglob
>     for name in glob_in_dir(dirname, basename, dironly):
> 
>   File "/usr/lib/python3.9/glob.py", line 86, in _glob1
>     return fnmatch.filter(names, pattern)
> 
>   File "/usr/lib/python3.9/fnmatch.py", line 58, in filter
>     match = _compile_pattern(pat)
> 
>   File "/usr/lib/python3.9/fnmatch.py", line 52, in _compile_pattern
>     return re.compile(res).match
> 
>   File "/usr/lib/python3.9/re.py", line 252, in compile
>     return _compile(pattern, flags)
> 
>   File "/usr/lib/python3.9/re.py", line 304, in _compile
>     p = sre_compile.compile(pattern, flags)
> 
>   File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
>     p = sre_parse.parse(p, flags)
> 
>   File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
>     p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
> 
>   File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
>     itemsappend(_parse(source, state, verbose, nested + 1,
> 
>   File "/usr/lib/python3.9/sre_parse.py", line 834, in _parse
>     p = _parse_sub(source, state, sub_verbose, nested + 1)
> 
>   File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
>     itemsappend(_parse(source, state, verbose, nested + 1,
> 
>   File "/usr/lib/python3.9/sre_parse.py", line 598, in _parse
>     raise source.error(msg, len(this) + 1 + len(that))
> 
> re.error: bad character range A-1 at position 28
> 

Although I've noticed that renaming folders temporarily to something very short, such a string of numbers (1, 2, 3...), does not result in a crash, I believe it'd be more beneficial if QuodLibet instead renamed the source folder the files are on. 

**Example:**

If the target folder were to be in the same parent directory as the source folder.

> Music/Elvis Presley/Elvis Presley - (2015) Greatest Hits {Sony Music Entertainment 3195827578} (2012) [CD 16-44100] [FLAC]

To

> Music/Elvis Presley/Elvis Presley - (2015) Greatest Hits {Sony Music Entertainment & United Artists 3195827578} (2012) [CD 16-44100] [FLAC]

Action: Rename the folder. 

**Example:**

If the target folder were to be outside the parent directory the source folder is in.

> Music/Elvis Presley/Elvis Presley - (2015) Greatest Hits {Sony Music Entertainment 3195827578} (2012) [CD 16-44100] [FLAC]

To

> Music/Elvis Presley & His Orchestra/Elvis Presley - (2015) Greatest Hits {Sony Music Entertainment 3195827578} (2012) [CD 16-44100] [FLAC]

Action: Rename the folder and move it to the desired path.

Benefits of this change
-----------------------

1. It should fix any crashes related to the length of the folder's name when renaming it. It doesn't make sense to create a whole new folder just because one tag value was changed (bad capitalization, mistakes made during tagging), when we could just rename the folder and avoid all that hassle.

2. It would inadvertently fix any issues related to moving non-music files along with music files, since we'd no longer be creating new folders, ergo all files would remain inside it. That is, as long as the source folder remains inside the same parent directory. I am aware there's no such love towards non-music files (I am forced to move them manually) but this change would, nevertheless, save us a lot of time by simply renaming the folders, instead of creating new ones.

Any issues this might cause
---------------------------

None, although it might be quite the challenge to introduce this new feature, in which QuodLibet would now handle folders by renaming them instead of creating new ones.

**Comment by Ironbalden** [comment]
This idea works only on the assumption that every item inside the folder has to move, and that assumption might not be true. Touching files not requested by the user can cause serious issues and should be avoided. As an example if I'm fixing a song actually residing in my download folder, if i simply rename the folder my whole downloaded files move with it.

**Comment by Kaerheern** [comment]
> This idea works only on the assumption that every item inside the folder has to move, and that assumption might not be true. Touching files not requested by the user can cause serious issues and should be avoided. As an example if I'm fixing a song actually residing in my download folder, if i simply rename the folder my whole downloaded files move with it.

I can understand your use case if, for some reason, you're more fond of pouring every track into the Downloads folder first, and then move them from there. However, some people, myself included, are already pretty careful, so the album in question is already located in its respective "C:\Music\Artist\Album" folder, without interfering with any other files. 

This change would still be significantly more beneficial in the long-term, saving many headaches derived from QuodLibet being unable to handle long folder names and crashing every time as a result, as well as the fact that, in its current state, it finds itself incapable to move non-music files. It could always be made into a toggable option disabled by default.

**Comment by declension** [comment]
> many headaches derived from QuodLibet being unable to handle long folder names and crashing every time as a result

This is definitely not my experience. Anyway, sounds like a bug that should just be fixed. @Kaerheern could you either convert this issue to be _that_, or split this into a new Bug Report (it's also not clear whether this is a Windows-only problem as your talks of `C:\` so please include system details). Thanks!

**Comment by Kaerheern** [comment]
> > many headaches derived from QuodLibet being unable to handle long folder names and crashing every time as a result
> 
> @Kaerheern could you either convert this issue to be _that_, or split this into a new Bug Report.

Yes, of course. This my first time doing this, but I assume you need me to edit the issue when you say that I must "convert" it?

> (it's also not clear whether this is a Windows-only problem as your talks of `C:\` so please include system details)
That was my mistake, I wanted to show a basic example, and I thought of Windows since most people use it. I'll update the issue with the Linux distro I'm using.
