### ISSUE TITLE
Quodlibet not working on Kubuntu 22.04

### ISSUE THREAD

**Issue by theFOAD** [quodlibet/quodlibet#4114]
Steps to reproduce
------------------

Install quodlibet using apt-get on a fresh Kubuntu 22.04.

Expected Output
---------------

quodlibet should then work.

Actual Output
-------------

It didn't work, only tell me this:

** (io.github.quodlibet.QuodLibet:168674): WARNING **: 20:50:01.389: Binding 'XF86AudioPrev' failed!

** (io.github.quodlibet.QuodLibet:168674): WARNING **: 20:50:01.389: Binding 'XF86AudioNext' failed!

** (io.github.quodlibet.QuodLibet:168674): WARNING **: 20:50:01.390: Binding 'XF86AudioStop' failed!

** (io.github.quodlibet.QuodLibet:168674): WARNING **: 20:50:01.390: Binding 'XF86AudioPlay' failed!

** (io.github.quodlibet.QuodLibet:168674): WARNING **: 20:50:01.390: Binding 'XF86AudioRepeat' failed!

** (io.github.quodlibet.QuodLibet:168674): WARNING **: 20:50:01.391: Binding 'XF86AudioRandomPlay' failed!
E: 11.181: errorreport.main.errorhook:
    faulthandling.py:138:raise_and_clear_error: quodlibet.errorreport.faulthandling.FaultHandlerCrash: Fatal Python error: Segmentation fault
    
    
    Extension modules: gi._gi, cairo._cairo, gi._gi_cairo, _dbus_bindings, _dbus_glib_bindings, simplejson._speedups, tornado.speedups (total: 7)

Test System
-----------

### Which version of Quod Libet?

4.5.0

### Which operating system 

Kubuntu 22.04

### If it's audio-related, what back-end?

Additional Information
----------------------

**Comment by elcste** [comment]
What do you see running `apt list -a quodlibet`? The versions for Ubuntu 22.04 should be `4.4.0-2` or `4.4.0-2ubuntu0.1` (https://packages.ubuntu.com/search?keywords=quodlibet), so I surprised you have 4.5 without installing in some other way.

**Comment by theFOAD** [comment]
Hi, thanks for your reply.  This is what I get.

root@diana:~# apt list -a quodlibet
Listing... Done
quodlibet/jammy,jammy,now 4.5.0-0~ppa0~jammy all [installed]
quodlibet/jammy-updates,jammy-updates 4.4.0-2ubuntu0.1 all
quodlibet/jammy,jammy 4.4.0-2 all

**Comment by elcste** [comment]
Looks like you have a version from a PPA. Personally, I'd remove the PPA and use either

- the 4.4 version that is available for Ubuntu 22.04 or
- the 4.5 version from Ubuntu 22.10, by downloading and manually installing the deb file: https://packages.ubuntu.com/kinetic/all/quodlibet/download

**Comment by theFOAD** [comment]
Hello,

I removed the ppa and reinstalled quodlibet from 22.04. I still get the same errors.

root@diana:~# apt list -a quodlibet
Listing... Done
quodlibet/jammy-updates,jammy-updates,now 4.4.0-2ubuntu0.1 all [installed]
quodlibet/jammy,jammy 4.4.0-2 all

**Comment by elcste** [comment]
Hmm, I'm not sure then. These standard packages have been working for me, but I've been using Ubuntu with GNOME and Sway environments, not Kubuntu.

Maybe the QL developers have a better idea what the problem is.

**Comment by declension** [comment]
Hard to say with segfaults. It's typically a dependent library issue, but that doesn't narrow it down much.

@theFOAD did you `apt remove quodlibet --purge` (having taken a backup of `~/.quodlibet/` etc?

Failing that or some other trial and error it might be `gdb` time but don't ask me I'm afraid. Some ideas on https://stackoverflow.com/questions/2663841/python-tracing-a-segmentation-fault if you're feeling brave...

**Comment by petitminion** [comment]
same problem here but only with some files 
```
FaultHandlerCrash: Fatal Python error: Segmentation fault
------
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/quodlibet/errorreport/faulthandling.py", line 138, in raise_and_clear_error
    raise FaultHandlerCrash(text)

quodlibet.errorreport.faulthandling.FaultHandlerCrash: Fatal Python error: Segmentation fault


Extension modules: gi._gi, cairo._cairo, gi._gi_cairo, _dbus_bindings, _dbus_glib_bindings, _brotli (total: 6)

```

**Comment by petitminion** [comment]
deactivating "MusicBrainz Cover Source " pluging resolve this issue for me

**Comment by afontenot** [comment]
> deactivating "MusicBrainz Cover Source " pluging resolve this issue for me

Can you upload a file that causes a crash and link to it here?

**Comment by petitminion** [comment]
```
{'event_id': '47b681bbd4e1407ba95ccab3ebfd3277',
'exception': {'values': [{'module': 'quodlibet.errorreport.faulthandling',
      'stacktrace': {'frames': [{'abs_path': '/usr/lib/python3/dist-packages/quodlibet/errorreport/faulthandling.py',
             'context_line': '            '
                 'raise '
                 'FaultHandlerCrash(text)',
             'filename': 'quodlibet/errorreport/faulthandling.py',
             'function': 'raise_and_clear_error',
             'lineno': 138,
             'module': 'quodlibet.errorreport.faulthandling',
             'post_context': ['',
                 '',
                 'def '
                 'crash():',
                 '    '
                 '"""Makes '
                 'the '
                 'process '
                 'segfault. '
                 'For '
                 'testing '
                 'purposes"""',
                 ''],
             'pre_context': ['        '
                 '_fileobj.truncate()',
                 '    '
                 'except '
                 'IOError:',
                 '        '
                 'print_exc()',
                 '    '
                 'else:',
                 '        '
                 'if '
                 'text:'],
             'vars': {'text': "'Fatal "
                 'Python '
                 'error: '
                 'Aborted\n'
                 '\n'
                 '\n'
                 'Extension '
                 'modules: '
                 'gi._gi, '
                 'cairo._cairo, '
                 'gi._gi_cairo, '
                 '_dbus_bindings, '
                 '_dbus_glib_bindings, '
                 '_brotli '
                 '(total: '
                 "6)'"}}]},
      'type': 'FaultHandlerCrash',
      'value': 'Fatal '
         'Python '
         'error: '
         'Aborted\n'
         '\n'
         '\n'
         'Extension '
         'modules: '
         'gi._gi, '
         'cairo._cairo, '
         'gi._gi_cairo, '
         '_dbus_bindings, '
         '_dbus_glib_bindings, '
         '_brotli '
         '(total: '
         '6)'}]},
'extra': {'sys.argv': ("'/usr/bin/quodlibet'",
      "'--run'",
      "'--play-file'")},
'fingerprint': ['{{ default }}', ''],
'level': 40,
'message': 'FaultHandlerCrash: Fatal '
   'Python error: Aborted\n'
   '\n'
   '\n'
   'Extension modules: '
   'gi._gi, cairo._cairo, '
   'gi._gi_cairo, '
   '_dbus_bindings, '
   '_dbus_glib_bindings, '
   '_brotli (total: 6)',
'modules': {'python': '3.10.6'},
'platform': 'python',
'project': '142415',
'release': '4.5.0',
'repos': {},
'sdk': {'name': 'raven-python',
  'version': '6.5.0'},
'server_name': 'default',
'tags': {'build_info': 'NONE',
  'build_type': 'default',
  'gtk_backend': 'X11',
  'gtk_version': '3.24.33',
  'mutagen_version': '1.45.1',
  'platform': 'Linux-5.15.0-48-generic-x86_64-with-glibc2.35',
  'pycairo_version': '1.20.1',
  'pygobject_version': '3.42.1',
  'python_version': '3.10.6'},
'time_spent': None,
'timestamp': datetime.datetime(2022, 10, 4, 10, 56, 9, 805701)}
```

[La Varda - Les Chemins De L'Errance... - 02 - Voyage 5 (Klezmer)](https://audio.gafamfree.party/library/tracks/840/)

**Comment by raydeepx** [comment]
this is test result from master branch on 22.04 

```
./setup.py test
running test
<frozen importlib._bootstrap>:914: ImportWarning: RedirectImportHook.find_spec() not found; falling back to find_module()
================================================ test session starts =================================================
platform linux -- Python 3.10.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
rootdir: /assets/build/quodlibet, configfile: setup.cfg
collected 4595 items / 1 skipped / 4594 selected                                                                     

tests/test___init__.py .....                                                                                   [  0%]
tests/test_appdata_files.py ssss                                                                               [  0%]
tests/test_browsers___init__.py .........                                                                      [  0%]
tests/test_browsers__base.py Fatal Python error: Aborted

Thread 0x00007fa655499640 (most recent call first):
  File "/usr/lib/python3.10/socket.py", line 833 in create_connection
  File "/usr/lib/python3.10/http/client.py", line 941 in connect
  File "/usr/lib/python3.10/http/client.py", line 1447 in connect
  File "/usr/lib/python3.10/http/client.py", line 975 in send
  File "/usr/lib/python3.10/http/client.py", line 1037 in _send_output
  File "/usr/lib/python3.10/http/client.py", line 1277 in endheaders
  File "/usr/lib/python3.10/http/client.py", line 1328 in _send_request
  File "/usr/lib/python3.10/http/client.py", line 1282 in request
  File "/usr/lib/python3.10/urllib/request.py", line 1348 in do_open
  File "/usr/lib/python3.10/urllib/request.py", line 1391 in https_open
  File "/usr/lib/python3.10/urllib/request.py", line 496 in _call_chain
  File "/usr/lib/python3.10/urllib/request.py", line 536 in _open
  File "/usr/lib/python3.10/urllib/request.py", line 519 in open
  File "/usr/lib/python3.10/urllib/request.py", line 216 in urlopen
  File "/assets/build/quodlibet/quodlibet/qltk/x.py", line 458 in _fetch_image
  File "/assets/build/quodlibet/quodlibet/util/thread.py", line 71 in wrap
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58 in run
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 83 in _worker
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007fa655c9a640 (most recent call first):
  File "/usr/lib/python3.10/socket.py", line 833 in create_connection
  File "/usr/lib/python3.10/http/client.py", line 941 in connect
  File "/usr/lib/python3.10/http/client.py", line 1447 in connect
  File "/usr/lib/python3.10/http/client.py", line 975 in send
  File "/usr/lib/python3.10/http/client.py", line 1037 in _send_output
  File "/usr/lib/python3.10/http/client.py", line 1277 in endheaders
  File "/usr/lib/python3.10/http/client.py", line 1328 in _send_request
  File "/usr/lib/python3.10/http/client.py", line 1282 in request
  File "/usr/lib/python3.10/urllib/request.py", line 1348 in do_open
  File "/usr/lib/python3.10/urllib/request.py", line 1391 in https_open
  File "/usr/lib/python3.10/urllib/request.py", line 496 in _call_chain
  File "/usr/lib/python3.10/urllib/request.py", line 536 in _open
  File "/usr/lib/python3.10/urllib/request.py", line 519 in open
  File "/usr/lib/python3.10/urllib/request.py", line 216 in urlopen
  File "/assets/build/quodlibet/quodlibet/qltk/x.py", line 458 in _fetch_image
  File "/assets/build/quodlibet/quodlibet/util/thread.py", line 71 in wrap
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58 in run
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 83 in _worker
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007fa65659a640 (most recent call first):
  File "/usr/lib/python3.10/ssl.py", line 1130 in read
  File "/usr/lib/python3.10/ssl.py", line 1274 in recv_into
  File "/usr/lib/python3.10/socket.py", line 705 in readinto
  File "/usr/lib/python3.10/http/client.py", line 279 in _read_status
  File "/usr/lib/python3.10/http/client.py", line 318 in begin
  File "/usr/lib/python3.10/http/client.py", line 1374 in getresponse
  File "/usr/lib/python3.10/urllib/request.py", line 1352 in do_open
  File "/usr/lib/python3.10/urllib/request.py", line 1391 in https_open
  File "/usr/lib/python3.10/urllib/request.py", line 496 in _call_chain
  File "/usr/lib/python3.10/urllib/request.py", line 536 in _open
  File "/usr/lib/python3.10/urllib/request.py", line 519 in open
  File "/usr/lib/python3.10/urllib/request.py", line 216 in urlopen
  File "/assets/build/quodlibet/quodlibet/qltk/x.py", line 458 in _fetch_image
  File "/assets/build/quodlibet/quodlibet/util/thread.py", line 71 in wrap
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58 in run
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 83 in _worker
  File "/usr/lib/python3.10/threading.py", line 953 in run
  File "/usr/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 973 in _bootstrap

Thread 0x00007fa66a6cb000 (most recent call first):
  File "/assets/build/quodlibet/quodlibet/qltk/views.py", line 651 in on_selection_changed
  File "/assets/build/quodlibet/quodlibet/qltk/songlist.py", line 735 in set_model
  File "/assets/build/quodlibet/quodlibet/qltk/views.py", line 878 in without_model

Extension modules: gi._gi, cairo._cairo, gi._gi_cairo, _dbus_bindings, _dbus_glib_bindings, _brotli (total: 6)
Aborted
```

**Comment by raydeepx** [comment]
i can run app but it crash on some flac's, some works fine some crash

**Comment by declension** [comment]
Ah if it's FLACs - have you seen #4197 and #4196? What version of libFLAC do you have?

**Comment by raydeepx** [comment]
dpkg -l | grep libflac
ii  libflac++6v5:amd64                            1.3.3-2build2                                                        amd64     
ii  libflac8:amd64                                1.3.3-2build2                                                        amd64

**Comment by gjedeer** [comment]
I'm having the same issue with xubuntu 22.04. Happens with distro-packaged 4.4.0 as well as 4.5.0 downloaded from github. 

```
$ quodlibet-4.5.0 gdb python3
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...
(No debugging symbols found in python3)
(gdb) run quodlibet.py
Starting program: /usr/bin/python3 quodlibet.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3e54640 (LWP 47818)]
[New Thread 0x7ffff3653640 (LWP 47819)]
[New Thread 0x7fffe9e30640 (LWP 47821)]
[Thread 0x7fffe9e30640 (LWP 47821) exited]
[New Thread 0x7fffe9e30640 (LWP 47822)]
[New Thread 0x7fffe9522640 (LWP 47823)]
[Thread 0x7fffe9e30640 (LWP 47822) exited]
[New Thread 0x7fffe9e30640 (LWP 47824)]
[Thread 0x7fffe9e30640 (LWP 47824) exited]
[Thread 0x7fffe9522640 (LWP 47823) exited]
[New Thread 0x7fffe9522640 (LWP 47825)]
[New Thread 0x7fffe9e30640 (LWP 47826)]
[Thread 0x7fffe9522640 (LWP 47825) exited]
[Thread 0x7fffe9e30640 (LWP 47826) exited]
[New Thread 0x7fffe9e30640 (LWP 47827)]
[New Thread 0x7fffe9522640 (LWP 47828)]
[Thread 0x7fffe9522640 (LWP 47828) exited]
[New Thread 0x7fffe9522640 (LWP 47829)]
[New Thread 0x7fffc3fff640 (LWP 47830)]
[New Thread 0x7fffc37fe640 (LWP 47831)]
[New Thread 0x7fffc2ffd640 (LWP 47832)]
[Thread 0x7fffc37fe640 (LWP 47831) exited]
[Thread 0x7fffc2ffd640 (LWP 47832) exited]
[New Thread 0x7fffc2ffd640 (LWP 47833)]

** (io.github.quodlibet.QuodLibet:47815): WARNING **: 09:37:55.151: Binding 'XF86AudioPrev' failed!

** (io.github.quodlibet.QuodLibet:47815): WARNING **: 09:37:55.151: Binding 'XF86AudioNext' failed!

** (io.github.quodlibet.QuodLibet:47815): WARNING **: 09:37:55.151: Binding 'XF86AudioStop' failed!

** (io.github.quodlibet.QuodLibet:47815): WARNING **: 09:37:55.151: Binding 'XF86AudioPlay' failed!

** (io.github.quodlibet.QuodLibet:47815): WARNING **: 09:37:55.151: Binding 'XF86AudioRepeat' failed!

** (io.github.quodlibet.QuodLibet:47815): WARNING **: 09:37:55.151: Binding 'XF86AudioRandomPlay' failed!
[New Thread 0x7fffc37fe640 (LWP 47836)]
[New Thread 0x7fffc1bff640 (LWP 47837)]
[Thread 0x7fffc37fe640 (LWP 47836) exited]
[Thread 0x7fffc1bff640 (LWP 47837) exited]
[New Thread 0x7fffc1bff640 (LWP 47838)]
[New Thread 0x7fffc37fe640 (LWP 47839)]
[Thread 0x7fffc37fe640 (LWP 47839) exited]
[Thread 0x7fffc1bff640 (LWP 47838) exited]
[New Thread 0x7fffc1bff640 (LWP 47840)]
[New Thread 0x7fffc37fe640 (LWP 47841)]
[Thread 0x7fffc1bff640 (LWP 47840) exited]
[Thread 0x7fffc37fe640 (LWP 47841) exited]
[New Thread 0x7fffc37fe640 (LWP 47842)]

Thread 10 "pool-io.github." received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe9e30640 (LWP 47827)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737117357632) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt full
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737117357632) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7fffe9e30640
        old_mask = {__val = {140737087723556, 0, 0, 28548224099773696, 0, 0, 2305878331563712544, 9042521604759584, 93825011755088, 93825011755088, 4607182418800017408, 0, 4608315376411869184, 0, 4602678819172665918, 14859171818800728320}}
        ret = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140737117357632) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737117357632, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007ffff7c287f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 0, 0, 16, 72340172838076673, 72340172838076673, 770, 0, 0, 0, 0, 0, 0, 0, 0, 0}}, sa_flags = 0, sa_restorer = 0x0}
        sigs = {__val = {32, 140737299679373, 0, 0, 2, 9223372036854775814, 0, 0, 0, 0, 16, 72340172838076673, 72340172838076673, 770, 0, 0}}
#5  0x00007ffff52a26b2 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff52ad8df in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff52ada07 in __gxx_personality_v0 () at /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff4c10fe9 in __libunwind_Unwind_Resume () at /lib/x86_64-linux-gnu/libunwind.so.8
#9  0x00007fffe81ed86d in  () at /lib/x86_64-linux-gnu/libproxy.so.1
#10 0x00007fffe81f6827 in px_proxy_factory_get_proxies () at /lib/x86_64-linux-gnu/libproxy.so.1
#11 0x00007fffe8584827 in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
#12 0x00007ffff6a53194 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x00007ffff6cd66b4 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff6cd3a51 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff7c94b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>

                      unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737488339264, 4166981140195589135, 140737117357632, 0, 140737350551632, 140737488339616, -4167020971672454129, -4166963430489703409}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--c
#16 0x00007ffff7d26a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

Plugins active at the moment of crash:

```
active_plugins = refresh-songs
    follow
    ReplayGain
    Tray Icon
    Download Album Art
    lastfm-cover
    Download Cover Art
```

Deleting the active_plugins section from config helped with the problem. I wanted to bisect to find the problematic plugin but started running into all sorts of config file parsing errors so I gave up.

**Comment by declension** [comment]
See probably-related  #4251

**Comment by gjedeer** [comment]
@declension  I just tried enabling Last.fm cover art plugin, playing a track without cover art, restarting quodlibet, everything worked as expected. Same with Discogs cover art. So that's not related

**Comment by declension** [comment]
So @gjedeer your problem could be related to this [Debian-reported Gstreamer bug]( https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1029618) leading to https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/issues/1008 but hard to say. Definitely similar stack traces there.

**Comment by declension** [comment]
@gjedeer @raydeepx  @petitminion  @theFOAD If you are comfortable doing so, please try the libsoup3 upgrade branch in development:

```shell
git clone https://github.com/quodlibet/quodlibet.git --depth 1
cd quodlibet
git checkout move-to-libsoup3
pip install --user poetry
poetry install
poetry run /.quodlibet.py --debug
```
