### ISSUE TITLE
can't add files to ql

### ISSUE THREAD

**Issue by Bob-gt** [quodlibet/quodlibet#4181]
Steps to reproduce
------------------
Tried to add files

Expected Output
---------------
Files should appear in the tracklist.

Actual Output
-------------
Nothing

Test System
-----------

### Which version of Quod Libet?

4.5.0
### Which operating system 
 Mint 20

### If it's audio-related, what back-end?

Additional Information
----------------------
This happened after I connected to soundcloud. Not sure if it's related.
The only other tracks in QL were added by folders from ripped discs.

**Comment by afontenot** [comment]
> The only other tracks in QL were added by folders from ripped discs before using SC. (update) I just tried adding folder and two of the files were added but the other two were not. The two files added were fron Soundcloud, the two other files that weren't added are from Youtube.

It sounds like some files are being added, but not others. Can you provide an example of a file that isn't working - e.g. what format is it (mp3, ogg, etc), how are you trying to add it? More detailed reproduction steps would be helpful here. Can you still import ripped discs after connecting to Soundcloud?

**Comment by bothesven** [comment]
I am seeing the same issue. 
I have .ogg and .wav files in ~/tmp. After I add the folder, I see the .ogg files in QL, but not the .wav files.
Trying to explicitly add one of the wav's has no apparent effect.

**Comment by bothesven** [comment]
- I am not aware of any global filters.
- The files do **not** have any tags. (The mp3 files don't have tags either, but they are shown.)
- In Paned Browser, I added the "Full Name" column and sorted by it to find my files by folder.


This is the error I get with debug logging when trying to add one of the .wav files:

W: 66.095: formats._misc.MusicFile: Error loading '/home/sven/tmp/FlussBKPrough1004b.wav'
E: 66.095: formats._misc.MusicFile:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/quodlibet/formats/_misc.py", line 45, in translate_errors
        yield
      File "/usr/lib/python3.10/site-packages/quodlibet/formats/wav.py", line 27, in __init__
        f = wave.open(h)
      File "/usr/lib/python3.10/wave.py", line 509, in open
        return Wave_read(f)
      File "/usr/lib/python3.10/wave.py", line 163, in __init__
        self.initfp(f)
      File "/usr/lib/python3.10/wave.py", line 143, in initfp
        self._read_fmt_chunk(chunk)
      File "/usr/lib/python3.10/wave.py", line 268, in _read_fmt_chunk
        raise Error('unknown format: %r' % (wFormatTag,))
    wave.Error: unknown format: 3
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/quodlibet/formats/_misc.py", line 114, in MusicFile
        return loader(filename)
      File "/usr/lib/python3.10/site-packages/quodlibet/formats/wav.py", line 25, in __init__
        with translate_errors():
      File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
        self.gen.throw(typ, value, traceback)
      File "/usr/lib/python3.10/site-packages/quodlibet/formats/_misc.py", line 51, in translate_errors
        reraise(MutagenBug, e)
      File "/usr/lib/python3.10/site-packages/quodlibet/util/__init__.py", line 1151, in reraise
        raise tp(value).with_traceback(tb)
      File "/usr/lib/python3.10/site-packages/quodlibet/formats/_misc.py", line 45, in translate_errors
        yield
      File "/usr/lib/python3.10/site-packages/quodlibet/formats/wav.py", line 27, in __init__
        f = wave.open(h)
      File "/usr/lib/python3.10/wave.py", line 509, in open
        return Wave_read(f)
      File "/usr/lib/python3.10/wave.py", line 163, in __init__
        self.initfp(f)
      File "/usr/lib/python3.10/wave.py", line 143, in initfp
        self._read_fmt_chunk(chunk)
      File "/usr/lib/python3.10/wave.py", line 268, in _read_fmt_chunk
        raise Error('unknown format: %r' % (wFormatTag,))
    quodlibet.formats._misc.MutagenBug: unknown format: 3

---

I am going the attach the complete log. For adding the whole folder you can see this error three times for the three wav's in it. (And there are apparently also a couple other errors for other songs in my library.)
[ql_debug.zip](https://github.com/quodlibet/quodlibet/files/11254075/ql_debug.zip)

**Comment by declension** [comment]
Thanks. Yes so it's a WAV file with unsupported tags. In fact I think it's BWF - see #3667
