### ISSUE TITLE
Creating a playlist with a name ending in a slash results in a TypeError

### ISSUE THREAD

**Issue by scresante** [quodlibet/quodlibet#4218]
This is seems to be a result of how the `name_for` method is using splitext(). 

## To Reproduce:

Create a new playlist with a name ending in a / (such as a/b/)

## Expected Result: 

Create a playlist with the filename of a%2Fb%2F.xspf

### Which version of Quod Libet?

[3df7f6e](https://github.com/quodlibet/quodlibet/commit/3df7f6e416851b7675968f3972da92a7fb4af10d)

### Which operating system 
arch

Additional Information
----------------------
```
Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/quodlibet/browsers/playlists/menu.py", line 47, in _on_new_playlist_activate
        return self.pl_lib.create_from_songs(songs, title=title)
      File "/usr/lib/python3.10/site-packages/quodlibet/library/playlist.py", line 108, in create_from_songs
        return XSPFBackedPlaylist.from_songs(
      File "/usr/lib/python3.10/site-packages/quodlibet/util/collection.py", line 632, in from_songs
        playlist = cls.new(dir_, title, songs_lib=songs_lib, pl_lib=pl_lib)
      File "/usr/lib/python3.10/site-packages/quodlibet/util/collection.py", line 622, in new
        return cls(dir_, fn, songs_lib=songs_lib, pl_lib=pl_lib, validate=True)
      File "/usr/lib/python3.10/site-packages/quodlibet/util/collection.py", line 572, in __init__
        name = self.name_for(filename)
      File "/usr/lib/python3.10/site-packages/quodlibet/util/collection.py", line 767, in name_for
        raise TypeError(f"XSPFs should end in '{cls.EXT}', not {ext}")
    TypeError: XSPFs should end in 'xspf', not
    ```

**Comment by declension** [comment]
Reproduced, but only if you create the playlist from the songlist context menu; normal creation in the playlists browser does it properly
