### ISSUE TITLE
cli --play-file crashes (4.6.1

### ISSUE THREAD

**Issue by davidSchlosser** [quodlibet/quodlibet#4240]
Steps to reproduce
------------------
quodlibet/quodlibet.py --play-file='/media/david/StarTechcom8Tb/qlMusic/Another/track1.mp3'

Expected Output
---------------
file should start playing as in previous versions

Actual Output
-------------
$ quodlibet/quodlibet.py --play-file='/media/david/StarTechcom8Tb/qlMusic/Another/track1.mp3'
Traceback (most recent call last):
  File "/home/david/quodlibet/quodlibet.py", line 14, in <module>
    sys.exit(main())
  File "/home/david/quodlibet/quodlibet/main.py", line 31, in main
    startup_actions, cmds_todo = process_arguments(argv)
  File "/home/david/quodlibet/quodlibet/cli.py", line 254, in process_arguments
    filename = os.path.abspath(util.path.expanduser(arg))
AttributeError: module 'quodlibet.util.path' has no attribute 'expanduser'

Test System
-----------

### Which version of Quod Libet?
4.6.1

### Which operating system 
Ubuntu 22.04

### If it's audio-related, what back-end?
n/a

Additional Information
----------------------
david@david-NUC10i7FNH:~$ quodlibet/quodlibet.py --version
Quod Libet 4.6.-1
<quod-libet-development@googlegroups.com>
Copyright 2004-2022
david@david-NUC10i7FNH:~$ quodlibet/quodlibet.py --play-file='/media/david/StarTechcom8Tb/qlMusic/Another/track1.mp3'
Traceback (most recent call last):
  File "/home/david/quodlibet/quodlibet.py", line 14, in <module>
    sys.exit(main())
  File "/home/david/quodlibet/quodlibet/main.py", line 31, in main
    startup_actions, cmds_todo = process_arguments(argv)
  File "/home/david/quodlibet/quodlibet/cli.py", line 254, in process_arguments
    filename = os.path.abspath(util.path.expanduser(arg))
AttributeError: module 'quodlibet.util.path' has no attribute 'expanduser'

**Comment by davidSchlosser** [comment]
Thankyou!
