### ISSUE TITLE
`pipx` install - quodlibet fails to launch: "No module named 'gi' "

### ISSUE THREAD

**Issue by mojolo** [quodlibet/quodlibet#4316]
**Background:** 
>`quodlibet 4.5.0` is running perfectly on `Kubuntu 23.04`, installed via `apt`.
git branches also run well by simply cloning the git repo and running `./quodlibet.py`
Additionally, git branches installed with `poetry` also run well (see #4296)

That said, `pipx` seems to be a simpler solution if we just want to test the latest features.

However, when running the _pipx-installed_ quodlibet, quodlibet fails to launch because it can't find the `gi` (PyGObject) module.

_Note_: python3 `gi` module (aka `python3-gi 3.44.1` package, aka `PyGObject 3.44.1`) is globally installed via `apt`.
_Note_: `poetry` uses its own `gi` module (`PyGObject 3.42.2`), which it installs into its quodlibet virtualenv.
_Note_: `pipx `does not install its own  `gi` module (`PyGObject`) into its quodlibet virtualenv. it also does not link to the globally installed `gi` module (aka `python3-gi 3.44.1` package, aka `PyGObject 3.44.1`)

Steps to reproduce
------------------
pipx installs quodlibet git without issue:
```
$ pipx install git+https://github.com/quodlibet/quodlibet.git@move-to-libsoup3
OR
$ pipx install git+https://github.com/quodlibet/quodlibet.git

⚠️  Note: exfalso was already on your PATH at /usr/bin/exfalso
⚠️  Note: operon was already on your PATH at /usr/bin/operon
⚠️  Note: quodlibet was already on your PATH at /usr/bin/quodlibet
  installed package quodlibet 4.6.dev0, installed using Python 3.11.2
  These apps are now globally available
    - exfalso
    - operon
    - quodlibet
done! ✨ 🌟 ✨
```

Next, I run:
```
$ hash -r
$ which quodlibet
/home/$USER/.local/bin/quodlibet
$ quodlibet
```

Expected Output
---------------
The _pipx-installed_ quodlibet (home/$USER/.local/bin/quodlibet) should launch normally. `pipx` should have either linked to the globally installed `gi` (PyGObject) module or installed the dependency into its own virtualenv.

Actual Output
-------------
The _pipx-installed_ quodlibet (home/$USER/.local/bin/quodlibet) does not launch because it cannot find the `gi` module.
```
Traceback (most recent call last):
  File "/home/$USER/.local/bin/quodlibet", line 11, in <module>
    from quodlibet.main import main
  File "/home/$USER/.local/pipx/venvs/quodlibet/lib/python3.11/site-packages/quodlibet/__init__.py", line 21, in <module>
    from .util.i18n import _, C_, N_, ngettext, npgettext
  File "/home/$USER/.local/pipx/venvs/quodlibet/lib/python3.11/site-packages/quodlibet/util/__init__.py", line 34, in <module>
    from .misc import cached_func, get_module_dir, get_ca_file, \
  File "/home/$USER/.local/pipx/venvs/quodlibet/lib/python3.11/site-packages/quodlibet/util/misc.py", line 16, in <module>
    from .environment import is_linux
  File "/home/$USER/.local/pipx/venvs/quodlibet/lib/python3.11/site-packages/quodlibet/util/environment.py", line 18, in <module>
    from gi.repository import GLib, Gio
ModuleNotFoundError: No module named 'gi'
```

Test System
-----------
Kubuntu 23.04
quodlibet git (main branch) or quodlibet git (move-to-libsoup3 branch)
Python v3.11.2 (installed via apt)
pipx v1.1.0 (globally installed via `apt`)
`python3-gi 3.44.1` package (ie `PyGObject 3.44.1`) installed globally via `apt`.

**Comment by mojolo** [comment]
Actually, I'm closing this issue because `pipx` fails to install any dependencies in its quodlibet virtualenv.

I'm guessing this is because the `pyproject.toml` file is formatted for `poetry`?

Seems this project wants us to use `poetry`. It works, so I'm OK with that.

**Comment by mojolo** [comment]
Even though I closed this issue last month, I'm following up in case it is helpful to others.

I was able to install from git with `pipx` by emplying the '--system-site-packages' flag, as below:

```
pipx install --system-site-packages --verbose 'quodlibet[musicbrainzngs,dbus-python,paho-mqtt,soco,pypresence] @ git+https://github.com/quodlibet/quodlibet.git'
```
