### ISSUE TITLE
TypeError: type str doesn't define __round__ method

### ISSUE THREAD

**Issue by van-de-bugger** [quodlibet/quodlibet#4339]
Steps to reproduce
------------------

Start QuodLibet, enter the following expression to the search field:

    #(~year = ~originalyear)

Expected Output
---------------

QuodLibet enther shows the result of search or indicates that search expression is invalid (by rendering the search expression in green color).

Actual Output
-------------

Search expression is rendered in *green* color.

Following dialog box appears:

![Screenshot from 2023-07-31 02-27-07](https://github.com/quodlibet/quodlibet/assets/721164/3b85d1ee-766d-4e70-b7a0-54a6fab2b494)

Error details are:

```
TypeError: type str doesn't define __round__ method
------
Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/quodlibet/browsers/paned/main.py", line 143, in __text_parse
    self.activate()

  File "/usr/lib/python3.11/site-packages/quodlibet/browsers/paned/main.py", line 201, in activate
    songs = list(filter(self._filter, self._library))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/quodlibet/query/_match.py", line 164, in search
    if not re.search(data):
           ^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/quodlibet/query/_match.py", line 250, in search
    val2 = self._expr2.evaluate(data, time_, use_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/quodlibet/query/_match.py", line 323, in evaluate
    return round(num, 2)
           ^^^^^^^^^^^^^

TypeError: type str doesn't define __round__ method

```

BTW, If I press "Ignore Error" and then quit, QuodLibet fails to start next time. Being run from the terminal, it prints:

```
$ quodlibet 
E: 3.810: errorreport.main.errorhook: _match.py:323:evaluate: TypeError: type str doesn't define __round__ method
```

The only way to reanimate QuodLibet is removing the line

```
query_text = #(~year = ~originalyear)
```

from `~.quodlibet/config` file.

Test System
-----------

Quod Libet version: 4.5.0 (quodlibet-4.5.0-5.fc38.noarch).
Operating system: Fedora 38.

**Comment by declension** [comment]
Thanks for the report. That's a fairly bad spiral of errors so keen to put some safety nets in there.

However, I can't replicate this here, so I'm guessing it's dependent on some track data.

What I can say is you should try `#(year = originalyear)` (i.e. no tildes for numeric expression variables) and you should probably get the search you wanted. Can confirm _that_ works for me fine here.

**Comment by van-de-bugger** [comment]
> What I can say is you should try `#(year = originalyear)` (i.e. no tildes for numeric expression variables) and you should probably get the search you wanted. Can confirm *that* works for me fine here.

Yes, `#(year = originalyear)` works.

However, my point is not the specific search request, but fact that QuodLibet can be crashed by the user input, and crashed quite badly, so it can't restart. That's the problem.
