### ISSUE TITLE
Unable to rename file

### ISSUE THREAD

**Issue by gevhaz** [quodlibet/quodlibet#4342]
Steps to reproduce
------------------

1. Open "Edit tags" from the context menu of any song in the File System view.
2. Go to "Rename Files" tab.
3. Select one of my patterns.
4. Press Preview.
5. Press Save.

Expected Output
---------------
Song is moved

Actual Output
-------------

Error message:

> Unable to to rename file
>
> Renaming \<b\>01.opus\</b\> to \<b\>/home/me/Music/01.opus\</b\> failed. Possibly the target file already exists, or you do not have permission to make the new file or remove the old one

When running Quod libet from the command line, I see a log like this:

```
E: 35.205: RenameFiles._rename: song.py:69:rename: KeyError: '/home/me/for_sorting/06.opus'
```

Test System
-----------

### Which version of Quod Libet?
4.5.0

### Which operating system 
Arch Linux

Additional Information
----------------------

Pressing "Continue" in the error dialog, then doing another "Preview" and "Save" for the same song makes it actually work. The file is then moved. It is not moved in the first attempt.

**Comment by mikemp7** [comment]
I'm also running into this when trying to edit metadata on a track. 

terminal output: 
`qltk.edittags.__save_files: _util.py:271:_openfile: quodlibet.formats._misc.AudioFileError: [Errno 13] Permission denied: '/home/user/nfs/sets/max_graham_patreon/maxgraham-twitchstream-deepmix-5-23-2020.mp3'`

Notes
- Debian, x86-64
- Library is on a local NAS, mounted via NFS to a local path
- Local file editing works, but editing files mounted via a nfs share on my local NAS does not work

**Comment by mikemp7** [comment]
> I'm also running into this when trying to edit metadata on a track.
> 
> terminal output: `qltk.edittags.__save_files: _util.py:271:_openfile: quodlibet.formats._misc.AudioFileError: [Errno 13] Permission denied: '/home/user/nfs/sets/max_graham_patreon/maxgraham-twitchstream-deepmix-5-23-2020.mp3'`
> 
> Notes
> 
> * Debian, x86-64
> * v4.5.0
> * Library is hosted on a NAS (LAN), mounted via NFS to a local path
> * Local file editing works, but editing files mounted via a nfs share on my local NAS does not work

Update: this is likely due to a permissions issue on the nfs share ...

**Comment by gevhaz** [comment]
My case is different, so I'm reopening. I'm not using an NFS share. I'm using a normal ext4 on an internal drive. I definitely have write-permission to both the source and destination.

The fact that it works if I ignore the error message and click "Save" another time (see my "Additional Information") indicates that it's a QuodLibet issue to me.

I'm happy to assist in debugging. I tried doing some prints around the area in the code  base where the error message comes from but I'm not sure what to print.

Running `quodlibet --debug` gives a bit more context:

```
E: [0142.441] RenameFiles._rename:
    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/quodlibet/qltk/renamefiles.py", line 330, in _rename
        library.rename(song, text2fsn(new_name), changed=was_changed)
      File "/usr/lib/python3.11/site-packages/quodlibet/library/song.py", line 69, in rename
        del self._contents[song.key]
            ~~~~~~~~~~~~~~^^^^^^^^^^
    KeyError: '/path/to/the/file.opus'
```

**Comment by gevhaz** [comment]
More info:

Moving within the same directory or to an existing directory doesn't make a difference – I see the same issue.

I mentioned a workaround in the initial report. For any file, I can ignore the error by pressing 'continue' in the dialog box (here the file remains the same on disk), then change the 'renaming pattern' and change it back again so that I am able to press 'preview' and then 'save' (then it is actually renamed). An additional point to add is that after the first time I do this workaround, I can rename the file without getting any errors from that point onward.

@declension, ping for re-open of issue. I lack permission.

**Comment by chickendude** [comment]
I've had this issue for years, as well. I've just gotten used to going through the process @gevhaz mentioned, namely:
1. Press preview then save
2. Press enter a bunch of times to click on the "Continue" button until all files have been handled.
3. Add a space and remove it somewhere in the rename pattern
4. Press preview and save (it works after this)
