### ISSUE TITLE
Deleting a watched track after it was played in shuffle mode raises AttributeError

### ISSUE THREAD

**Issue by chrisr87** [quodlibet/quodlibet#4348]
Steps to reproduce
------------------
1. Enable `shuffle` and `repeat all`
2. Play any song
3. Hit next to go to the next song
4. Select the previous song and `right click` -> `move to trash`
5. Hit next to go to the next song
6. Crash

Expected Output
---------------
To not crash and play the next song

Actual Output
-------------
```
AttributeError: 'NoneType' object has no attribute 'get_indices'
------
Traceback (most recent call last):

  File "/home/chris/git/quodlibet/quodlibet/util/__init__.py", line 716, in wrap
    return handler(that, *args)
           ^^^^^^^^^^^^^^^^^^^^

  File "/home/chris/git/quodlibet/quodlibet/qltk/controls.py", line 298, in __next
    player.next()

  File "/home/chris/git/quodlibet/quodlibet/player/_base.py", line 274, in next
    self._source.next()

  File "/home/chris/git/quodlibet/quodlibet/qltk/songmodel.py", line 72, in next
    self.pl.next()

  File "/home/chris/git/quodlibet/quodlibet/qltk/songmodel.py", line 260, in next
    self.current_iter = self.order.next_explicit(self, iter_)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/chris/git/quodlibet/quodlibet/order/__init__.py", line 68, in next_explicit
    return self.next(playlist, iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/chris/git/quodlibet/quodlibet/order/repeat.py", line 61, in next
    next = self.wrapped.next(playlist, iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/chris/git/quodlibet/quodlibet/order/reorder.py", line 27, in next
    remaining = self.remaining(playlist)
                ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/chris/git/quodlibet/quodlibet/order/__init__.py", line 138, in remaining
    played = set(map(get_index, self._played))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/chris/git/quodlibet/quodlibet/order/__init__.py", line 136, in get_index
    return playlist.get_path(iter).get_indices()[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'get_indices'

```

Test System
-----------

### Which version of Quod Libet?
4.6 (development)

### Which operating system 
Arch Linux

### If it's audio-related, what back-end?

Additional Information
----------------------
Sometimes I'll restart quodlibet and it'll load up with the same error and forces me to restart again.

**Comment by declension** [comment]
Thanks. Do you have Library Watching turned on in your settings?

**Comment by chrisr87** [comment]
> Thanks. Do you have Library Watching turned on in your settings?

Yes, if it's these settings:

![image](https://github.com/quodlibet/quodlibet/assets/5024506/593a7f77-fa00-4f19-b09a-4038913911fe)

**Comment by chrisr87** [comment]
Thanks looks like [#4382](https://github.com/quodlibet/quodlibet/pull/4382) fixed this
