### ISSUE TITLE
Cannot downgrade from 4.6.0 to 4.4.0

### ISSUE THREAD

**Issue by dpitch40** [quodlibet/quodlibet#4424]
I want to downgrade quodlibet from version 4.6.0 to version 4.4.0 because of [this bug](https://github.com/quodlibet/quodlibet/issues/4386).

Steps to reproduce
------------------
With quodlibet 4.6.0 installed, I run `sudo aptitude install quodlibet=4.4.0-2ubuntu0.1 exfalso=4.4.0-2ubuntu0.1` or `sudo aptitude install quodlibet=4.4.0-2 exfalso=4.4.0-2`.

Expected Output
---------------
quodlibet is downgraded back to version 4.4.0, which was previously working before I upgraded. The documentation should have steps to downgrade Quodlibet due to bugs in the latest version.

Actual Output
-------------
If I install version 4.4.0-2 of quodlibet and exfalso, running quodlibet gives me this error:

```E: 0.155: errorreport.main.errorhook: collection.py:27:<module>: ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/quodlibet/errorreport/main.py", line 175, in errorhook
    sentry_error = sentry.capture(exc_info, fingerprint=fingerprint)
  File "/usr/lib/python3/dist-packages/quodlibet/errorreport/sentrywrapper.py", line 247, in capture
    client = Client(
  File "/usr/lib/python3/dist-packages/quodlibet/packages/raven/base.py", line 224, in __init__
    from raven.context import Context
  File "/usr/lib/python3/dist-packages/quodlibet/_import.py", line 47, in load_module
    mod = importlib.import_module(loadname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/quodlibet/packages/raven/context.py", line 10, in <module>
    from collections import Mapping, Iterable
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/quodlibet", line 14, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/quodlibet/main.py", line 44, in main
    import quodlibet.library
  File "/usr/lib/python3/dist-packages/quodlibet/library/__init__.py", line 20, in <module>
    from quodlibet.library.libraries import SongFileLibrary, SongLibrary
  File "/usr/lib/python3/dist-packages/quodlibet/library/libraries.py", line 32, in <module>
    from quodlibet.util.collection import Album
  File "/usr/lib/python3/dist-packages/quodlibet/util/collection.py", line 27, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

No supported version of Python 3 has `Iterable` and `Mapping` classes defined in the `collections` module. Why does it expect to find them there and not in `collections.abc`?

If I install version 4.4.0-2ubuntu0.1 of quodlibet and exfalso, running quodlibet gives me this error:

```collection.py:686:_populate_from_file: AttributeError: 'NoneType' object has no attribute 'text'```

Test System
-----------
### Which version of Quod Libet?
4.4.0

### Which operating system 
Linux Mint 21.2

**Comment by declension** [comment]
Hi. Sounds like you're on Python >=3.10

The root cause there then is:

> Remove deprecated aliases to [Collections Abstract Base Classes](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) from the [collections](https://docs.python.org/3/library/collections.html#module-collections) module. (Contributed by Victor Stinner in [bpo-37324](https://bugs.python.org/issue?@action=redirect&bpo=37324).)

From [3.10 release notes](https://docs.python.org/3/whatsnew/3.10.html#removed)

See #3818 for more details on the fix.

> collection.py:686:_populate_from_file: AttributeError: 'NoneType' object has no attribute 'text'

Sounds like a separate problem - could you repurpose this bug to be about that, or split it out into a new one?

**Comment by dpitch40** [comment]
Python 3.10 is the only Python version I have installed. How was Quodlibet 4.4.0 previously working with it?
