### ISSUE TITLE
when using global filter: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by dseomn** [quodlibet/quodlibet#4483]
Steps to reproduce
------------------
1. Set the global filter to `genre != "playback/manual-only"`
2. Change the search text in the cover grid browser

Expected Output
---------------
The cover grid should have shown albums matching the new search text.

Actual Output
-------------
I got this error:
```
TypeError: 'NoneType' object is not callable
------
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/quodlibet/browsers/covergrid/models.py", line 254, in _apply_filter
    return filter(item)
           ^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/quodlibet/browsers/covergrid/models.py", line 214, in <lambda>
    f = lambda item: b(item.album) and value(item.album)
                                       ^^^^^^^^^^^^^^^^^

TypeError: 'NoneType' object is not callable
```

Test System
-----------

### Which version of Quod Libet?
4.6.0-1

### Which operating system 
Debian testing

### If it's audio-related, what back-end?
N/A

Additional Information
----------------------
N/A

**Comment by mmuffins** [comment]
I'm running quod libet 4.7.1 on nixos and just ran into the bug. I had the global filter set to `~dirname=!.trash-1000`  and opened the cover grid.
The nasty thing about this bug is that it freezes the application, cannot be dismissed, and pops up as soon as the application start. commandline flags --hide-window or --toggle-window --start-hidden -- and --set-browser don't work, and since the cause seems to be the global filter you also cannot unset it with --unfilter. So basically once you run into this error, the application cannot recover from it. 

In case anyone else has the same issue, the workaround is to edit your config file to remove the global filter:
- close quod libet
- open your config file, by default in `~/.config/quodlibet/config`
- find line `background = ...` in the `[browsers]` section. The line should contain your global filter
- remove the entire line
- start quod libet again
