### ISSUE TITLE
Quod Libet fails to start

### ISSUE THREAD

**Issue by DoughMucker** [quodlibet/quodlibet#4519]
Steps to reproduce
------------------
Previously worked in Ubuntu 22.04. Trying 24.04 and can't open Quod Libet

Expected Output
---------------
Successfuly Launched

Actual Output
-------------
Nothing. Dump attached

Test System
-----------

### Which version of Quod Libet?
4.6 installed via App Center

### Which operating system 
Ubuntu 24.04

### If it's audio-related, what back-end?
n/a

Additional Information
----------------------
=== SYSTEM INFORMATION:
Quod Libet 4.6.0
Mutagen 1.46.0
Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] linux
Platform Linux-6.8.0-31-generic-x86_64-with-glibc2.39
=== STACK TRACE

Traceback (most recent call last):

  File "/usr/lib/python3.12/ctypes/__init__.py", line 450, in __getattr__
    dll = self._dlltype(name)
          ^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^

OSError: libmodplug.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/bin/quodlibet", line 14, in <module>
    sys.exit(main())
             ^^^^^^

  File "/usr/lib/python3/dist-packages/quodlibet/main.py", line 67, in main
    player = quodlibet.player.init_player(wanted_backend, app.librarian)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/quodlibet/player/__init__.py", line 46, in init_player
    backend = init_backend(backend_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/quodlibet/player/__init__.py", line 61, in init_backend
    backend = importlib.import_module(modulename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 995, in exec_module

  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed

  File "/usr/lib/python3/dist-packages/quodlibet/player/gstbe/__init__.py", line 9, in <module>
    from .player import init

  File "/usr/lib/python3/dist-packages/quodlibet/player/gstbe/player.py", line 32, in <module>
    from quodlibet.formats.mod import ModFile

  File "/usr/lib/python3/dist-packages/quodlibet/formats/mod.py", line 21, in <module>
    _modplug = load_library(
               ^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/quodlibet/util/__init__.py", line 963, in load_library
    return load_func(dlopen_name), name
           ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/quodlibet/util/__init__.py", line 948, in <lambda>
    load_func = lambda n: getattr(ctypes.cdll, n)
                          ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/ctypes/__init__.py", line 452, in __getattr__
    raise AttributeError(name)

AttributeError: libmodplug.so.1

=== LOG:
D: [0000.316] util.i18n.init: LANGUAGE: 'en_CA:C:en:C'
D: [0000.316] util.i18n.init: LANG: 'en_CA.UTF-8'
D: [0000.322] util.i18n.register_translation: Translations loaded: '/usr/share/locale/en_CA/LC_MESSAGES/quodlibet.mo'
D: [0000.374] util.importhelper.get_importables: Ignoring '/usr/lib/python3/dist-packages/quodlibet/formats/__pycache__'
E: [0000.468] util.importhelper.load_dir_modules: __init__.py:452:__getattr__: AttributeError: libmodplug.so.1
D: [0000.599] formats._misc.init: MimeType=application/x-flac;audio/aac;audio/aiff;audio/dsf;audio/midi;audio/mp3;audio/mp4;audio/mpeg;audio/mpeg4;audio/mpg;audio/ogg;audio/vorbis;audio/wav;audio/wave;audio/x-aac;audio/x-aiff;audio/x-flac;audio/x-m4a;audio/x-midi;audio/x-mp3;audio/x-mpc;audio/x-mpeg;audio/x-ms-wma;audio/x-ms-wmv;audio/x-musepack;audio/x-oggflac;audio/x-speex;audio/x-tta;audio/x-wav;audio/x-wavpack;audio/x-wma;video/ogg;video/x-ms-asf;video/x-theora;video/x-wmv;
D: [0000.600] formats._misc.init: Supported formats: aac, aiff, dsf, midi, monkeysaudio, mp3, mp4, mpc, spc, trueaudio, vgm, wav, wavpack, wma, xiph
D: [0001.583] qltk.add_signal_watch: Register Python signal handler: 'SIGINT'
D: [0001.583] qltk.add_signal_watch: Register Python signal handler: 'SIGTERM'
D: [0001.583] qltk.add_signal_watch: Register Python signal handler: 'SIGHUP'
D: [0002.674] main.main: Initializing main library (~/.config/quodlibet/songs)
D: [0002.674] SongFileLibrary.__init__: Initializing <class 'quodlibet.library.song.SongFileLibrary'>: 'main'
D: [0002.674] SongFileLibrary.__init__: Initialised <song.SongFileLibrary object at 0x73107876de40 (quodlibet+library+song+SongFileLibrary at 0x1f02de0)>
D: [0002.674] SongFileLibrary.start_watching('main'): Setting up file watches on ['/mnt/nfsMusic']...
D: [0002.674] SongFileLibrary.load: Loading contents of '/home/doug/.config/quodlibet/songs'.
D: [0003.274] SongFileLibrary.load('main'): Done loading contents of '/home/doug/.config/quodlibet/songs'
E: [0003.301] errorreport.main.errorhook: __init__.py:452:__getattr__: AttributeError: libmodplug.so.1

**Comment by DoughMucker** [comment]
Hmm, I installed libmodplug-dev and Quod Libet starts. But should this be a required package?
